### ISSUE TITLE
NullReferenceException in MapRenderer.RenderVectorLayer (Mapsui.Rendering.Xaml)

### ISSUE THREAD

**Issue by drwatson1** [pauldendulk/Mapsui#107]
I use Mapsui.UI.Xaml with WMTS server. Server can return a XML as an error report instead of an image. But BruTile does not check Content-Type unfortunately. When we create a BitmapImage from these bytes later we get an exception. 

If I don't set up logger as this (or something like that):

`Logger.LogDelegate += LogMethod`

than I can get a  NullReferenceException in catch block in this line (method MapRenderer.RenderVectorLayer):

`Logger.LogDelegate(LogLevel.Error, "Unexpected error in renderer", ex);`

Because there is Logger.LogDelegate == null at that moment. We must use Logger.Log instead.
I can create a pull request to correct this. Should I do it?

**Comment by pauldendulk** [comment]
ah, yes! You are right. The logging functionality was added relatively recently. I could have more errors like this. Also the logger probably needs to be used in more places.

**Comment by pauldendulk** [comment]
Do you want to enter a pull request for this specific issues or do you want me to fix it?

**Comment by drwatson1** [comment]
I have strange problems with your last commits. There are some line ending problems I think. 
Please, fix this by yourself. I found one more place with the same problem - Mapsui.Rendering.Skia/RasterRenderer.cs in addition to Mapsui.Rendering.Xaml/MapRenderer.cs

**Comment by pauldendulk** [comment]
ah, sorry about that. I wanted to fix this by adding a .gitattributes but messed things up. Inquired about it today. Will fix it.

**Comment by pauldendulk** [comment]
I changed all the line endings to CRLF in this commit: https://github.com/pauldendulk/Mapsui/commit/3191cedab8bccf373993ed46a4725b78e3f2d9d3
Most of the LF line endings are probably from my work with Xamarin Studio. I still don't quite understand why my recent commits turned line endings to LF. 

I used the Line Endings Unifier for this: https://marketplace.visualstudio.com/items?itemName=JakubBielawa.LineEndingsUnifier. Perhaps you could use it on your repo to get it into sync with the current master.
