### ISSUE TITLE
Overlay tile layers with different projection

### ISSUE THREAD

**Issue by Kibnet** [pauldendulk/Mapsui#113]
I have tile layers in the projection "EPSG:4326" and "EPSG:3395". How can I convert them into one projection, so that when overlaid on each other, they coincide?

**Comment by pauldendulk** [comment]
Mapsui has limited support for projection of coordinates. It is has just SphericalMercator en WGS84 built in, and nothing else. It is possible to inject your projection if you use your own library to calculate the projection.

Mapsui has no support for projection of tiles. Although this functionality would be welcome there are disadvantages. It will be ugly, there will be lines in between tiles, and it will be slower. Some other tools use it. It is nice to compare between layers but for a proper app it is not a great solution.

So the best option would be if you try to get all your tile layers in the same projection.

**Comment by Kibnet** [comment]
Honestly, the lines between the tiles visible now, even for spherical Mercator projection.

**Comment by pauldendulk** [comment]
Yes, there are lines in WPF, but that is an issue with WPF. There are no lines in Skia rendering. 

It is actually quite a lot of work and moreover some technical decisions need to be made. For starters there has be transformation from and to EPSG:3395. You could use a library but I would then prefer to keep it outside of Mapsui. If you have a simple calculation we could add it. 

Another thing we need to figure out is how to draw a tile that is not rectangular. This needs to done in Skia and WPF.

**Comment by Kibnet** [comment]
#112 In this commit there is a simple calculation of the coordinates in the spherical projection and back

**Comment by pauldendulk** [comment]
Thanks, it was merged. Next you could add it to MinimalTransformation and see if it works for a single point by adding one in projection sample.

**Comment by pauldendulk** [comment]
Another thing that needs to be done is figure out how to draw a skewed bitmap in SkiaSharp. (BTW, what platform are you using, because for desktop WPF might stay preferred for a while). In Mapsui this will be represented as a geometry of for points (it will not be square anymore) with a bitmap as some kind of skin. In the SkiaSharp samples I see something directly related to this. The research for this could be done outside of Mapsui.

**Comment by pauldendulk** [comment]
Also I think the best approach would be to add a specific TransformingTileTiler (at least initially). This layer should the Transform similar to Layer. The current TileLayer only renders when the map CRS is identical to it's own CRS.

**Comment by pauldendulk** [comment]
btw, I still think it would be best to find another solution for this. Tile services are meant for fast performance. If you just need an overlay a WMS is a better solution.
