### ISSUE TITLE
Can not install it on a Portable Project ( PCL )

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#120]
I've tried a number of configurations, but each of them ended with a different kind of rejection either from BruTiles or Skia.
What kind of configuration I shall use in order to use the latest version with PCL projects ?

The current output is result of a perfectly new project.
File->New Project -> Black App (Native Portable).
.NET Framework 4.5.1

> Attempting to gather dependency information for package 'Mapsui.0.10.14' with respect to project 'App11', targeting '.NETPortable,Version=v4.6,Profile=Profile44'
> Attempting to resolve dependencies for package 'Mapsui.0.10.14' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'Mapsui.0.10.14'
> Resolved actions to install package 'Mapsui.0.10.14'
> Adding package 'BruTile.0.19.0' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Added package 'BruTile.0.19.0' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Added package 'BruTile.0.19.0' to 'packages.config'
> Successfully installed 'BruTile 0.19.0' to App11
> Adding package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Added package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
> Executing script file 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'...
> Successfully installed 'Newtonsoft.Json 9.0.1' to App11
> Adding package 'SkiaSharp.1.55.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Added package 'SkiaSharp.1.55.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Added package 'SkiaSharp.1.55.1' to 'packages.config'
> Successfully installed 'SkiaSharp 1.55.1' to App11
> Install failed. Rolling back...
> Package 'SkiaSharp.Views.1.55.1 : SkiaSharp [1.55.1, )' does not exist in project 'App11'
> Removed package 'SkiaSharp.1.55.1' from 'packages.config'
> Removed package 'Newtonsoft.Json.9.0.1' from 'packages.config'
> Removed package 'BruTile.0.19.0' from 'packages.config'
> Package 'SkiaSharp.Views.1.55.1 : SkiaSharp [1.55.1, )' does not exist in folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Removing package 'SkiaSharp.1.55.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Removed package 'SkiaSharp.1.55.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Removing package 'Newtonsoft.Json.9.0.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Removed package 'Newtonsoft.Json.9.0.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Removing package 'BruTile.0.19.0' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Removed package 'BruTile.0.19.0' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App11\packages'
> Could not install package 'SkiaSharp.Views 1.55.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
> ========== Finished ==========

**Comment by pauldendulk** [comment]
That template creates a PCL with Profile259. Mapsui's Profile111 can not be installed into this. Profile259 is compatible for example Silverlight, Mapsui isn't. PCL profile compatibility is complicated. This is why Microsoft is now changing to the dotnetstandard profiles. So try to create a PCL with Profile111.  BTW, Mapsui is also not compatible with the WindowsPhone project generated by that template. Perhaps you should just add the different projects separately.

**Comment by YordanYanakiev** [comment]
Just tried another configuration without Silverlight.

> Attempting to gather dependency information for package 'Mapsui.0.10.14' with respect to project 'App15', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
> Attempting to resolve dependencies for package 'Mapsui.0.10.14' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'Mapsui.0.10.14'
> Resolved actions to install package 'Mapsui.0.10.14'
> Adding package 'BruTile.0.19.0' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Added package 'BruTile.0.19.0' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Added package 'BruTile.0.19.0' to 'packages.config'
> Successfully installed 'BruTile 0.19.0' to App15
> Adding package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Added package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
> Executing script file 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'...
> Successfully installed 'Newtonsoft.Json 9.0.1' to App15
> Adding package 'SkiaSharp.1.55.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Added package 'SkiaSharp.1.55.1' to folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Added package 'SkiaSharp.1.55.1' to 'packages.config'
> Successfully installed 'SkiaSharp 1.55.1' to App15
> Install failed. Rolling back...
> Package 'SkiaSharp.Views.1.55.1 : SkiaSharp [1.55.1, )' does not exist in project 'App15'
> Removed package 'SkiaSharp.1.55.1' from 'packages.config'
> Removed package 'Newtonsoft.Json.9.0.1' from 'packages.config'
> Removed package 'BruTile.0.19.0' from 'packages.config'
> Package 'SkiaSharp.Views.1.55.1 : SkiaSharp [1.55.1, )' does not exist in folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Removing package 'SkiaSharp.1.55.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Removed package 'SkiaSharp.1.55.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Removing package 'Newtonsoft.Json.9.0.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Removed package 'Newtonsoft.Json.9.0.1' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Removing package 'BruTile.0.19.0' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Removed package 'BruTile.0.19.0' from folder 'c:\Users\Yordan\documents\visual studio 2015\Projects\App15\packages'
> Could not install package 'SkiaSharp.Views 1.55.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
> ========== Finished ==========
>

**Comment by YordanYanakiev** [comment]
P.S.
 - 0.9 worked flawlessly. None of 1.x is working now as I am trying to upgrade the project.
I am adding a screenshot of the settings I am trying, still no change.
![net3cnf](https://cloud.githubusercontent.com/assets/6534199/22247032/6e3658de-e240-11e6-9a9f-652c8fa3742e.jpg)

**Comment by pauldendulk** [comment]
Thanks for all the info. I can indeed reproduce it by installing into a Profile111.  I think it is caused because I specified SkiaSharp.Views as a dependency for the whole project while it should be a dependency for UI projects only.

**Comment by pauldendulk** [comment]
Mapsui 0.11.0 should fix this issue.

**Comment by pauldendulk** [comment]
Rather use 0.11.1

**Comment by YordanYanakiev** [comment]
Confirmed. It installed this time on a new project! Thanks for the lighting fast patching Paul !

**Comment by pauldendulk** [comment]
Thanks!
