### ISSUE TITLE
Getting a red screen within Android sample project with v0.11

### ISSUE THREAD

**Issue by TomWalkerCodes** [pauldendulk/Mapsui#121]
I've downloaded the zip of the latest project source with samples.  I'm getting a red screen when I'm running include Android.   

![mapsui red android screen](https://cloud.githubusercontent.com/assets/7881072/22275331/09eb7f78-e27a-11e6-9ef2-2011a55ab37b.jpg)

**Comment by pauldendulk** [comment]
Sorry about that! Fixed in 0.11.1. This was experimental code accidentally committed while fixing the PCL bug.
