### ISSUE TITLE
Markers for click/touch events

### ISSUE THREAD

**Issue by HaidelBert** [pauldendulk/Mapsui#128]
Hallo,

is there a way to add Markers in MapsUI like in google maps? If not, what would be the best way?

Many thanks
Alex

**Comment by pauldendulk** [comment]
If you start the Mapsui.Sample.Wpf sample there is a 'Various' sample that uses bitmaps as markers. [This](https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/VariousSample.cs) is source file. Is this what you mean?

**Comment by HaidelBert** [comment]
Thanks for the fast reply. 

Well, nearly. Actually I need to draw images from urls. Is that possible?

**Comment by pauldendulk** [comment]
What you could do in you map configuration method is to fetch the image stream from the url with HttpClient. You could then use that stream to register as a bitmap with something like this:
```
BitmapRegistry.Instance.Register(imageStream);
``` 
Look for the last few methods of VariousSample.cs. Replace ```assembly.GetManifestResourceStream(imagePath);``` with a HttpClient fetch.

You might need to copy the stream to a memory stream to make sure it is not disposed outside of the scope of the HttpClient.

**Comment by HaidelBert** [comment]
Thanks a lot!

**Comment by pauldendulk** [comment]
In your title you mention touch. This is a separate thing. Look at the Info
sample for that.

Op 10 feb. 2017 11:16 schreef "HaidelBert" <notifications@github.com>:

**Comment by HaidelBert** [comment]
I used the Info callback for the touch stuff.
