### ISSUE TITLE
The hit area of the touch event is not always correct

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#129]
The size of the symbol is now always assumed to be 32x32. It should be based on the actual symbol size, image or vector. This is not easy to implement in Mapsui as it is now. This is because we know the image size only after it is decoded and decoding is done in the renderers and depends on the renderers implementation (wpf or skia). Possible solutions:

- Add a SkiaSharp dependency to the Mapsui dll and use it to determine the size. Problems:
  - The SkiaSharp PCL is a bait and switch dll (I assume, it has to be, no?) so the Mapsui dll can't be used without a head that uses SkiaSharp.
  - The decoded image can not be used by WPF (I think). So we need to keep both the undecoded stream and decoded image in memory. This is more memory (probably not a lot for symbol images) and confusing.
- Inject and image decoder to Mapsui. This will make use of Mapsui harder.
- Assign the width and height of the symbol after it is decoded by the renderer. This makes it the responsibility of the renderer which is a bad thing.

**Comment by pauldendulk** [comment]
Some more options:
- Get image dimensions with some generic .net code that does not depend on renderers. Research so far shows this is hard.
- Pass the the dimension information from that MapControl (that has a specific renderer) to the GetFeatureInfo method. This seems to be the best solution so far.

**Comment by pauldendulk** [comment]
I've chosen the last option. Introduced a symbol cache and passed to the feature info method.

**Comment by pauldendulk** [comment]
Fixed with https://github.com/pauldendulk/Mapsui/commit/a459ca0c20a2a53c5b03d5bc76ad6fdcfcdda4e9

Not yet ignoring transparent parts of bitmap.

**Comment by Visutronik** [comment]
Hello,
do you have an example for a "click on" marker and then show a label?

Best regards,
Christian

**Comment by pauldendulk** [comment]
@Visutronik in Demo -> Map Info you can click a geometry and see it's name bottom left.

**Comment by Visutronik** [comment]
Thanks alot,
i have found the methods in https://github.com/Mapsui/Mapsui/tree/master/Samples/Mapsui.Samples.Wpf for WPF.
