### ISSUE TITLE
ios: Add a constructor to MapControl to allow its use from within a Storyboard

### ISSUE THREAD

**Issue by softlion** [pauldendulk/Mapsui#130]
In an iOS Storyboard you can add a UIView and specify "MapControl" as the custom class name. Then you can add contraints and properties/custom properties to the view visually.

For this to work, the MapControl class must have a specific contructor. Code:

        [Preserve]
        public MapControl(IntPtr handle) : base(handle)
        {
            ... call Initialize() ?
        }

Could you add it ?
Ty !

**Comment by pauldendulk** [comment]
Thanks for the feedback. I will add it.

**Comment by pauldendulk** [comment]
I added the constructor and moved the frame initialization to the ```Frame``` setter.

**Comment by pauldendulk** [comment]
This is now released in 0.12.0
