### ISSUE TITLE
Coordinate System Unclear

### ISSUE THREAD

**Issue by SimplexAuctor** [pauldendulk/Mapsui#134]
Looking at the code it looks like a Feature's geometry point would be in latitude/longitude.  But in actuality it seems to be something like lat/lon but multiplied by a little over 100,000.  What is the correct way to convert between lat/lon and Mapsui points?  Using the Mapsui.Geometries.Point.FromDMS provides points that are all quite close to 0,0 (near Africa), so it doesn't seem like the way to go.

**Comment by pauldendulk** [comment]
The Mapsui MapControl has no specific coordinate system, only the map has. The openstreetmap layer that is used most often is in a coordinate sytem called SphericalMerator. You can transform point in lat/lon (or WGS84, or EPSG4326) using SphericalMercator.FromLonLat(...). See [this](https://github.com/pauldendulk/Mapsui/tree/master/Mapsui/Projection).

**Comment by pauldendulk** [comment]
You could create dynamic projection like [this](https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/ProjectionSample.cs). To improve this Mapsui should pick a specific projection library so we could support most any projection. Perhaps I should add some classes to make this specific scenario easier. Like a layer that does this projection automatically without further configuration. ```LatLonToOsmLayer```.

**Comment by SimplexAuctor** [comment]
Thanks, That helps a lot!
