### ISSUE TITLE
Click on marker

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#136]
Hi

I've created the markers I need, now I just need some click event's.
Got lot's of different markers in the app, some are click markers, that need to trigger event on click. Some just change color on click.
I've tried the Info callback through map. But really small place I can click, and when I added offset, I need to click in bottom of the marker. And the callback doesn't write LayerName, it's always empty.

Isn't there a better way to make the clickable marker, is really a killer for our app. ? 

Br. John Sørensen

**Comment by pauldendulk** [comment]
This is a still open issue that needs to be addressed soon: https://github.com/pauldendulk/Mapsui/issues/129
It is now possible to increase the hit area by setting the static fields `SymbolStyle.DefaultWidth` and `SymbolStyle.DefaultHeight`. For the offset there is no such workaround.

A workaround that we used in WPF is to add WPF element on top of the MapControl and position then on ViewportChanged. You basically make your own platform specific layer. This is not the best solution if you want performance. I think this is not the best way to go.

Perhaps it is possible to work with symbols without offset until this functionality is fixed.

**Comment by johnhs91** [comment]
Well i've made my own workaround, since I need a better click event all around, so i've taking my own I used in OsmSharp, and implemented in Mapsui :) Untill now it work very well.
About size of symbols, i've changed this to my own size, since I only use 1 size marker all around the app, and made a offset specified too.

Br. John Sørensen

**Comment by pauldendulk** [comment]
How did you do that? Registered to the MapControl.Touch event and handled it there?

How is the performance in Mapsui compared to your OsmSharp solution?

**Comment by pauldendulk** [comment]
btw, What platform(s) are you using?

**Comment by johnhs91** [comment]
I'm using Xamarin.Forms, and work only with android and iOS.
I've changed abit in both platforms, since I need a map click,map double click and marker click.

I've changed InvokeInfo to InvokeClick, since I don't want it to invoke both map click and info click same time, so it check if there are any info, if not, then it invoke map click.
The doubleClick do invoke Click twice, but since I never use both in same context, it's no problem for me.
So all I did is add some code in MapControl.MapView_Touch and Map.InvokeClick (Old Map.InvokeInfo). and added a Map.InvokeDoubleClick.

Still got few problems with Info click, because of the offset, that's what I'm currently working at.

About the performance, I don't know yet sadly. I'm making a new project to make all the features we need, and afterwards I will add to our app to see if it's better.
But to be hornest if it's abit slower I don't mind, the only issue we got is memory on android, OsmSharp crash so much because it doesn't release correctly.

**Comment by johnhs91** [comment]
And added a threshold to x and y to click in MapControl, since I don't want it to call click if you are dragging or zooming.

**Comment by charlenni** [comment]
Is it an open project? I started a fork to integrate Mapsui in Xamarin.Forms. So it would be helpful to see, how others did it.

**Comment by johnhs91** [comment]
There was an example somewhere in this forum. Don't remember where.
But it's actualy easy to implement in Xamarin.Form's since there are very little code that's platform specified in Mapsui.
MapControl is only platform specified, that's a very good thing.
This example doesn't add a TileLayer, see example to do that :)

Android renderer:

```
    public class MapsuiViewRenderer : ViewRenderer<MapsuiView, Mapsui.UI.Android.MapControl>
    {
        Mapsui.UI.Android.MapControl mapControl;
        MapsuiView Ele;

        protected override void OnElementChanged(ElementChangedEventArgs<MapsuiView> e)
        {
            base.OnElementChanged(e);

            if(Ele == null && e.NewElement != null)
            {
                Ele = e.NewElement as MapsuiView;
            }

            if(mapControl == null)
            {
                mapControl = new Mapsui.UI.Android.MapControl(Context, null);
                mapControl.Map = Ele.Map;
                SetNativeControl(mapControl);
                Ele.TakeScreenShot += takeScreenshot;
            }
        }
    }
```

Xamarin.Forms:

```
    public class MapsuiView : View
    {
        /// <summary>
        /// Map
        /// </summary>
        private Map map;
        public Map Map
        {
            get { return map; }
        }

        /// <summary>
        /// Constructor
        /// </summary>
        public MapsuiView()
        {
            CreateMap();
        }

        /// <summary>
        /// Create map, and set some props
        /// </summary>
        public void CreateMap()
        {
            map = new Map();
        }
    }
```

**Comment by charlenni** [comment]
Ah, than you do all things with underlaying Map object.

I try to expose some events to Xamarin.Forms. Or do you think, that this is useless and all should work with Map?

**Comment by johnhs91** [comment]
Yes can almost do everything with the Map object, got an event to call a screenshot methode, it's almost it :)
I'm not done yet, so don't know if there will be more yet.
