### ISSUE TITLE
Zoom level

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#139]
Hi

How do I set the current zoom level?
If I want it to start at 6-8?

Br. John Sørensen

**Comment by pauldendulk** [comment]
Here is an example:
https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/CenterOnLocationSample.cs

**Comment by johnhs91** [comment]
Thank you very much.
