### ISSUE TITLE
Rendering issues when map change parent

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#140]
Hi 

We have a page where a map can be shown in different size's in XF.
When it change view, I remove the view and add again in different or same layout.
Problem is, when I do so, it don't render TileLayer afterwards, the Markers (Normal image layers load fine)

Also got problems first time it load, then it load tile fine, but markers don't show before some layer is changed. I've checked it do render tile first and markers afterwards, as it should.

Br. John Sørensen

**Comment by johnhs91** [comment]
I've tried a Invalidate on change in my own android renderer, aswell as  Mapsui's own android renderer. Didn't help at all.

**Comment by johnhs91** [comment]
Didn't see I actualy get an error in our log.

System.ObjectDisposedExceptionCannot access a disposed object. Object name: 'Mapsui.UI.Android.MapControl'.

**Comment by pauldendulk** [comment]
So what exactly are you doing? You remove the MapControl from the view, keep the MapControl in memory and then add it back again to the view? How could I reproduce this if I took one of the samples as a starting point?

**Comment by johnhs91** [comment]
It must be my own code issue, just made a sample for you, then it work to perfection.
