### ISSUE TITLE
Density android

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#141]
Hi

You don't check up on density when rendering the map or markers, is that correct?
When I got the map on samsung s5 or samsung cam2 it's 2 different density, mean 2 different markers sizes and zoom is 2 different. Is there a easy way to solve this?

Br. John Sørensen

**Comment by pauldendulk** [comment]
Could you post screenshots? And what are the densities? And how do you think this should be resolved?

**Comment by johnhs91** [comment]
Can't take screenshot on my cam 3, don't know why. But I zoom into Denmark on 1 of them, then I only see Denmark and abit of Sweden. But on other mobile (With larger screen) I see part of England, Poland, Germany, Norway. Because it got bigger screen. That's what density is made for.

**Comment by pauldendulk** [comment]
With so many different devices zooming to a resolution could always lead to different results. You could try to use ZoomHelper.ZoomToBoundingBox to get a result that is closer to what you expect.

The different symbol sizes is probably something that should be improved.

**Comment by johnhs91** [comment]
Thank you.

But the marker/layers is unuseable as it's now, since I almost can't see markers on one screen and the other it's almost to big. Is it possible to find a solution on this one fast?
The problem is, I got the click event, and can't click on the small markers sadly.

**Comment by johnhs91** [comment]
Well the problem kinda keep exist in map I see, because of the density, I can't read the text on the tile. 
This also make it way slower, since it renderer much more tiles and wrong zoom.
Ill send some screenshots in 10 minutes

**Comment by johnhs91** [comment]
![55fffab8-cf6f-4e2a-97f3-7599ff5cb3ef](https://cloud.githubusercontent.com/assets/4305618/23707431/9edadca0-0412-11e7-8836-686e8a7c5b27.png)
![a649cd3e-f1bf-4a78-930f-37a1bcdaba2d](https://cloud.githubusercontent.com/assets/4305618/23707432/9ef9a5ea-0412-11e7-94a0-aed4ca3957c1.png)

**Comment by johnhs91** [comment]
OsmSharp worked different, it always show map in same size with same tiles.. here you see one of them show different tile, because it's zommed further, but not rly.
That's why density needs to be included in the calculation, or it kinda ruin it all.

**Comment by pauldendulk** [comment]
Could you check if the last [commit](https://github.com/pauldendulk/Mapsui/commit/abc4b853cfa473fe26f634ea57925508a72c64c6) fixes your density issue. I only tested on 1 device. It had a density of 1.33  which cause an increase in size of the markers.

**Comment by pauldendulk** [comment]
btw, I noticed that on some deployments I don't get any tiles at all. I hope this a glitch of my device. If not I suspect the latest BruTile has a problem with a HttpClient lock state.

**Comment by johnhs91** [comment]
After your update I don't get tiles at all :/ Didn't do other than update your android code.

**Comment by johnhs91** [comment]
But it looks like markers are almost same size, not 100% sure.

**Comment by pauldendulk** [comment]
I assume this is caused by the use of HttpClient in BruTile 0.20.0. Perhaps you can revert to BruTile 0.19.0 to check that. 

I won't be able to fix this today.

Is your project using the nuget packages or the code?

**Comment by pauldendulk** [comment]
I created a bug for not rendering tiles:
https://github.com/pauldendulk/Mapsui/issues/144

**Comment by johnhs91** [comment]
Well don't understand how it can be BruTile if it worked before your own update.
Anyway, was using 0.19.0 already, tried to change the 1 in Mapsui to 0.19.0, didn't work.

**Comment by pauldendulk** [comment]
It could also be related to the attribution changes. Perhaps you can revert the MapControl to the earlier version and then just add the changes related to density/scale.

**Comment by johnhs91** [comment]
Just used time on revert to https://github.com/pauldendulk/Mapsui/blob/42169a532b75f3fc3d1032c35efae780286676d6/Mapsui.UI.Android/MapControl.cs

**Comment by johnhs91** [comment]
However this works perfectly

**Comment by johnhs91** [comment]
I took the working one, and made scale myself.
Good result, only need to change some zoom settings.

2 samples, that show same marker, and what looks like same zoom lvl tiles.!
![ac6b3479-9077-4230-84a5-60c038659fe1](https://cloud.githubusercontent.com/assets/4305618/23745844/0eea0c58-04ba-11e7-94bc-8971a57cf9fd.png)
![1520ae05-cf32-4a33-a414-d85d58aea1c3](https://cloud.githubusercontent.com/assets/4305618/23745843/0ee5baae-04ba-11e7-92f7-22958825ed85.png)

**Comment by johnhs91** [comment]
Same 2 unit's as I sent SS of before.
Work perfectly now. Thank you very much.

![731ed1fc-dd5c-4273-8746-1f61e1e056bd](https://cloud.githubusercontent.com/assets/4305618/23746544/a1056a18-04bc-11e7-85b2-b1a3a03f8108.png)
![e046bf20-5274-4500-b4c4-1d596f12bb6d](https://cloud.githubusercontent.com/assets/4305618/23746545/a105e86c-04bc-11e7-8e8c-0daca2a1e6aa.png)
