### ISSUE TITLE
Resize of MapControl

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#145]
Xamarin.Forms make a relayout if you turn the device. Than the MapControl changes its size. After this event, the map doesn't fill the whole view. See this screenshot:

![grafik](https://cloud.githubusercontent.com/assets/4381223/23752169/7f020332-04d4-11e7-923f-dd600ebfdb73.png)

I don't know, where to start to solve this problem. Any hints?

PS: This is for Android, but could be relevant for iOS and UWP too. Have to test this.

**Comment by pauldendulk** [comment]
I will take a look tomorrow.

**Comment by pauldendulk** [comment]
In my sample I added this to prevent destroy.

```
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
```
In the MapControl I now set the new size on the Viewport

```
            Map.Viewport.Width = Width / _scale;
            Map.Viewport.Height = Height / _scale;
```

See commit:
https://github.com/pauldendulk/Mapsui/commit/5a8ab6da44a9b799f66cf622315447a27da3a7e5

This should fix it. Could you check?
