### ISSUE TITLE
Overlays: Unmovable layers

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#146]
Normal layers are all for things which move with the map like tiles or markers. But there are some things, that don't move with the map, but stay still in the view. One is the Attributation, which is now inserted automatically by MapControl. Another could be a scale, which shows a ruler on top of the map.

For this, there could be a new object type: Overlays. They are drawn on top of the canvas after all other layers are drawn. 

I have implemented such an overlay in my [Overlays branch](https://github.com/charlenni/Mapsui/tree/Overlays) The only up to now, which is working, is the center overlay, which draws a cross in the center of the control. It works with the Android and iOS sample.

Now my question: is this helpful or is it possible with the normal layers?

**Comment by pauldendulk** [comment]
Hi @charlenni ! This is great idea. The current layers do not support this. I think there are a lot of components that could be developed like this, like scalebar, legend and such. However, while working on attribution I realized I am not enough of an expert of the various UI platforms to maintain a library with a heavy focus on such UI components. What I want to focus on myself is good cross platform support, the geospatial aspect, rendering and performance. 

It should be possible to develop such components separate from this library. So I think such a library could form a separate project with it's own nuget package and a dependency on the Mapsui nuget package. I would like to participate in such a project also. Such components could also be put on top of the MapControl or in some case next to it. Perhaps injecting such component as part of the map could also be useful. We might have to add an IOverlay interface to allow this. Mapsui might need other modifications to improve this integration.

What do you think of this approach?

**Comment by charlenni** [comment]
Most of the overlays I could imagine are easy to draw. A cross for the center, a scale bar, the attribution. Perhaps some buttons for zoom or orientation. Nothing were we need a big UI. Look on Google Maps.

So what you need is an interface like ILayer. The classes, which implement this intetface hold all data needed for this overlay. At the same place where Layers are drawn, Overlays are drawn too. You need a Skia version and one for the other drawing interface. That's all. Because such overlays are not very complicated, they are drawn each time the map is drawn.

For buttons it would be useful, if we could have tap aware regions on the overlays.

Look at this first implementation I did. If there is enough time, I try to implement the scale bar overlay in the next days.

**Comment by pauldendulk** [comment]
Just took a look. This is indeed not something for a separate project. I expected it to be some kind of ui components. I was thinking such a component could also be placed outside of the map. You are using the renderer. 

A disadvantage of using the renderer for this is that it won't work for other renderer, and although I only have two renderer right now this could change again. For instance, Unity3D was mentioned last week. In the past I had renderers for GDI+, CompactFramework, Windows Phone, OpenTK, MonoGame and more.

It might be possible to use Skia and inject the Skia part into another renderer. Or just create a UIComponent and render within that component with Skia, independent of the MapRender. Sound not like a bad idea right now.

Maybe you can help me with this compile error, so I can see it in action. 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 3: cannot convert from 'Mapsui.Styles.Color' to 'System.Collections.Generic.IEnumerable<Mapsui.Overlays.IOverlay>'	Mapsui.Rendering.Skia.Tests, Mapsui.Rendering.Xaml.Tests	C:\code\github\MapsuiCharLenni\Tests\Mapsui.Rendering.Xaml.Tests\MapRendererTests.cs	29	Active
```

**Comment by charlenni** [comment]
Sorry for the problems. I didn't update the test for the new Render call. It now includs not only Layers, but Overlays in function calls too. Now it should work.

But what is the alternative for such things? Now you have to implement the functionality for Skia and XAML. If you use UI elements, you have to implement it for WPF, iOS, Android and all other platforms you want. I think, that is much more work. And I assume, that you will end with Skia. But there is no problem, if you want a new library. Like the Renderer for Layers, you have to make the renderer for Overlays too. A little bit more work, but easy to do. 

And why do you use Skia for Layers? Why don't you use platform specific drawings? Because it is to much work to do the same work for each platform.

To be clear: I don't want Overlays for normal UI elements. I want them for special cases like a cross in the center, a scale bar for the map or attribution. This things had to be drawn on each platform by hand too. There is no ready made scale bar in any of the UI.

**Comment by wangjianpeng** [comment]
i found you say you had render monogame ,and plan to unity3d, do you have these project sample ?

**Comment by pauldendulk** [comment]
No. I have not done anything with unity3d yet and the monogame project is not open source. If you want to write something like that start with the FeatureIterator used in the Skia renderer and start to implement the raster renderer.

**Comment by pauldendulk** [comment]
Fantastic feature! It is just lovely to see the smooth automatic readjustment of the scale bar. I like the way you separated the definition of the scale bar and the rendering of it. I am not sure if I would like to render it in MapRenderer, but I have no specific alternative in mind. It would be nice if I could use this on top of WPF as well, maybe render it inside a little SkiaSharp element.

The text is a bit blocky but it does not seem to improve if I use IsAntiAliased or something like that. There should be a way to improve this.

The scale factor in the ScaleBarOverlayRenderer should perhaps be based on the density (in android).

**Comment by pauldendulk** [comment]
btw, why do work with Android and not with UWP. Are you on Mac? If now is it really faster than UWP? Which emulator do you use?

**Comment by charlenni** [comment]
No, I'm not on Mac, even if I have one :). But to start two machines is to annoying. I normally work on Android or iOS and had never tested UWP. But if you ask, I did it now.

Yes, the automatic update is a nice feature. But a case is missing: if you go in north-south-direction, the scale bar changes. The scale bar should redrawn in this case too.

Render in WPF shouldn't be a problem. You only need a renderer for this, which could draw lines and text. That's all. 

For the text I tried many different things, but couldn't get any better results. Perhaps the font is wrong?

For the scale factor: I know, that this should be changed, but I don't know, what to use. Any suggestions?

I included now a new ovlerys sample into the common sample, but have problems with UWP. The scale bar isn't drawn. I get the blank background, but any DrawLine or DrawText aren't visible. Nothing changed in the render code from Android. Should work out of the box, but doesn't. Any idea?

**Comment by pauldendulk** [comment]
Thanks for testing UWP. I was curious why Android was fast for you because for me it is much slower than UWP.

About the blocky font. I now think this is because you write to bitmap and then write that bitmap to the canvas. I noticed before this becomes ugly in Skia. I suspect it has something to do with premultiplied alphas, but I cannot fix it by initializing the bitmap with unpremul. You could test it by directly writing the font to the canvas.

Also, it might help to draw the bitmap on discrete pixel positions so there is no pixel interpolation when drawing. I did something like this when drawing the labels, rounding the x and y.

**Comment by pauldendulk** [comment]
Hopefully I will have time to take a closer look. I will create a fork of you fork and send PRs as way to interact and discuss the code. 

Did you have any other plans with this?

**Comment by pauldendulk** [comment]
hi @charlenni, Just took some more time to look at the overlays. I don't have any specific PR's at this point. I think it should first work correct on all platforms before I can judge if my own changes make sense. 

I have not decided how functionality like this should be attached to Mapsui. There should be some way to add custom overlays without the need to change the MapRenderer. Maybe it should be possible to add custom renderers. This could be done with some fancy plugin model. Alternatively we could also just expose the Skia canvas so that a user could do anything by drawing on it.

**Comment by charlenni** [comment]
Thank you Paul for coming back to this.

But isn't the MapRenderer the right place for such things? There should be drawn all things, that are shown on the map. And to expose the Skia canvas doesn't help for WPF.

Another possibility is to have a flag for Layers, which decides, if the features are in world coordinats or screen coordinates. Than you could create such things with features. Is there a text feature? I'm not really firm with your code. Sorry.

**Comment by pauldendulk** [comment]
The main motivation for decisions like this is to keep maintainability code. I don't want the MapRenderer to have knowledge of specific overlays. You could circumvent this by adding some overlay interface and adding a registry for renders for these overlays. This is also adds a further complication of the MapRenderer. 

The flag idea sounds interesting. It might be a relatively easy to implement. You would have the advantage that it would work for different renderers. A limitation would be that you have to work with geospatial geometries that are not designed to create just any layout. There will be requests for additional features for this, and this could lead to a lot of scope creep. If it can be done with just a few changes it would still be a good option.

You could add text with LabelStyle.

Another option would be to use a standard format like SVG as a way to specify an overlay. I would like to have SVG rendering for symbols anyway. SVG support is not here yet: https://github.com/mono/SkiaSharp/issues/258. Although there is a SkiaSharp.Svg package: https://www.nuget.org/packages/SkiaSharp.Svg/

**Comment by charlenni** [comment]
But you need only a few elementary geometries (line, polygon, circle, text, bitmap) and all of them should be implemented allready. Or not?

SVG is a good idea too, but that means, that you could add it to Mapsui in any way. So you had to think about a special Overlay class or use Layer with a flag. If not, you have to make a special MapRenderer ;)

**Comment by charlenni** [comment]
If I look through the code, you use everywhere the Viewport.WorldToScreen() function to calculate screen coords. So it would perhaps possible to create such a function per Layer if one exists, it is used to calculate the screen coords. If not, the Viewport.WorldToScreen() function is used. And for overlays, the function returns the coords without changing them.

**Comment by pauldendulk** [comment]
- About SVG. Yes you have to add some specific rendering for SVG, but you have to do this only once, not for every overlay.
- About 'a few elementary geometries'. That is how it always starts :) but eventually you could end up with something like the SVG spec (700 pages), or the Skia api to draw just a few vectors.
- About WorldToScreen. Yes it would be nice it this could be solved by simply not calling WorldToScreen. The features will have to be generated in screen coordinates. So the overlay generator would need to take the screensize into account (if an overlay needs to be in the bottom-right corner for example). 

I see still quite a few options, some new once coming up. This is a reason keep thinking a bit longer about it. This discussion is valuable in its own right though.

**Comment by charlenni** [comment]
Regarding handling Overlays as Layers: there is one difference between Overlays and Layers, that must be handled. Overlays could change, if the Viewport changes. That was one function, which I had to insert into Map object. If you don't do this, Overlays aren't updated when e.g. Center changes.

SVG would be nice for markers too. And no, animation in SVG is nice, but you don't need it. So perhaps some of the 700 pages could be dropped ;). Isn't normal behavior implemented in the SkiaSharp project?

Doesn't have Viewport the dimensions of the screen? Perhaps a property for dpis could be usefull.

My intention was to have a Map control for Xamarin.Forms. I could create overlays there, but think, that it is much more usefull to have it in Mapsui Map control, because than more people could use it. Put things, that everyone could use, in the right control.

**Comment by pauldendulk** [comment]
> Regarding handling Overlays as Layers: there is one difference between Overlays and Layers, that must be handled. Overlays could change, if the Viewport changes. That was one function, which I had to insert into Map object. If you don't do this, Overlays aren't updated when e.g. Center changes.

I don't understand, this is also the case for regular layers.

> SVG would be nice for markers too. And no, animation in SVG is nice, but you don't need it. So perhaps some of the 700 pages could be dropped ;). Isn't normal behavior implemented in the SkiaSharp project?

True, the animations complicate is a lot. And there are also some kind of events. These are things that should have been in a separate spec.

> Doesn't have Viewport the dimensions of the screen? Perhaps a property for dpis could be usefull.

When the renderer is initialized in the MapControl the platform's dpi can be used to initialize the skia canvas with a scale. For layers this is enough. For overlays perhaps not. For overlays you could use:
- Relative position between 0 and 1. In this case I think you need to know the dpi
- Absolute position in screen coordinates. In this case you need to know the screen width and height. This is available in the Viewport. I think dpi will not be necessary. I think this option better.

> My intention was to have a Map control for Xamarin.Forms. I could create overlays there, but think, that it is much more usefull to have it in Mapsui Map control, because than more people could use it. Put things, that everyone could use, in the right control.

Yes, I prefer that too but we have to way the pros and cons.

**Comment by pauldendulk** [comment]
This has now been implemented as Widgets.
