### ISSUE TITLE
Displaying markers and drawing polyons as per mouse click

### ISSUE THREAD

**Issue by ThandiweM** [pauldendulk/Mapsui#148]
hello,

I am trying to display a marker at the mouse click Position aswel as draw Polygons by clicking the mouse.I have looked into the Info layer example but am unable to exand on it to  accomodate my needs since I have hit a brick wall on how to acquire the Point at the mouse click position and enter it into eg CreatePolygonLayer() .

Any assistance will be greatly appreciated.

**Comment by pauldendulk** [comment]
Intercepts the screen position with a regular click event. Then use MapControl.Map.Viewport.ScreenToWorld(screenPosition) to calculate the coordinates of the Map. Add a new feature at that position.

**Comment by pauldendulk** [comment]
Please let me know if you have further questions.

**Comment by ThandiweM** [comment]
Thank you very much for your Response.

So I Need to place the click Event in the MapControl class,am I that corrrect?

**Comment by pauldendulk** [comment]
Yes, you need to listen to that native event of the MapControl. Could be the touch event, depending on the platform.

We should add some such event on the Map so that you can handle this on a platform independent way. 

What kind of behavior would you expect? What are you used to in other platforms?

**Comment by ThandiweM** [comment]
Thank you very much,it worked liked a charm with the Placement of the  markers. I have been able to place markers and move/drag them in other platforms so this is what I am trying to realise using Mapsui. As well as drawing Polygons as per mouse click ,moving then or changing the Position of the polygon's vertices thereby altering the polygon's shape. 

My current challenge is with the moving/dragging of the markers.I am kindly asking for any Information which could Point me towards the right direction on how to achieve this.
My deepest apologies for the delayed Response.

**Comment by pauldendulk** [comment]
There is nothing out of the box specifically for dragging. One options is to do it in steps. Use feature info to get the feature info of a marker. Store the id in your client and put you client application in some 'moving' mode that you manage in your own app. On the second mouse click change the X/Y of the selected feature to the new position.

If you want to see the symbol actually be dragged it will be more complicated. The Map needs to be locked to prevent panning (not sure if locking is now properly implemented but this will not be hard to add). To draw the symbol that is moved you could either 1) draw a symbol in your client, or 2) update the symbol position on every move. Perhaps Mapsui has limitations for the second option. This is something that needs to be supported but perhaps after 1.0.

**Comment by pauldendulk** [comment]
I created an issue to add a sample for this #155

**Comment by pauldendulk** [comment]
UPDATE: The click event now always returns the world coordinates. So a new point could be added with just that coordinate without the need to transform.
