### ISSUE TITLE
Is there api develop document about this project ?

### ISSUE THREAD

**Issue by wangjianpeng** [pauldendulk/Mapsui#149]
I want to study  and develop this project, but i when i  study the simple demo, i can't find any API document ?  what should i do  to study  this project ?

**Comment by pauldendulk** [comment]
We are starting to add some info in the wiki but it is still limited:
https://github.com/pauldendulk/Mapsui/wiki

The samples should be an important place to get you started:
https://github.com/pauldendulk/Mapsui/tree/master/Samples/Mapsui.Samples.Common/Maps
You can run the various sample maps in there from the WPF application. Look at the code samples themselves to improve your understanding. 

We are gradually improving our documentation based on user feedback. This is now done mostly by adding/improving samples. Do you have any specific questions I can help you with?
