### ISSUE TITLE
what the blur tile happened ?

### ISSUE THREAD

**Issue by wangjianpeng** [pauldendulk/Mapsui#151]
When i drag to move the mapcontrol, the viewport will change, and i will reget the tiles on the current viewport, and to download the need tiles image to cache it. then render the downloaded image . for other tile that waiting to download corresponded image, the tile will blur, could you tell me the logic and where the code is to make the tile blur ?
and i am also confused with the feature class and style class  ? when render one layer, i need to foreach layerstyle , and   foreach features  under the layerstyle?  why at last reforeach the features , and foreach the style under feature styles following the up code ? how to understand the feature and style on the map, is there any extend class like feature or style in the future?
```c#
                var features = layer.GetFeaturesInView(viewport.Extent, viewport.RenderResolution).ToList();
                var layerStyles = BaseLayer.GetLayerStyles(layer);
                var brushCache = new BrushCache();

                foreach (var layerStyle in layerStyles)
                {
                    var style = layerStyle; // This is the default that could be overridden by an IThemeStyle
                    if (style!=null)
                    {
                        Logger.Log(LogLevel.Information, "Under layer style "+style.ToString());
                    }

                    foreach (var feature in features)
                    {
                        if (layerStyle is IThemeStyle) style = (layerStyle as IThemeStyle).GetStyle(feature);
                        if ((style == null) || (style.Enabled == false) || (style.MinVisible > viewport.Resolution) ||
                            (style.MaxVisible < viewport.Resolution)) continue;
                        Logger.Log(LogLevel.Information, $"Enter the features loop {feature.ToString()}");
                        RenderFeature(viewport, canvas, feature, style, rasterizing, brushCache);
                    }
                }

                foreach (var feature in features)
                {
                    Logger.Log(LogLevel.Information, "Under the feature  style loop after the previous  layer feature loop.");
                    var styles = feature.Styles ?? Enumerable.Empty<IStyle>();
                    foreach (var style in styles)
                        if ((feature.Styles != null) && style.Enabled)
                        {
                            Logger.Log(LogLevel.Information, $"during the style loop {style.ToString()} under feature {feature.ToString()}");
                            RenderFeature(viewport, canvas, feature, style, rasterizing, brushCache);
                            
                        }
                            
                }
```
could you tell me what  code logic to do in details ?

**Comment by pauldendulk** [comment]
Hello, I will try to help you but I do not fully understand your question. Perhaps you could first explain what you are trying to achieve. It will also help if you post your different question as separate issues. 

Is the code that you show just what is in the WPF MapRenderer or are you trying to build a renderer yourself? This should not be necessary. 

About the Styles. There can be multiple styles on a layer (those apply to alle features in a layer) and multiple styles per feature (those apply only to the feature). The first loop renders the layer styles, de second loop renders the feature styles.

About the blur. This is not explicitly in the code. When a tile is draw much larger than it's actual size it will start to blur. This is how the WPF renderer deals with this. This can happen if you only have top level tiles available and zoom much deeper. After 1.0 I will start on rendering vector tiles, which do not have this problem.

**Comment by wangjianpeng** [comment]
thank you , you have answered all my questions.could you tell me where the render code process draw larger actual size , i am still new to wpf.

**Comment by charlenni** [comment]
Ah, vector tiles. This would be a great feature :)

I made a port of Mapsforge to C# in another project 
(https://github.com/charlenni/MapsforgeSharp). It is a tile generator, 
which could make any tile from a Mapsforge file with a Skia renderer. I 
stopped, because I didn't have any good idea to draw the text for the 
map and handling the ready made tiles was to difficult for me. But than 
I found Mapsui, which does the handling :). Perhaps it helps.

Best regards,
Dirk

Am 22.03.2017 um 07:52 schrieb Paul den Dulk:

**Comment by pauldendulk** [comment]
@wangjianpeng GeometryRenderer.RenderRaster creates an element that contains the image. That element is placed in the visual tree of WPF. There is no explicit call to render the image like in skia. GeometryRenderer.PositionRaster moves the element around af it was initially created. What are you trying to do?

**Comment by pauldendulk** [comment]
@charlenni I have been using [mapbox-vector-tiles-cs](https://github.com/bertt/mapbox-vector-tile-cs) to decode vector tiles. I did a simple rendering test in [VectorTileToBitmapRenderer](https://github.com/OsmSharp/VectorTileToBitmapRenderer). Perhaps your work on MapsforgeSharp add to that. Do you think there are parts of MapsforgeSharp that could be useful to us?

I added an issue to implement vector tiles:
https://github.com/pauldendulk/Mapsui/issues/152

**Comment by wangjianpeng** [comment]
I just want to simulate this effect  in the Unity3D, i think  i can change the scale of the mesh to make the  texture blur.

**Comment by pauldendulk** [comment]
I think the skia renderer is a better starting point
