### ISSUE TITLE
MBTiles

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#158]
Hi 

I know there have been other issue's about this. 
Could use a little explanation about this.

I have my own service that download MBTile from a WMS server, it give information about row, col, zoom level and ofc. tile_data.
I have used the example:

```
            MbTilesTileSource.SetPlatform(plat);
            var tileSource = new MbTilesTileSource(new SQLiteConnectionString(path, false));
            return new TileLayer(tileSource) { Name = "MbTiles" };
```

But how do I set the data into the right table, so it's useable?

Br. John Sørensen

**Comment by pauldendulk** [comment]
This could actually work without further modification. MbTiles assumes the OSM tile schema is used. Perhaps you cached only a small subset? Or used the wrong YAxis?

Could you share the file?

**Comment by johnhs91** [comment]
Don't think you understand.
The data I get from my own service, don't get saved anywhere yet, just get own made object with the information I wrote. 
How do i set this in the right sql lite table?

```
        public static ILayer CreateLayer()
        {
            var path = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "name");
#if __IOS__
            var plat = new SQLite.Net.Platform.XamarinIOS.SQLitePlatformIOS();
#endif
#if __ANDROID__
            var plat = new SQLite.Net.Platform.XamarinAndroid.SQLitePlatformAndroid();
#endif
            MbTilesTileSource.SetPlatform(plat);

            var tileSource = new MbTilesTileSource(new SQLiteConnectionString(path, false), new TileSchema());
            return new TileLayer(tileSource) { Name = "MbTiles" };
        }
```

And then I got a function that get all information from server in a list of what I wrote in the thread.

`var tileData = mapService.GetMBTiles(lat, true, lon, true, radius, true, map, wms, customerId, layers, maxzoomlevel, true);`

This is only code I got, only thing I need is to save the tileData to the right place, so I can use it for offline use.

**Comment by pauldendulk** [comment]
I don't understand what you are trying to do. 
- Are you trying to generate an  MBTiles file yourself? If so, I would expect this to be a server side thing and not a client side thing. In this case you would want to read up on the MBTiles format. Here for example: https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md
- It seems though that the service is somehow used in the client. Are you sure you need MBTiles here?
- How do you generate the tiles? Do you render them yourself? From what data?

**Comment by johnhs91** [comment]
Well we got our own map service, that generate tiles based on a map and layers.
Then we make so customers are able to download map, if they later need to use the app on offline mode.
So I need to setup sql lite with table's I can save the data into, so Mapsui can read from database instead of from our service, for offline mode.

**Comment by charlenni** [comment]
You get bitmap tiles, not vector tiles, from your service and want to store them into a MBTile file. Is this correct?

**Comment by johnhs91** [comment]
Well isn't MBTile file a normal sql lite database?
And yes it's correct.

**Comment by charlenni** [comment]
Yes, but you could save two types of tiles in the database: bitmap tiles and vector tiles. They are very different :). Bitmap tiles must only be displayed on screen, vector tiles had to be rendered before you could use them.

You should look at https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md for the file format of MBTiles.

**Comment by johnhs91** [comment]
Aha, well only though Mapsui supported bitmap, that's why I didn't specify this.

**Comment by johnhs91** [comment]
Thank you very much, kinda work now. 
It show tiles, just the wrong one, but guess that's my service that send something wrong.

**Comment by pauldendulk** [comment]
You can pass a schema to the constructor of MbTilesTileSource to use a schema that is compatible with your service.

A common error is use of YAxis.OSM instead of YAxis.TMS or the other way around. 
``` C#
new GlobalSphericalMercator(YAxis.OSM)
```
