### ISSUE TITLE
Required version of BruTile not updated to 0.20.0 (for Mapsui 0.13.0)

### ISSUE THREAD

**Issue by SimplexAuctor** [pauldendulk/Mapsui#160]
The nuget package still requires BruTile 0.19.0, I think the Mapsui.nuspec needs updated for release 0.13.0.

**Comment by charlenni** [comment]
I encountered this today too. But for some things you need 0.20 too, so you have to install it too.

**Comment by pauldendulk** [comment]
Oops, you are right. Thanks for that. I will update the nuspec to BruTile 0.20.

This might also be related to issue #156

**Comment by pauldendulk** [comment]
Fixed with push of Mapsui 0.14.0:
https://www.nuget.org/packages/Mapsui/0.14.0
