### ISSUE TITLE
Add FillStyle to Skia Polygon Rendering

### ISSUE THREAD

**Issue by d001225** [pauldendulk/Mapsui#163]
Seeing the code, the only available renderer for Android is the FillStyle.Solid (PolygonRenderer.Draw)

Since the class is internal, and has no public interface, it's not changeable.

Is it possible to draw a polygon with another filled pattern?

**Comment by pauldendulk** [comment]
That is correct. It is not implemented in the Skia renderer that is used for Android. I mentioned this here: https://github.com/pauldendulk/Mapsui/wiki/Renderers.

It is implemented for WPF by @tebben. He used it for Esri services.

For what scenario do you use it?

**Comment by d001225** [comment]
I'm using it to develop an Android App for the http://reatlas.ismai.pt/atlas.
I use patterns to allow for diferentiation among families, genera and species.
Looks like no map control allows it, though, as I tried with both Mapsui and google maps api.

**Comment by pauldendulk** [comment]
Well perhaps it is actually easier to implement is in skia. I should add a graphical unit test for it. The WPF sample app can then be used to show it in the XAML renderer, which can be the example for the skia renderer.

**Comment by pauldendulk** [comment]
![image](https://cloud.githubusercontent.com/assets/963462/24674582/3a609aba-197c-11e7-95af-566490d8631e.png)

**Comment by pauldendulk** [comment]
@tebben added a unit test for this feature. In the Mapsui.Samples.Wpf app you can see it if you select 'Test Samples' and select 6. If you select 'Skia Renderer' you will see it is still missing there.

**Comment by pauldendulk** [comment]
This is now implemented in 1.3.2.

Oddly this does not work in the code I committed today, but it will work in the next release.

**Comment by pauldendulk** [comment]
And you have to thank @charlenni :)
