### ISSUE TITLE
Draw circle on map

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#165]
Hi

We have offline use, where person can choose radius and zoom level to download down.
When I write in a radius, I want a circle drawn on the map, so the user is able to see how much he currently is trying downloading.
What is the best and most efficient way to do this?

Br. John Sørensen

**Comment by pauldendulk** [comment]
Please take a look at this issue:
https://github.com/pauldendulk/Mapsui/issues/124
There is some code by @YordanYanakiev that can be helpful.

**Comment by johnhs91** [comment]
Thank you very much, helped alot.
