### ISSUE TITLE
Geometry IEquatable implementation

### ISSUE THREAD

**Issue by JakubBorek** [pauldendulk/Mapsui#168]
Using the default equality comparer on Point and possibly other Geometry implementations results in a fatal StackOverflowException.

The EqualityComparer<Point>.Default.Equals  calls Geometry.Equals(object), which in turn calls Geometry.Equals(Geometry), which again calls Geometry.Equals(object) and so on. The result is an endless recursive calls loop.

**Comment by pauldendulk** [comment]
I going to close this as fixed. @JakubBorek if you get around to test this on your project let me know.
