### ISSUE TITLE
Way to load bitmap markers into memory?

### ISSUE THREAD

**Issue by reubengann** [pauldendulk/Mapsui#169]
Hi, I have a question about implementation.

I have a number of marker bitmaps as png files on disk. I don't necessarily want to embed them in my project since users may want to change them. I noticed that in the examples the image files are loaded via a file stream, so I'm just opening the filestreams as needed and storing the ids in a Dictionary
```
if (!idcache.ContainsKey(path))
{
    FileStream fs = new FileStream(path, FileMode.Open);
    int id = BitmapRegistry.Instance.Register(fs);
    idcache[path] = id;
}
```
and then I just reference that id from the Dictionary if the marker is ever used again.

This code works just fine, but all of the png files remain open and locked until the application is closed. Is this the way it is supposed to work? If this is by design, then I will happily continue doing it that way. I guess I was thinking of doing it as in Sharpmap where you specify the image as an Image class (using, for instance Image.FromFile()), but I did not see an obvious way to do that in Mapsui (sorry if I have missed it). I tried the `using` statement around the Register() function, but no markers show up when I do that.

Thank you

**Comment by pauldendulk** [comment]
Mapsui has to work cross platform. The file system differs between platforms. So there is no direct way to implement this. It could be done using packages like pclstorage but this is not something I have on the roadmap or on the backlog.

So the interface now is a BitmapRegistry that takes in image in the form of a Stream. The idea is that tha stream stays in memory as long as it is not removed. 

To avoid the file lock you should load the image with a FileStream and then copy it to a MemoryStream. So your code would look something like this:
``` c#
            if (!idcache.ContainsKey(path))
            {
                using(FileStream fs = new FileStream(path, FileMode.Open))
                {
                    var memoryStream = new MemoryStream();
                    fs.CopyTo(memoryStream);
                    int id = BitmapRegistry.Instance.Register(memoryStream);
                    idcache[path] = id;
                }
            }
```

**Comment by reubengann** [comment]
Wonderful. Thank you
