### ISSUE TITLE
Getting a thumbnail from a map with layers

### ISSUE THREAD

**Issue by NewToMaps** [pauldendulk/Mapsui#172]
I'm playing with the WmsSample and OsmSample (and pretty much all other samples) in combination with the RenderToBitmapStream (MapRendererTests) functionality (of both the Xaml and Skia renderers), I only seem to be getting a (black) blank image. It does not seem to render my layers somehow.
The farthest I have gotten is a (white) blank image with a black frame around it.

Could anyone provide some sample code as to how you'd get a simple thumbnail from a map, with certain layers for a specific location? (Like the MapRendererTests.RenderTiles (Not using the MapControl), while using something like OpenStreetMaps or a WMS provider)

Just cant seem to get this working this way, the Mapsui.Samples.Wpf however does work using the same samples...

(Sorry for making an issue for this, didn't know where else to ask this...)

**Comment by pauldendulk** [comment]
All tests in MapRendererTests produce an image of a map. There is an important difference between samples and tests:
- Sample use the Layer and TileLayer which have an asynchronous mechanism for fetching data.
- Tests us a MemoryLayer which holds the features directly after initializing and the Layer.GetFeaturesInView return those features directly.

Perhaps your problem is dat you are rasterizing before the async layers have their data loaded.

Options:
- Try to load your data into Memory before rasterizing somehow.
- Wait until the data has been loaded. The ILayer has a Busy field. You could wait for it to become false. However, I think it is only implemented for fully for TileLayer.

**Comment by pauldendulk** [comment]
About loading the data. 

For vector layers that might be simple. Create a MemoryLayer with any IProvider you happen to use. The MemoryLayer will fetch the data sync.

For tile layers you might need to create your own MemoryTileLayer which does very little except return the tiles it fetches directly from the tile source. So where TileLayer.GetFeaturesInView fetches its data from cache the MemoryTileLayer fetches it direct from the source.

**Comment by jelknab** [comment]
Hello!

I'm trying to do the same thing, however the tile layer does not seem to show.
I want to draw a route over a tilelayer, the route shows up fine, but the rest is covered by the background color set in the RenderToBitmapStream function.

When debugging everything seems to work fine, the layer's GetFeaturesInView is called before rendering and returns features. 


![screenshot](https://user-images.githubusercontent.com/1346248/94674516-95aa5a80-0318-11eb-9065-4880c349a5d0.png)

The green should be OSM tiles.

This is what i've tried:
```
            const int outputWidth = 400;
            const int outputHeight = 600;
            
            var renderArea = new BoundingBox(
                SphericalMercator.FromLonLat(4.5562, 52.2209),
                SphericalMercator.FromLonLat(4.5672, 52.2076)
            );

            var map = new Mapsui.Map();

            map.Layers.Add(new TileMemoryLayer(KnownTileSources.Create(source: KnownTileSource.OpenStreetMap)));
            map.Layers.Add(GetPathLayer(LoadRouteFromDb()));

            using (var fileStream = new FileStream(imageFilePath, FileMode.Create, FileAccess.Write))
            {
                var resolution = ZoomHelper.DetermineResolution(renderArea.Width, renderArea.Height, outputWidth, outputHeight);
                var viewport = new Viewport {Center = renderArea.Centroid, Width = outputWidth, Height = outputHeight, Resolution = resolution};
                
                new MapRenderer().RenderToBitmapStream(viewport, map.Layers, Color.White).WriteTo(fileStream);
            }
```


```
public class TileMemoryLayer : MemoryLayer
    {
        private readonly ITileSource _source;
        
        public TileMemoryLayer(ITileSource source)
        {
            _source = source;
        }
        
        public override IEnumerable<IFeature> GetFeaturesInView(BoundingBox box, double resolution)
        {
            var tiles = _source.Schema
                .GetTileInfos(box.ToExtent(), resolution)
                .Select(ToFeature)
                .ToList();

            return tiles;
        }
        
        private IFeature ToFeature(TileInfo tileInfo)
        {
            var tileData = _source.GetTile(tileInfo);
            return new Feature { Geometry = ToGeometry(tileInfo, tileData) };
        }

        private Raster ToGeometry(TileInfo tileInfo, byte[] tileData)
        {
            return tileData == null ? null : new Raster(new MemoryStream(tileData), tileInfo.Extent.ToBoundingBox());
        }
    }
```

**Comment by pauldendulk** [comment]
@jelknab Could the problem be that there is a delay in the fetching of the tiles (they are fetched async). Suggestions:
- Just wait halve a second to let the map load
- Put the background tiles in a MemoryLayer (not async).
- Wait for the ILayer.Busy boolean to go to false. I am not sure this is implemented fully correct though. Also you need to make sure it goes to Busy = true first.

**Comment by ondrasvoboda** [comment]
@jelknab (or anybody else) have you solved your issue? I have similar problem here. I have WMS layers I need to render image from. The bounding box and resolution I need to render is not always the same with the one displayed on screen = WMS layers don't have data loaded. My idea is:
- force all layers to load data for given bounding box and resolution (is there any method I could use?)
- wait until it is completed (I would use Busy boolean suggested above)

Do you have any idea how this could be done?

**Comment by jelknab** [comment]
Hello @ondrasvoboda, I ended up digging in mapsui's source code and using parts of it to make my own method for rendering tiles.

https://github.com/jelknab/FamilieWandelPad/blob/ea190823d2bfe69dc49bbdcab06d200d2b6b0133/FamilieWandelPad.RouteImager/RouteImager.cs#L149
