### ISSUE TITLE
Styles enhancement

### ISSUE THREAD

**Issue by DiabloRusso** [pauldendulk/Mapsui#173]
Hi!
Currently, styles do not allow describing appearance of features of vector tiles
I propose to modify the styles, see Mapnik xml fragment:
```
<Style name="landcover" filter-mode="first">
  <Rule>
    <MaxScaleDenominator>100000</MaxScaleDenominator>
    <Filter>([feature] = 'amenity_university') and ([way_pixels] &gt;= 64)</Filter>
    <PolygonSymbolizer gamma="0.3" fill="#f0f0d8" />
    <LineSymbolizer stroke-width="0.3" stroke="#a52a2a" />
  </Rule>
 <Rule>
    <MaxScaleDenominator>200000</MaxScaleDenominator>
    <MinScaleDenominator>100000</MinScaleDenominator>
    <Filter>([feature] = 'amenity_hospital')</Filter>
    <PolygonSymbolizer fill="#f0f0d8" />
   ...............
  </Rule>
  ...............
</Style> 
```
Style contains one or more rules, rule limits zoom levels, describe how features are filtered by tags and contains one or more symbolizers, symbolizer describe how feature are rendered. See [Mapnik symbology ](https://github.com/mapnik/mapnik/wiki/SymbologySupport) support.
With minimal changes, can add to existing styles an filter expression.
Thanx!

**Comment by pauldendulk** [comment]
It is possible to set a style on polygon, lines and point. For polygons use the VectorStyle. I added an example to the [PolygonSample](https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/PolygonSample.cs). It is the fourth sample if you run Mapsui.Samples.Wpf

**Comment by DiabloRusso** [comment]
Yes, I already understand your style concept, I will create a new style based on filter expression and add it to specific features.
Thanx for help!

**Comment by charlenni** [comment]
This is the problem I mentioned in another issue. Style files have given styles for a part of the features. Style files are hirarchical organized. So you have to search each time, which style is the right one (speed problem) or you add the right style once to a feature, so you could often use it (memory problem).

**Comment by pauldendulk** [comment]
The memory increase because of style on a feature will not be that big. The class consists of only some colors (4 ints) and a pen width. While the geometry consists of Points with many coordinates.

Perhaps the search of a dynamic style could be noticeable but there are many options to build it. You could even create your own style IThemeStyle. It has a GetStyle delegate that you could implement any way you like.

**Comment by charlenni** [comment]
But it seems, that there are more things for a style to use. See http://wiki.openstreetmap.org/wiki/MapCSS/0.2 for line attributs.

**Comment by pauldendulk** [comment]
Well if it does not fit in the current styles we will have to change it. Also, the Mapsui styles is not my original code and I would like to replace it at some point with something I could put under an MIT license.

**Comment by pauldendulk** [comment]
btw, I would be more than happy with a first version that has no support for the vector tile styles at all. If  the geometries can be read and they can be shown by adding your own style on the layer that would be great.

**Comment by charlenni** [comment]
But @pauldendulk before this is possible, it should be clear, if you want a tile engine, which produces bitmap tiles like a normal tile source, or a vector layer, which is drawn each time the map changes. 

And it should be clear, what parts of code we need and which interfaces to use. There are more than one vector format out there, so it should be possible to use them with the same API like for bitmap tile providers with BruTile. There are many styling formats out there and @DiabloRusso try's to implement one of them.

@DiabloRusso how do you handle the transformation from vector data with tags to features? Do you create a layer for each tag type?
