### ISSUE TITLE
Is there any ways to make POI or map maker effect?

### ISSUE THREAD

**Issue by wangjianpeng** [pauldendulk/Mapsui#174]
I want to create POI effect  ,should i create custom  poilayer ?

**Comment by pauldendulk** [comment]
What is a POI effect? A popup shown after a mouse click?

**Comment by wangjianpeng** [comment]
There are some icons with specify lat and lon shown on the map looks like pop  bubble after i got some  input tages search result. just like the following image.
![File:Opm126-a.png](http://i.imgur.com/jKVAeIi.png)

**Comment by pauldendulk** [comment]
For Mapsui these are two separate things.
- **Bitmap Icons**: You can use custom bitmaps for points. Take a look at SymbolsSample.cs and [this](https://github.com/pauldendulk/Mapsui/issues/169) discussion.
- **Pop-up**: There is no out of the box pop-up but it is possible to listen to the Map.Info event if you register you poi layer as a Map.InfoLayer. In the event you can show a pop-up. You need to do this for each platform. Look at InfoSample.cs.
