### ISSUE TITLE
Dynamic libraries linking ( Android 7 and up )

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#175]
I am posting this for future reference on the development, in order to avoid future issues.

https://blog.xamarin.com/preparing-for-native-library-linking-changes-in-android-n/

**Comment by pauldendulk** [comment]
It looks like we just need to update the dependencies. Perhaps the current versions are okay already.

**Comment by pauldendulk** [comment]
The current version of sqlite is later than the ones suggested in the blog post, so I consider this fixed. Thanks for the issue.
