### ISSUE TITLE
Add camera move animation example based on one or multiple markers

### ISSUE THREAD

**Issue by kthulu** [pauldendulk/Mapsui#177]
Is it possible to add a working example for a moving marker on a zoomed map that stays centered as it moves along the screen (the marker)? I am trying to make a vehicle tracking app and not exactly sure how to go about this...

**Comment by pauldendulk** [comment]
I have done something like that with earlier versions of Mapsui. I am not sure if the current version properly supports this. Adding a sample for this does not have priority right now.

How it was implemented then: There is a 'follow' mode and 'regular' mode in the client. In the 'follow' mode you constantly set the Map.Viewport.Center to the location of the vehicle you are tracking (you might need to transform from lon/lat to spherical mercator). You need to do this in some event handler that is triggered by a location change of the vehicle. If the user touches the map set the client into 'regular' mode. You go back in to 'follow' mode by an explicit user action (like pressing a 'follow' button in a popup you get when tapping a vehicle).

The follow mode looks a lot nicer if you use animated movements between vehicle positions. Look at AnimationSample.cs.

**Comment by kthulu** [comment]
I have previously found a working example of what i am after in this repo: https://github.com/charlenni/OsmSharp.Forms however i think it might me wise to switch to the more native implementation of your mapsui version as i am still at the beginning an discovered the projects have now been split into 3 different ones. I did like the PCL version in OSMSharp.Forms for its simplicity more than the new native approach as I am a newbie in Xamarin and PCL makes more sense. 

Can you let me know if the OsmSharp has been discontinued? 

I am searching into your branch for AnimationSample.cs and can't find it, did you mean:  AnimatedPointsSample.cs

**Comment by pauldendulk** [comment]
Yes, I meant AnimatedPointsSample.cs.

My OsmSharp fork is indeed outdated, I deleted it. I continued part of the work in [VectorTiletoBitmapRenderer](https://github.com/OsmSharp/VectorTileToBitmapRenderer), and part in OsmSharp/UI in the orginal OsmSharp repo. Both projects will at some point be integrated with Mapsui. OsmSharp itself will continue as UI-less library for OSM data.

**Comment by pauldendulk** [comment]
The animation itself is a nice feature. It makes it much easier to follow the movement if you look at the map. It is also complication. So, it is easiest to start with just centering on the vehicle when data arrives.
