### ISSUE TITLE
Mercator Projection

### ISSUE THREAD

**Issue by wavemaster90** [pauldendulk/Mapsui#178]
Hello,

first of all thank you so much for this great project. I am trying to convert from lat./lon. coordinates into the world coordinates using the Mercator class. While the longitude projection works perfectly, I am experiencing a slight offset in the latitude projection, when comparing points with googlemaps. 

I believe this offset comes from the projection formula. In [wikipedia](https://en.wikipedia.org/wiki/Mercator_projection#Derivation_of_the_Mercator_projection) I found the following equations:

lat = 2*atan(e^(y/R))-pi/2 and y = R*ln(tan(pi/4 +  lat/2))

Using this formula yields a precise projection between world coordinates and lon./lat. coordinates. 

You are using a slightly different, more complex formula for the transformation. Is there a reason for this?

**Comment by pauldendulk** [comment]
Thanks for your feedback. What basemap did you test this with? Could there be a difference between basemaps?

**Comment by wavemaster90** [comment]
Thank you for your quick response. I used your WPF sample application with the "OsmSample" as base map. Then I looked for a landmark and computed the lon./lat. coordinates from it. Afterwards I compared  them with the ones I got from Google for the same landmark. 

The wikipedia formula has a quite good accuracy for this combination. The formula in the Mercator class isn't bad, as well, but differs for a couple hundred meters from the Google reference.

**Comment by pauldendulk** [comment]
If I take the lat/lon coordinate of the dam in Amsterdam and transform this using SphericalMercator.FromLonLat it gets quite close, certainly not a couple hundred meters difference.

![image](https://cloud.githubusercontent.com/assets/963462/25223495/ce373b0e-25bb-11e7-8fda-5c688c33d02a.png)

Did you use an icon that needs offset? Did you use the same icon for both?

Also SphericalMercator is not identical to Mercator, maybe that explains the difference in the formula. 

Could you please provide me with the exact steps to reproduce the displacement in location so I can investigate it?

**Comment by pauldendulk** [comment]
This is the code from the sample in the picture:

```C#
using BruTile.Predefined;
using Mapsui.Geometries;
using Mapsui.Layers;
using Mapsui.Projection;
using Mapsui.Providers;
using Mapsui.Utilities;

namespace Mapsui.Samples.Common.Maps
{
    public static class OsmSample
    {
        public static Map CreateMap()
        {
            var map = new Map();
            map.Layers.Add(new TileLayer(KnownTileSources.Create(KnownTileSource.BingAerial)) { Name = "Bing Aerial" });
            map.Layers.Add(CreateNewLayer());
            return map;
        }

        private static ILayer CreateNewLayer()
        {
            var layer = new Layer();
            var point = new Point(4.893611, 52.372778);
            var sphericalPoint = SphericalMercator.FromLonLat(point.X, point.Y);
            layer.DataSource = new MemoryProvider(sphericalPoint);
            return layer;
        }
    }
}
```

**Comment by wavemaster90** [comment]
Hello Paul,

thank you so much for your investigations. You are right I used the Mercator class instead of the SphericalMercator class.

SphericalMercator does exactly what it should do with a good precisson. Your hint fully solved my problem. Sorry for the inconvenience. 

(P.s. just a question out of interest. What is the use case for the Mercator projection?)

**Comment by pauldendulk** [comment]
@wavemaster90 Any update on this?

**Comment by pauldendulk** [comment]
Mapsui is not tied to any specific map projection. The most used is SphericalMercator but you could use a basemap in any other projection. The Mercator projection was contributed by a user who worked with a Mercator map. 

Mapsui does not use any specific projection library so for other projections you have to use some external projection library. The important thing is that Mapsui can be extended in this way.
