### ISSUE TITLE
Info Event occurred on layers when resolution not in Min/MaxVisible range

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#182]
I have multiple layers in my app. Some of them are only visible at a higher zoom level, but react for the info event even when they are not displayed on the screen at the time. For example: I’m in Zoom Level 2, I click into an empty space of the map, where a layer is visible in zoom level 4 (with an icon on this position), but the info event occurs. I have made a small video about the issue. 

Video about the issue: 
https://secure.kruse-familie.eu/bug-mapsui-info-event-on-hidden-layer.avi

**Comment by pauldendulk** [comment]
Thanks for you excellent bug report. I'll take a look.
