### ISSUE TITLE
Scaling issue on iPhone 6+, 6S+ and 7+

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#183]
The map seems to have a problem to be displayed correctly on the plus model series of iOS devices. It seems to work on any iPad model and any non plus iPhone model (as far as my testing goes). The map seems to end at ~70-80% of it's desired size (see the video below for more details and a proper lock on the issue). 

Video about the issue: 
https://secure.kruse-familie.eu/bug-mapsui-scaling-issue-iOS-plus-model.avi

**Comment by pauldendulk** [comment]
Looks like a bug, i'll take a look.

**Comment by pauldendulk** [comment]
Fixed in 1.0.2
