### ISSUE TITLE
Attribution input field stays visible on iOS

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#184]
Even if the Attribution.Text and Attribution.Url is set to null or string.Empty, the input field stays visible (at least on iOS, did not test it on Android yet). This problem is also in the sample (it is just hard too see white on white but you can click in the bottom right corner and start typing).

**Comment by pauldendulk** [comment]
There are some additional problems. 
- After adding and removing layers the attribution moves to the top right.
- The attribution is not editable but still visible when empty.

**Comment by pauldendulk** [comment]
Fixed with 1.0.4
