### ISSUE TITLE
mapControl.Map.Viewport.WorldToScreen returns null

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#188]
var p = new Point( 10, 10 );
var ssx = mapControl.Map.Viewport.WorldToScreen( p );

**ssx is null**

**Comment by pauldendulk** [comment]
I Suspect there is something wrong with the initialization of the Viewport. What is Width, Height, Extent, Center, Resolution.

Although I cannot see how the returned point itself could be null.

**Comment by YordanYanakiev** [comment]
![varddd](https://cloud.githubusercontent.com/assets/6534199/25744835/8995992e-31a4-11e7-8d47-f4b4084c888f.png)

**Comment by pauldendulk** [comment]
Thanks, almost there, but could you expand the Center and Extent. And could you put the breakpoint after that line to see the result after executed?

**Comment by YordanYanakiev** [comment]
![sadsad](https://cloud.githubusercontent.com/assets/6534199/25747710/16965b54-31b1-11e7-8617-699da8e759b0.png)

**Comment by pauldendulk** [comment]
Well, eventScreenPosition can not be null in the third screenshot because the line below that would have thrown an exception but perhaps your problem is related to a problem with screen density and Info on Android. Could you check the new 1.0.7.

**Comment by YordanYanakiev** [comment]
Still the same. I see no difference than before, except the "Resolution" which is now "104"

**Comment by pauldendulk** [comment]
In your screenshot I see a tip saying eventScreenPoint (null), but this cannot be correct for the third sample. WorldToScreen never returns null. So, maybe we should focus on what is actually going wrong. What is the problem you see in your application? Does it crash? What does not work as you expect?

**Comment by YordanYanakiev** [comment]
You were right ! it's actual a bug in Visual Studio debuger probably.
since when i put it as a parameter to a function - it is actually having a result.
although the result is incorrect. - the screen coordinates is not correct.

**Comment by pauldendulk** [comment]
uh... so is there still a problem to fix?

**Comment by YordanYanakiev** [comment]
still investigating the issue the position issue.

**Comment by pauldendulk** [comment]
Perhaps it is the same as this one just reported: https://github.com/pauldendulk/Mapsui/issues/189

**Comment by pauldendulk** [comment]
Although WorldToScreen does not return null the problem behind this report is probably this bug https://github.com/pauldendulk/Mapsui/issues/189 which was fixed in 1.0.7.
