### ISSUE TITLE
How to place road and building 's name on the map ?

### ISSUE THREAD

**Issue by wangjianpeng** [pauldendulk/Mapsui#194]
I want to separately  place roads and buildings names  on the map, as we all know, these names maybe has different rotation angle and position depend on correct  roads and buildings path. when the map resolution changed. the names should also adjust them size to fit the map. 
Does this sdk support the feature , or do you have any idea to implement it ?

**Comment by charlenni** [comment]
Sorry, you could do such things only with a vector based map. Mapsui uses up to now bitmaps, which are created by a server.

**Comment by pauldendulk** [comment]
It is also possible to show vectors in Mapsui. The following types are supported (maybe time to document this):
- Points
- MultiPoints
- Lines
- MultiLines
- Polygons
- MultiPolygons
- Rasters (used for Tiles and WMS)

Labelling is however very primitive. The label is always on the center of the bounding box of the geometry.

Take a look at the shapefile sample in Mapsui.Samples.Wpf in this codebase.
