### ISSUE TITLE
Unexpected (?) circle included with Feature

### ISSUE THREAD

**Issue by reubengann** [pauldendulk/Mapsui#195]
I'm trying to display a marker with a label and bitmap. Following the LabelsSample.cs example, I use
```
var feature = new Mapsui.Providers.Feature
{
	Geometry = c.Location
};
feature.Styles.Add(new LabelStyle
{
	Text = c.Name,
	ForeColor = Color.White,
	BackColor = null,
	VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Bottom,
	Offset = new Offset(0, 14),
	Halo = new Pen(Color.Transparent),
	CollisionDetection = false
});
feature.Styles.Add(new SymbolStyle { BitmapId = IconCache[path] });
memoryProvider.Features.Add(feature);
```
This creates the bitmap and the label, but a white circle comes along for the ride. What I expect is this:
![capture2](https://cloud.githubusercontent.com/assets/20427974/26018122/0e1a8970-373b-11e7-8463-54b0674da51d.PNG)
but what I actually get is this
![capture](https://cloud.githubusercontent.com/assets/20427974/26018069/cdc6b970-373a-11e7-8432-75ac34757316.PNG)
If I don't add the styles, I get the circle all by itself. Is this expected behavior? If so, I wonder how I can achieve the result I want.

Thanks

**Comment by pauldendulk** [comment]
That is the default symbol on the layer itself (both layers and features
can have styles). You have to set it to null. I it causing confusion a lot.

Paul

Op 12 mei 2017 23:50 schreef "reubengann" <notifications@github.com>:

**Comment by reubengann** [comment]
ok, thank you. So the way to instantiate the layer in this use case is something like
`MemoryLayer _pointlayer = new MemoryLayer { Style = null };`

Something else that's odd is that I don't see the halo functionality appearing to work (on Windows). I copy the CreateColoredLabelStyle()
```
feature.Styles.Add(new LabelStyle
{
	Text = c.Name,
	BackColor = new Brush(Color.Blue),
	ForeColor = Color.White,
	Halo = new Pen(Color.Red, 4),
	VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Bottom,
	Offset = new Offset(0, 14),
	CollisionDetection = false
});
```
Is it weird that I don't see a red outline?
![capture3](https://cloud.githubusercontent.com/assets/20427974/26029332/b3af77cc-3800-11e7-8376-c8acc0daf373.PNG)

**Comment by pauldendulk** [comment]
You can set ```Outline``` instead. 

Are your expectations based on some other library? Which?

**Comment by reubengann** [comment]
Oh, no, not at all, just trying to learn from the examples. The result I was trying to get was outlined text, but that seems difficult to accomplish. My current solution is problematic since white text disappears over markers that have white in them. Thanks for the help
