### ISSUE TITLE
popup ommouse over marker

### ISSUE THREAD

**Issue by ThandiweM** [pauldendulk/Mapsui#196]
Hello,

I have managed to add marker Features to a layer as per mouse click and added it to HoverInfoLayer.I was hoping to achieve something like a popup when the mouse goes over the marker.My issues is this is only working for the  marker  I place first and not for the markers that  place afterwards...apparently no Feature is being returned.I was wondering if you could perhaps point me towards the correct direction in achieving this.

**Comment by pauldendulk** [comment]
So, what is happening exactly? If there is no feature when you click the map no feature is returned obviously. If you add the feature at that Info event you could show the feature you are about to add to the popup. I probably don't understand the problem at all. Please help me.

**Comment by ThandiweM** [comment]
Hello,

Pardon me for the delayed response.Well,my issue is after placing numerous markers the hover event only fires for the first marker placed and not for all the other markers

**Comment by pauldendulk** [comment]
Considering this answered for now. Feel free to reopen if there is further information.

**Comment by kezara** [comment]
Hello, I didn't want to open similar issue like this, but is it possible to get pop up on mouse over marker in MAUI version of Mapsui? I haven't seen this in samples, or I missed.

**Comment by pauldendulk** [comment]
There is the option to use Mapsui's Callout. See the 'Single Callout' and 'Custom Callout' samples under 'Info'. 

If you want to show a MAUI native popup you need to implement this yourself. I did this by putting an AbsoluteLayout over the Mapsui MapControl an place the popup using the screen location in the MapInfo event. Look at the InfoLayersSample to see how you can get an info event.

btw, I often end up not placing the popup over the map but above or besides the map. Especially on small devices.

**Comment by kezara** [comment]
Hello, sorry for late reply...I ended up with something like this
`private void MapControl_Hovered(object sender, HoveredEventArgs e)
        {
            var mapControl = sender as MapControl;
            
            var mapInfo = mapControl.GetMapInfo(e.ScreenPosition);
            var feature = mapInfo.Feature;

            if (feature is not null)
            {
                Model.Location.Location location = (Model.Location.Location)feature["location"];
                _calloutStyle = feature.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
                if (_calloutStyle is not null)
                {
                    _calloutStyle.Enabled = !_calloutStyle.Enabled;
                    _lastSelected = feature;
                    mapInfo?.Layer?.DataHasChanged();
                }
            }
            else
            {
                if (_calloutStyle is not null)
                {
                    _calloutStyle.Enabled = false;
                    mapInfo?.Layer?.DataHasChanged();
                }
            }

        }`

It shows popup when feature is hovered, but popup is quite unstable, I mean it blinks and even when mouse is still and do not moving, popup is shortly visible and then disappear. Do you have any idea how to fix this? Thanks.

**Comment by charlenni** [comment]
I assume, that this line is your problem:

````
_calloutStyle.Enabled = !_calloutStyle.Enabled;
````

You turn it on and off and on and off... Set it to true and save this feature. If you don't find a feature at this point, disable the last feature and forget this last feature.

**Comment by kezara** [comment]
Well, I think that I was tried with similar solution...I tried like this:

```
private void MapControl_Hovered(object sender, HoveredEventArgs e)
        {
            var mapControl = sender as MapControl;
            
            var mapInfo = mapControl.GetMapInfo(e.ScreenPosition);
            var feature = mapInfo.Feature;

            if (feature is not null)
            {
                var calloutStyle = feature.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
                if (calloutStyle is not null)
                {
                    calloutStyle.Enabled = true;
                    _lastSelected = feature;
                    mapInfo?.Layer?.DataHasChanged();
                }
            }
            else
            {
                if (_lastSelected is not null)
                {
                    var calloutStyle = _lastSelected.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
                    if (calloutStyle is not null)
                    {
                        calloutStyle.Enabled = false;
                        _lastSelected = null;
                        mapInfo?.Layer?.DataHasChanged();
                    }
                }
            }

        }
```

With this, popup is more stable, but from some reason after mouse leave feature, in some cases popup stays visible when it should not. In some cases that popup will disappear when mouse hover over the other feature or hover over map, but sometimes I will have 2 or more popups visible at the same time. Also, I noted that when features are close enough one to another, it will display popups for all that near features.

**Comment by charlenni** [comment]
Two things come in mind:
1. It could be, that you leave the control too fast. So you disable the popup in the event, that is called, if the control loose the focus. 
2. The second is, that if you hover around and you don't find a feature, MapInfo?.Layer?.DataHasChanged() perhaps isn't called, because MapInfo.Layer is null.

**Comment by kezara** [comment]
It seems that both of your suggestions are correct. In the end I've got something like this

```
private void MapControl_Hovered(object sender, HoveredEventArgs e)
        {
            var mapControl = sender as MapControl;
            
            var mapInfo = mapControl.GetMapInfo(e.ScreenPosition);
            var feature = mapInfo.Feature;

            if (feature is not null)
            {
                var calloutStyle = feature.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
                if (calloutStyle is not null)
                {
                    if (_lastSelected is not null)
                    {
                        if (_lastSelected != feature)
                        {
                            _lastSelected.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault().Enabled = false;
                            mapInfo?.Layer?.DataHasChanged();
                        }
                    }
                    calloutStyle.Enabled = true;
                    _lastSelected = feature;
                    _lastSelectedFeatureLayer = mapInfo?.Layer;
                    mapInfo?.Layer?.DataHasChanged();
                }
            }
            else
            {
                if (_lastSelected is not null)
                {
                    var calloutStyle = _lastSelected.Styles.Where(s => s is CalloutStyle).Cast<CalloutStyle>().FirstOrDefault();
                    if (calloutStyle is not null)
                    {
                        calloutStyle.Enabled = false;
                        _lastSelected = null;
                        _lastSelectedFeatureLayer.DataHasChanged();
                        _lastSelectedFeatureLayer = null;
                    }
                }
            }
        }
```
and it looks like it's working....Thanks for your feedback and help.
