### ISSUE TITLE
The Skia renderer bitmap cache never gets cleared

### ISSUE THREAD

**Issue by laarmen** [pauldendulk/Mapsui#197]
Hi!

In the following function:
https://github.com/pauldendulk/Mapsui/blob/002480f7f1ef13473b9e3a1b5cc5fe1700d8b5ba/Mapsui.Rendering.Skia-PCL/MapRenderer.cs#L86

We have numberToKeep == _tileCache.Count * 3 and numberOfTilesUsedInCurrentIteration <= _tileCache.Count, which means that no matter what, the cache is going to keep expanding.

Using Mapsui in a WPF app, browsing around, we didn't notice much difference when hardcoding numberToKeep at 100, but without it, the memory usage could easily go up to OutOfMemory-esque dimensions when browing around.

**Comment by pauldendulk** [comment]
Thank you very much. This is a serious bug. I will publish a new version today.

**Comment by pauldendulk** [comment]
Fix published in 1.0.8
