### ISSUE TITLE
Add OnDrag event

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#198]
Please add if possible map.Drag event.

**Comment by pauldendulk** [comment]
How would that work? Should it only fire when drag is started on a symbol? Should it actually move the symbol? Is it about dragging a symbol to another place or moving the map? or both?

**Comment by YordanYanakiev** [comment]
Woops. Sorry Pauk. 
I mean when the map is moved, and another event ( if possible ) when the map is zoomed.
But the moved is more important.

**Comment by pauldendulk** [comment]
Have a look at and tell me what is missing: 

```MapControl.Map.Viewport.ViewportChanged```

**Comment by pauldendulk** [comment]
Closing this for now. Feel free to reopen if there are further questions.
