### ISSUE TITLE
[Android] DllNotFoundException when adding MapControl to layout file

### ISSUE THREAD

**Issue by epicmittmitt** [pauldendulk/Mapsui#199]
I'm trying to make a simple app that displays a few markers on a map. But I am having trouble adding the packages by NuGet. This is the error I'm getting in the designer when adding the MapControl to the UI:
![image](https://i.imgur.com/iLPwog8.png)

Apparently, Skia can't find a DLL to work with. I have tried remaking the project, reinstalling the NuGet files, and installing an older version of Mapsui all to no avail.

I'm using Visual Studio 2017 Community with Xamarin 4.5.

Why is this happening? Am I missing an initialization step?

**Comment by pauldendulk** [comment]
Could this be a problem that exists only in the designer? What if you run the application? 

So far I did not give any attention to the designer at all. I will have to dig into this.

**Comment by pauldendulk** [comment]
Here is a SkiaSharp issue that might be related:

**Comment by pauldendulk** [comment]
This fix will only prevent the crash but will not show the content drawn. https://github.com/mono/SkiaSharp/issues/234#issuecomment-299737544

**Comment by epicmittmitt** [comment]
Building the app works, surprisingly. It's just the designer that's bugged. I'll try to apply the fix and see if that changes anything.

Thanks.

**Comment by pauldendulk** [comment]
I am not sure if you can fix it without changing the mapsui source because
the nuget package has an explicit reference to the old version. Perhaps you
can override that.

Paul

Op 9 jun. 2017 18:06 schreef "Sumit Basak" <notifications@github.com>:

**Comment by pauldendulk** [comment]
@epicmittmitt Mapsui is now updated to the SkiaSharp version that contains the fix. Could you check if this prevents your crash? [but](https://github.com/mono/SkiaSharp/issues/234)
> Due to limitations in the previewers with native assets, the paint events are not invoked (the views will be blank).
