### ISSUE TITLE
[Wpf] Hit Testing for LineString

### ISSUE THREAD

**Issue by luvvaluvva** [pauldendulk/Mapsui#201]
I'm trying to implement a Hit Test for LineString, with a Transform implemented (because it's not a square transform, I can't unfortunately use polygons instead for my issue).

I've tried a couple of approaches, but I'm having issues at one end or another. By default, LineStrings don't have a ".Contains" method that returns true, but trying to implement a construct that inherits from LineStrings fails at GeometryToWKB.Parse, because it can't find the geometry type (and then can't be deserialised).

How would you recommend working with this case?

**Comment by pauldendulk** [comment]
This is not implemented yet. 

I don't understand why you cannot use polygons because of the Transform. You can use LineStrings but not Polygons for this? I would think they have the same problems.

Does the hit test for point symbols work correctly for your Transform?

**Comment by luvvaluvva** [comment]
The transformation for the point symbols works as expected, the issue would come that when you're at high or low latitudes, (for extreme caees, looking close to the arctic circle) the polygon would naturally become skewed. To logically get around this, we need to transform the coordinates into a square-based coordinate system, calculate the polygon and transform the coordinates back again into WGS84.

I ended up adding in some code to handle LineString hit testing, (using .contains, i believe) which seemed to work well enough!

**Comment by pauldendulk** [comment]
This is implemented in the version after 1.3.2 (not sure it that is 1.4 or 2.0).
