### ISSUE TITLE
Sometimes it does not Render the shape

### ISSUE THREAD

**Issue by sadjadesfandiari** [pauldendulk/Mapsui#204]
Hi
In the WPFSample project in the left pane, the Shapefile (Desktop) item, sometimes the city icon is not displayed.
Unexpected error in renderer error occurs.

This error Handled in the MapRenderer class and in the RenderLayerStatic method in the Catch block.
The error that came to Block Catch is:
"The calling thread cannot access this object because a different thread owns it"

An error in the PointRenderer class and in the CreateSymbolFromBitmap method and in-line
Var width = imageBrush.ImageSource.Width
it happens.
![untitled](https://user-images.githubusercontent.com/22491652/27479925-31d5f492-582b-11e7-8acf-4d37c7fb060b.png)

**Comment by pauldendulk** [comment]
Thank you very much. This was surprisingly easy to reproduce. With Exception Settings set to 'Break When Thrown' it show right away. I am going to fix it.

What happens that the initial thread creates the brush and adds it to the cache, then a second thread tries to use it. Some solutions I am thinking of:
- Keep a single thread for all such background rendering.
- Cache the bitmap but not the WPF brush object.

**Comment by pauldendulk** [comment]
This will be fixed in 1.0.11
