### ISSUE TITLE
[UWP] - Element is already the child of another element.

### ISSUE THREAD

**Issue by spaddlewit** [pauldendulk/Mapsui#205]
When using either Sebastian Kruse's or Charlenni's UWP Xamarin Forms sample... BUT, I'm wondering if this is something fixable from the base Mapsui library and not necessarily something that's the responsibility of the Xamarin.Forms implementation:

I created a repro project, based on Charlenni's existing Mapsui.Forms.Samples PCL project, just drop it in as a replacement:
http://www.spaddlewit.com/UWPError.zip

The issue is when you Navigation.PushAsync or Navigation.PushModalAsync another form on top, and then pop back to the forms with the Mapsui control:

"System.Runtime.InteropServices.COMException: No installed components were detected.\r\n\r\nElement is already the child of another element.\r\n   at System.Runtime.InteropServices.WindowsRuntime.IVector`1.Append(T value)\r\n   at System.Runtime.InteropServices.WindowsRuntime.VectorToCollectionAdapter.Add[T](T item)\r\n   at Mapsui.UI.Uwp.MapControl.InitAnimation()\r\n   at Mapsui.UI.Uwp.MapControl.MapControlLoaded(Object sender, RoutedEventArgs e)"

Any idea what's going on here?

**Comment by spaddlewit** [comment]
Here's the fix, in Mapsui.UI.Uwp.MapControl.InitAnimation():

Check if the children collection already contains '_zoomAnimation' before adding it.

        if (!_zoomStoryBoard.Children.Contains(_zoomAnimation))
            _zoomStoryBoard.Children.Add(_zoomAnimation);

This might also not be the completely 'correct' fix... should MapControlLoaded be allowed to potentially fire multiple times? Or should the event be removed inside of the MapControlLoaded event callback?

**Comment by pauldendulk** [comment]
Hi spaddlewit, Thanks for the bug report!

What happens is that the MapControl is removed and then added again. When it is added again the 'Loaded' event is called for the second time and the zoomAnimation is added again to the Children which is not allowed.

This is probably also a problem in WPF.

**Comment by pauldendulk** [comment]
BTW, zoom animation is not used in UWP at the moment. I have to decide what to do with it: https://github.com/pauldendulk/Mapsui/issues/211
