### ISSUE TITLE
iOS Map Control "Attribution View"

### ISSUE THREAD

**Issue by JoeCooper** [pauldendulk/Mapsui#215]
The size of the rendered frame does not fit the screen. Rather, it sticks to whatever it was in interface builder, regardless of what's happening at runtime.

I can rewrite this, however, it's not clear what "attribution view" does or why it's there.

Any hints?

**Comment by pauldendulk** [comment]
hi @JoeCooper! The attibution view is where the attribution text is shown, this is a requirement for using for instance openstreemap. There can be multiple layers each with their own attribution. Here it is in wpf: 
![image](https://user-images.githubusercontent.com/963462/28379017-8823358a-6cb2-11e7-9913-c555e40c6205.png)

Contributions on this are very welcome, when working on this feature I realized I know very little about iOS ui. I was under this impression I had it working for all screen resolutions though. I will need to check on my mac what is going wrong.

**Comment by JoeCooper** [comment]
Don't worry about checking. I know what's going on and I've fixed it in a branch in my fork.

It should work on various resolutions, but it was not resizing correctly at runtime. This can be an issue because the saved in the XiB (when you're editing) might not match the particular screen.

My version has the MapControl inheriting from UIView instead of UIStackView and using NSLayoutConstraints to rig up the subviews. Thanks to your screenshot, I can finish this fix by putting the attribution view back in and once I do that I'll fold it into my main branch and send you another pull request.

**Comment by pauldendulk** [comment]
Great! thanks @JoeCooper

**Comment by JoeCooper** [comment]
Hey, have a look at my pull request when you have a chance. I will look into the Android version as well within a few weeks.
