### ISSUE TITLE
Xamarin.AndroidUI When change center of viewport it does not refresh view

### ISSUE THREAD

**Issue by marcinkorba** [pauldendulk/Mapsui#217]
Hello I have a problem with MapsUI when i changing Center of Viewport by
MapControl.Map.Viewport.Center = center;
It does not change View on phone until i try to move view by fingers on phone, than it magically shows immediately new place. I use the latest nuget version of MapsUI.
Is there any way that with current nuget version I can tell my map to refresh view so that it would center on new points in realtime (when point is being received?)

**Comment by pauldendulk** [comment]
iOS or Android? 
What if you change only the resolution?

**Comment by marcinkorba** [comment]
It's on android with version targeted at api22(android 5.1)

**Comment by pauldendulk** [comment]
Thanks for pointing this out. The samples were incorrect.

I changed the [CenterOnLocationSample](https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/CenterOnLocationSample.cs) to use Map.NavigateTo.

```
// Set the center of viewport to the coordinate. The UI will refresh automatically
map.NavigateTo(sphericalMercatorCoordinate);
// Additionally you might want to set the resolution, this could depend on your specific purpose
map.NavigateTo(map.Resolutions[9]);
```

NavigateTo always triggers a data refresh and graphics refresh. So in this sample both are called twice. This is just fine in most situations. In some situations where performance is important you could replace this by more fine grained calls, using, MapControl.Map.NavigateTo followed by MapControl.Map.ViewChanged and MapControl.RefreshGraphics.

**Comment by pauldendulk** [comment]
I am closing this but please feel free to post further questions or reopen.
