### ISSUE TITLE
Xamarin forms custom renderer not working

### ISSUE THREAD

**Issue by AlexTeixeira** [pauldendulk/Mapsui#218]
Hello guys,

I follow the instructions of #59 to create a custom renderer to use Mapsui in forms.

The problem is that a blank view is shown instead of the map.

<img width="321" alt="capture d ecran 2017-08-05 a 11 19 00" src="https://user-images.githubusercontent.com/6555080/28994513-ebb85e7a-79cf-11e7-86a3-eace7b30e10f.png">

Here my custom renderer in forms : 

```
public class MapsUIView : Xamarin.Forms.View
    {
        private Map map;
        public Map Map
        {
            get { return map; }
        }

        public MapsUIView()
        {
            map = new Map();
            this.SetBaseLayer();
        }

        public void SetBaseLayer()
        {
            map.Layers.Add(new TileLayer(KnownTileSources.Create()) { Name = "OSM" });
            map.Viewport.Resolution = 2;
        }

    }
```

And here the implementation in android : 

```
public class MapViewRenderer : ViewRenderer<MapsUIView, Mapsui.UI.Android.MapControl>
    {
        Mapsui.UI.Android.MapControl mapControl;
        MapsUIView formsMapControl;

        protected override void OnElementChanged(ElementChangedEventArgs<MapsUIView> e)
        {
            base.OnElementChanged(e);

            if (formsMapControl == null && e.NewElement != null)
            {
                // Custom Forms control
                formsMapControl = e.NewElement as MapsUIView;
            }

            if (mapControl == null)
            {
                // Native android implementation
                mapControl = new Mapsui.UI.Android.MapControl(Context, null);
                // Link to map object
                mapControl.Map = formsMapControl.Map;
                // Set native app
                SetNativeControl(mapControl);
            }
        }
    }
```

I have the same issue in IOS.
The version of Xamarin.Forms : 2.3.4.247
I am developing in Visual Studio for Mac and my macOs is up to date.

Thanks for your help

**Comment by charlenni** [comment]
If I remember correct, you should use

    KnownTileSource.Create(KnownTileSource.BingAerial)

**Comment by charlenni** [comment]
Oh, I saw, that OSMTileSource is the default.

But it has nothing to do with the renderer, because you see the attribution of the map correct. So the renderer works, but the tiles are not shown. Try another KnownTileSource. Perhaps you have problems with OSM.

**Comment by AlexTeixeira** [comment]
Hi,

Thanks for your response... I'm very new at OSM. So should I Install OSM nugget package to work with in Mapsui?

**Comment by charlenni** [comment]
No, you shouldn't. First try another KnownTileSource. There are more than one.

**Comment by AlexTeixeira** [comment]
Seems that only` KnownTileSource.StamenToner` works...
One more question : The wiki is very light, do you have any good website or tips to start working with this plugin ?
