### ISSUE TITLE
Multipolygon not working in InfoLayers

### ISSUE THREAD

**Issue by Sakker** [pauldendulk/Mapsui#219]
If I add a multipolygon to a layer and add that layer as InfoLayer, the Info event won't work.
When doing exactly the same with a polygon, it will work.
The event will trigger, but the feature will not be returned.

var multiPolygonString = @"MULTIPOLYGON (((403402.159809351 6651884.80547931,403401.512679859 6651884.09646646,403294.011549052 6651888.31504503,403309.700868129 6652006.1868857,403321.668500406 6652006.24904113,403365.478775193 6652006.3207122,403384.534153941 6652006.35150711,403391.759624428 6652006.36280938,403414.999632312 6652006.39348054,403402.159809351 6651884.80547931)),((403418.698282756 6652041.41546842,403415.459722056 6652010.75351856,403412.643957587 6652010.74443543,403399.203381782 6652010.51848429,403373.298059691 6652010.08274853,403334.114600477 6652010.3640766,403321.779307718 6652010.4507884,403310.257459794 6652010.37324315,403314.386645516 6652041.39175248,403321.636769284 6652040.94212321,403324.391293398 6652040.95568715,403418.698282756 6652041.41546842)))";
           
//this WKT is one of the polygons from the above multipolygon, this one works
var polygonString = @"POLYGON ((403402.159809351 6651884.80547931,403401.512679859 6651884.09646646,403294.011549052 6651888.31504503,403309.700868129 6652006.1868857,403321.668500406 6652006.24904113,403365.478775193 6652006.3207122,403384.534153941 6652006.35150711,403391.759624428 6652006.36280938,403414.999632312 6652006.39348054,403402.159809351 6651884.80547931))";

Below is part of the code that I use, which is similar to the example.
            var layer = new MemoryLayer
            {
                DataSource = CreateShapeDataSource(shapeStringPolygonOrMultipolygon, "sample text for info"),
                Name = "Polygon",
                Opacity = 0.5,
            };
            _map.Layers.Add(layer);
            _map.InfoLayers.Add(layer);
            

Am I doing something wrong or is there a bug?

**Comment by Sakker** [comment]
I worked around the bug, by splitting the multipolygon in multiple polygons and adding them to the same DataSource/layer.
(I didn't close it, since the bug still exists)

**Comment by pauldendulk** [comment]
Thanks for your clear report. Your samples helped to fix it quickly.
