### ISSUE TITLE
Mapsui.Providers.Shapefile missing

### ISSUE THREAD

**Issue by mathisloge** [pauldendulk/Mapsui#220]
Hey there, 
in the Desktop.Commns Samples is a using Mapsui.Providers.Shapefile. But I can´t find it anywhere. 

Am I doing something wrong?

Edit:
I´m using WPF

**Comment by pauldendulk** [comment]
The Shapefile sample came with SharpMap from which Mapsui was ported. It is part of the Mapsui.Desktop project but is not published as nuget package. I have currently no plans to do so. It should be considered not supported. The sample should be replaced with something that works on all platforms. You could use a copy of the code of the Mapsui.Desktop project to work with it in your own project.

**Comment by mathisloge** [comment]
Okay thank you. 
It works if i just copy the code in my project.
