### ISSUE TITLE
Skia MapRenderer.RenderToBitmapStream doesn't appear to work on iOS

### ISSUE THREAD

**Issue by jshield** [pauldendulk/Mapsui#221]
Hi,

I've written a TileRasterizer wrapping BruTile's ITileSource which internally uses the Map and MapRenderer classes to generate TMS compatible tiles to speed up rendering and facilitate caching to the local file system. It operates in a similar fashion to the RasterizingLayer, but uses the regular TileLayer to manage fetching. 

When I was testing it on iOS I noticed it was returning empty transparent pngs. 
After an hour or two of investigation I wrote a new RenderToBitmapStream method that is working.
```csharp
private MemoryStream RenderToBitmapStream(IViewport viewport, IEnumerable<ILayer> layers, Color background = null)
{
  using (var surface = SKSurface.Create((int)viewport.Width, (int)viewport.Height, SKImageInfo.PlatformColorType, SKAlphaType.Unpremul))
  {
    Render(surface.Canvas, viewport, layers, background);
    using (var image = surface.Snapshot())
    {
      using (var data = image.Encode())
      {
        var memoryStream = new MemoryStream();
        data.SaveTo(memoryStream);
        return memoryStream;
      }
    }
  }
}
```

Key differences being using SKSurface and SKImageInfo.PlatformColorType instead of SKColorType.Bgra8888, on my iOS device (iPhone 6S Plus) it returned Rgba8888 instead. I suspect that iOS can't handle Bgra8888, might be a Skia bug?

I have not tested this on other platforms using Skia so I can't say if it would affect UWP/Android.

Cheers,

**Comment by pauldendulk** [comment]
Apparently Bgra8888 is not supported iOS. Look [here](https://developer.xamarin.com/api/field/SkiaSharp.SKImageInfo.PlatformColorType/) and [here](https://github.com/mono/SkiaSharp/issues/291#issuecomment-302759958). This means the rasterizer never worked on iOS. It looks loke PlatformColorType is just the correct way to do it. Thanks for your contribution!
