### ISSUE TITLE
Zooming in further?

### ISSUE THREAD

**Issue by Phantamos** [pauldendulk/Mapsui#223]
I noticed there does not appear to be any way to access the max zoom in or out. Are they set based on the source tiles, or is the min/max built in somewhere?

**Comment by pauldendulk** [comment]
Yes, they are currently based on the zoom levels and not adjustable. If there are no tile layers there is no restriction. On Android and iOS is it worse, there is no restriction at all. Fixing this is quite high on my priority list.
