### ISSUE TITLE
Mbtiles sample gives exception on UWP

### ISSUE THREAD

**Issue by bertt** [pauldendulk/Mapsui#224]
Exception on loading mbtiles file in UWP sample. Line: https://github.com/pauldendulk/Mapsui/blob/612546664f667a12124512a0020dac90493e2bc0/Samples/Mapsui.Samples.Common/Maps/MbTilesSample.cs#L21

Current path in function is: .\\MbTiles\\torrejon-de-ardoz.mbtiles
But must be something else in UWP (tried folders in ApplicationData.Current but no luck so far)

**Comment by pauldendulk** [comment]
There you go!
