### ISSUE TITLE
Sample for MultiLineString

### ISSUE THREAD

**Issue by mathisloge** [pauldendulk/Mapsui#226]
Hey there, 
is there a way to add thersholds to MultiLineString to get something like this : [http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/demo/](http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/demo/)

Thanks in advance

**Comment by pauldendulk** [comment]
There is a lot possible with ThemeStyle, GradientStyle and CustomStyle.

In this case it seems what is needed styling within a single Multiline. Is that correct? This is not possible in Mapsui.

**Comment by mathisloge** [comment]
Yes you are right.
Okay. Thank you for your Quick response.

**Comment by LillyWebsites** [comment]
I would also need Styles per LineString in one MultiLineString. Would be a great feature!
