### ISSUE TITLE
Triggering a non-organic map (feature) update

### ISSUE THREAD

**Issue by BrentonWheeler** [pauldendulk/Mapsui#229]
I'm trying to change the style of a polygon which works fine, although it only actually shows the new style of the polygon after I touch/drag the map. Is there a way to force this update when ever I need to, without user interaction?

**Comment by pauldendulk** [comment]
This should be easier but should work with this:

- MapControl.Map.ViewChanged (to refresh the data in the layer)
- MapControl.RefreshGraphics

**Comment by pauldendulk** [comment]
In Mapsui 1.1 this will be possible with MapControl.Refresh().
