### ISSUE TITLE
version 1.1.1 - wrong coordinates on click

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#233]
While the click were returning correct coordinates until 1.0.11, in 1.1.1 there is something changed, and now the coordinates is not the correct ( or at least doesnt follow the previous ideology )
Is there some change which I need to reflect or it is a bug ?

**Comment by pauldendulk** [comment]
You should now use the MapControl.WorldToScreen/ScreenToWorld and not the ones on the Viewport. Those are for internal use.

**Comment by pauldendulk** [comment]
Did you find a solution? Android.Mapsui.Samples starts with the InfoSample and positions a native Android widget on touch. How do you request the coordinate?

**Comment by YordanYanakiev** [comment]
I've revert temporarily to previous version in order to complete the current task.
Most likely Your solution will work as charm as usually.
I will report probably tomorrow or next day how it is going. 
Sorry for the keeped open issue.

**Comment by pauldendulk** [comment]
I have another report of this problem, so I think it is a real issue. 

The Android sample in the Mapsui master does return the features correctly. I could be just a problem with the iOS control, or something showing only in Xamarin Forms.

**Comment by pauldendulk** [comment]
This was caused by the fact that the touch coordinates are in the scale skia coordinate instead of non-scaled device coordinate, was on Android.

**Comment by pauldendulk** [comment]
Please reopen when your problem is not solved.

**Comment by pauldendulk** [comment]
Fixed in 1.1.3 https://github.com/pauldendulk/Mapsui/releases/tag/1.1.3

**Comment by YordanYanakiev** [comment]
I am sorry that I am reopening this, but I am really confused now,
My application is in a few levels abstraction that it have a level of abstraction which produce Native PCL Android application, which on it's own is part of a PCL project node which is producing Forms PCL iOS/Android XAML application.
The issue is that the classes which I am using from the project I found in here for the XAML part does not implement direct access to ScreenToWorld and WorldToScreen routines, and everything pass trough the viewport.
But even keeping it the way it were in 1.0.10 - and it works fine in Android PCL native. The result coordinates is weird in the Forms PCL XAML application.

**Comment by pauldendulk** [comment]
Could you try to formulate a more specific question?

**Comment by YordanYanakiev** [comment]
Probably I am missing something, so - is there a demo application which is using click on marker for XAML application ?
