### ISSUE TITLE
Copyright-Text position (iPhone X)

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#237]
The position of the copyright text is a bit misplaced for iPhone X users. I attached a screenshot what the problem exactly is. It would also be great if there are a few customization options to this (maybe positioning, hide/show url or fade after x seconds). 

![simulator screen shot - iphone x - 2017-10-22 at 02 47 21](https://user-images.githubusercontent.com/25636075/31857065-c79785d4-b6d3-11e7-8097-79ddba7483bb.png)

**Comment by pauldendulk** [comment]
What is wrong with the text? Is that black line your editing or actually there on the screen?

I agree custom positioning is an obvious improvement. Perhaps the label alignment options could be used for this. 

The content of the attribution is determined by the license (described in the url in the screenshot http://www.openstreetmap.org/copyright). It could be shorter though if the url is a hyperlink.

It is actually already possible to change the content of the Attribution. It is field of the TileSource. It is not possible to hide the url and just use it as hyperlink. That is something that should be changed in the ios MapControl.

**Comment by Sebastian1989101** [comment]
The black line is part of the iPhone X and that's the problem. It is the replacement of the home button to access the app switcher within apps. So it always overlays the copyright text as long as this is at the bottom without any margin. You can test it in the iPhone X simulator already if you like.

**Comment by pauldendulk** [comment]
Fixed in 1.1.3 by moving the attribution to the top of the screen.https://github.com/pauldendulk/Mapsui/releases/tag/1.1.3
