### ISSUE TITLE
MbTiles representation modified behaviour with zero-level tiles

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#240]
I have a MbTile with zoom Levels from 0 to 18 for example.
So the zero zoom (the wholes world) have 4 tiles, before the secondary tiles (the ones which just zero level) were represented with blurry renderer but now the tiles are blank. 
Maybe is a change on Brutile and I have to change my .mbtiles file.

**Comment by pauldendulk** [comment]
Yes, the default strategy for drawing tiles has changed. I did not expect this to have a noticable effect. You can set the fetch strategy as a parameter to the TileLayer constructor. https://github.com/pauldendulk/Mapsui/blob/master/Mapsui/Layers/TileLayer.cs

**Comment by pauldendulk** [comment]
You will need to use the FetchStrategy instead of the MinimalFetchStrategy.

**Comment by pauldendulk** [comment]
A better alternative would be to use a correct schema for your tile source and use zoom limits. I still need to create samples for this.

**Comment by pauldendulk** [comment]
About the constructor argument. You can change the fetch strategy like this:
``` csharp
var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(path, true));
var mbTilesLayer = new TileLayer(mbTilesTileSource, fetchStrategy:new FetchStrategy());
```
Does this solve your problem?

**Comment by 88madri** [comment]
Yes. Sorry Paul for the late reply . I've tested with FetchStrategy and my MbTiles file works as before
Thanks.

**Comment by pauldendulk** [comment]
I great, thanks.
