### ISSUE TITLE
Initial zoom level on the map

### ISSUE THREAD

**Issue by BerBarBat** [pauldendulk/Mapsui#244]
I would like to know if I can somehow set a default zoom level at the start of the map. I currently create layers from GeoJson files and these are displayed at a much zoomed zoom level of the paintings on the layers. The idea will be to show the zoom level enough to show the layer with more size occupying the total of the screen.

Thanks

**Comment by pauldendulk** [comment]
If you initialize before the map is loaded it is enough to set the resolution. Like this:
```MyMapControl.Map.Viewport.Resolution = myResolution```
For sensible values for the resolution you could look at the Map.Resolutions list. Note, it is only populated if you have a TileLayer in your layer list.

If you need to change the resolution after the map is shown you could use one of the Map.NavigateTo methods. For instance the Map.NavigateTo(BoundingBox, ScaleMethod). The ScaleMethod could help for your purpose. You could also use the BoundingBox.Grow method to show more space around the map.

**Comment by BerBarBat** [comment]
Thanks for the quick response, I'll try to incorporate this code into my project.

My project consists of a base layer on which to paint different elements obtained through a GeoJSON.

I tried to paint the base layer from a GeoJSON but the file can be really large + - 250Mb and paint this base layer and appear with a zoom level so high it is impossible to bring the image closer to the application (Xamarin).

I have seen that the best option is to create the base layer with an MbTiles and on it to paint the element, this option is much faster and I see that we have centered the map to the size of the map that I have generated.

If you think that this scenario can be improved make a comment, but you can close the question.

**Comment by pauldendulk** [comment]
Please create a separate issue for your follow up question. A first response though. GeoJson needs to transformed from LatLon coordinates to SphericalMercator. Look at the ProjectionSample to learn how to do this. For performance improvement you could embed the GeoJson layer into a RasterizingLayer, please look at the ShapefileLayer example.

```
    map.Layers.Add(new RasterizingLayer(CreateCountryLayer(countrySource)));
```
