### ISSUE TITLE
Placement of the Attribution info

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#249]
Now the info is useable shown on iPhone X but especially in landscape mode it may overlay some content. I guess the best placement would be a free Vertical / Horizontal Alignment combined with a Margin (in this case the developer needs to implement this but at least it would fit every application as best as possible because for me it works in 2 apps for iPhone X now but breaks another app due to overlaying content).

**Comment by pauldendulk** [comment]
I considered some solutions and now think that the best option is to remove all the platform specific attribution controls and replace them by render elements. I created a new issue for this: https://github.com/pauldendulk/Mapsui/issues/254

**Comment by pauldendulk** [comment]
Fixed in https://github.com/pauldendulk/Mapsui/releases/tag/1.2.0
