### ISSUE TITLE
ViewChanged is not called on rotation

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#250]
In some cases the rotation seems not to refresh the Tiles-Layer. While my marker got repositioned correctly the tiles are not loaded for the now new visible area (I had to call ViewChanged myself or move the map a bit for a loading trigger).

**Comment by pauldendulk** [comment]
Can't reproduce it so far. 

- Is it Android, iOS, or both?
- Is it the simulator, the device or both?

**Comment by Sebastian1989101** [comment]
I have the issue on iOS (Simulator + Device; at least only tested there). Here is a small repository where this issue happens all the time: https://github.com/Sebastian1989101/OpenGeoDB-App (I had it also on native projects).

**Comment by pauldendulk** [comment]
Thanks for the sample project. This will help a lot. 


I have set ```AllowPinchRotation = true``` and try to reproduce it. Start the app. Select Aach. Rotate the map and everything seems normal.

**Comment by pauldendulk** [comment]
Sorry, I don't want to annoy you :) I am sure you have a real issue.

**Comment by Sebastian1989101** [comment]
I do not mean the rotation of the map itself. If you rotate the device (Portrait -> Landscape or Landscape -> Portrait) the map is not loading the tiles for the "new space".

**Comment by pauldendulk** [comment]
ah!

**Comment by pauldendulk** [comment]
I can reproduce it
