### ISSUE TITLE
How to display interactive map from own OSM Server 

### ISSUE THREAD

**Issue by PiotrFerenc** [pauldendulk/Mapsui#252]
How to display interactive map from own OSM Server ? 

Thx Pjo

**Comment by pauldendulk** [comment]
Take a look at the [OpenStreetMap](https://github.com/pauldendulk/Mapsui/blob/master/Mapsui/Utilities/OpenStreetMap.cs#L10) class. It has a url that points to openstreetmap.org. You can copy that class and change the url to point to your own openstreetmap server. 

If you use an alternative tile schema you should replace the ```new GlobalSphericalMercator(0, 18)``` parameter.

**Comment by PiotrFerenc** [comment]
@pauldendulk thx
![obraz](https://user-images.githubusercontent.com/30370747/32980155-dbb8ddee-cc61-11e7-9c96-0f59969e2d72.png)
