### ISSUE TITLE
Memory Leak while rotating png symbols (wpf)

### ISSUE THREAD

**Issue by PChristoph** [pauldendulk/Mapsui#253]
Hello there!

our software is using Mapsui to display a map, showing symbols (SymbolStyle -> png) on a separate layer. In the test setup we rotate the map clockwise by 1° every 20 ms, but we don't want the symbols to appear rotated, so we rotate them anticlockwise.
Unfortunatly the application becomes unresponsive after rotating the map for about 40 seconds. Some minutes later the whole gui and the map freezes completly.

I was able to reproduce the issue on the SymbolsSample on the current master of Mapsui (downloaded 17th nov, 15:40) by introducing the following code in the constructor of Mapsui.Samples.Wpf\Window1.xaml.cs:

```
          int deg = 0;
            var thread = new Thread(() =>
            {
                while (true)
                {
                    MapControl.Map.RotateTo(deg);
                    var layer = MapControl.Map.Layers.FirstOrDefault(x => x.Name == "Styles Layer") as MemoryLayer;
                    if (layer != null)
                    {
                        var styles = ((MemoryProvider)layer.DataSource).Features.SelectMany(x => x.Styles);
                        foreach (var style in styles)
                        {
                            var symbol = style as SymbolStyle;
                            if (symbol != null)
                            {
                                symbol.SymbolRotation = -deg;
                            }
                        }
                    }
                    deg = deg++%360;

                    Thread.Sleep(20);
                }
            });
            thread.Start();
```

Note that in our actual application, we don't have to search for the correct SymbolStyles to rotate on each iteration, because we keep a reference to them. I just didn't want to introduce more changes to the sample code.

Running the CPU Analyzer tool, it appears that most of the cpu power sinks into PointRenderer.CreateSymbolFromBitmap(...)

I attached 2 screenshots of the RAM Analyzer session which made me guess that there is a memory leak.

Is the way we achieve the "png symbol stays unrotated" a wrong approach?
I notice when we switch the render method of the MapControl to Skia the UI won't freeze anymore, but the png symbols won't stay unrotated - they slowly change the orientation without changing any other code. Skia and Wpf renderer behave differently there.

I hope the information helps, please don't hesitate to ask for more.

![mapsui diagsession 1](https://user-images.githubusercontent.com/18269443/33073637-cb456e46-cec3-11e7-9bc0-b758203dbbb2.png)
![mapsui diagsession 2](https://user-images.githubusercontent.com/18269443/33073638-cb5d4da4-cec3-11e7-853f-25ede192bf1e.png)

**Comment by charlenni** [comment]
Regarding the slowly rotating symbols on Skia: do you rotate always the original symbol by the whole amount or do you rotate the symbol always by 1°? Could be an rounding error.

**Comment by PChristoph** [comment]
@charlenni 
Thank you for your question. I looked at the SymbolsSample again and noticed something interesting. If I add `MapControl.RenderMode = UI.Wpf.RenderMode.Skia` right above the code I posted above (at the end of the constructor of Window1.cs) the symbols rotate anti clockwise. But if I than comment out the line `symbol.SymbolRotation = -deg;` the symbols won't rotate.
So when I use the RenderMode Skia, I don't have to manualy rotate the symbols back, because they won't get rotated automaticaly. When I use the RenderMode Wpf, I do have to manualy rotate the symbols back.

**Comment by PChristoph** [comment]
As far as I can tell from a short Memory Analyzer session: yes this solves the issue. Thank you for the quick response!

However I would like to fully understand your statement. Can you please elaborate what you consider an individual style here? Because from my understanding I don't create a new style just by setting a SymbolRotation double value. Also if I assume you are talking about "rotated png => new style", I can't see why there seem to be endless new styles, because I would think after having rotated a png by 1 degree 360 times I would end up with the same pngs again.

Also I would be very interested in the differences between Skia and Wpf - or "could we use the old Mapsui version which we already have in our project and switch to the Skia renderer, or would we suffer from other drawbacks than?".

**Comment by pauldendulk** [comment]
[Here](https://github.com/pauldendulk/Mapsui/wiki/Renderers) is some information on Skia versus WPF. Mapsui.Samples.WPF can be used to switch between both so you can get an impression. Whether you can use skia in your current version depends on how old it is. [Here](https://github.com/pauldendulk/Mapsui/releases) you can browse through all the releases.

The cache uses separate caching for each style, using the style itself as a key in the dictionary.

You are right that I would not expect an increase once a full 360 is done, so I will investigate this further.

**Comment by PChristoph** [comment]
Thank you again! That helped very much to understand the pitfall which is to be avoided. I suppose it can not be recommended to update SymbolStyle.SymbolRotation very often.

**Comment by pauldendulk** [comment]
Thanks for your code. It made it easy to test this. There was one little bug in it which surprised me as well. This line ```deg = deg++% 360``` always returns 0. It is clearly [documented](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/modulus-operator) though. I used .NET fiddle to [investigate it](https://dotnetfiddle.net/yUKsdb).

The result I get with the fixed line (```deb = ++deg % 360```) is different from what you got:
![image](https://user-images.githubusercontent.com/963462/33228413-3d2141bc-d1bb-11e7-9966-3f1dad4559c4.png)
There is still an increase after the first cycle and the second, I guess this should be explained by the renderer allocating memory. In the long run it goes to a flat line though.

At some point the symbol specific caching needs to go but at the moment I am not investing in the WPF renderer. Thanks for the sample. It is nice way to investigate memory usage.

**Comment by pauldendulk** [comment]
I did one more run with a delay of just 2 milliseconds, so many more full cycles, and here it also stays flat.

![image](https://user-images.githubusercontent.com/963462/33228809-a9273e54-d1c3-11e7-9a07-1aea4feef314.png)

**Comment by pauldendulk** [comment]
This is how it look with Skia rendering. Goes to its maximum much quicker, as expected. Total memory use is lower, as expected (104 iso 153).

![image](https://user-images.githubusercontent.com/963462/33230072-79b5d496-d1dc-11e7-9c55-0d6c74d6fbea.png)

**Comment by PChristoph** [comment]
You are welcome!
Yes I should have tested my changes I made after charlenni's question - but I guess this issue didn't take you much time to find/fix! I'm still used to write c++ instead of ++c :)

Your result from wpfrenderer - is this with the fix where you just don't let the symbols rotate or is there any new change?

**Comment by pauldendulk** [comment]
Finding the ++x bug was fun actually :)

I did it after the wpfrenderer fix but I still changed the orientation like you did (although it was not necessary). I don't expect it to make any difference.

Version 1.1.4 will have the fix.
