### ISSUE TITLE
Updating LineString coordinates

### ISSUE THREAD

**Issue by PChristoph** [pauldendulk/Mapsui#255]
Hello there!

I'm drawing LineStrings consisting of 2 Points on a MemoryLayer. The endpoint of this line has to be regularly updated. Since this happens very often and shall be performant, I hope I can get around of deleting the LineString instance from the Features List and adding the new one.

I noticed LineString.StartPoint and LineString.EndPoint are readonly, but I can grab the endpoint from LineString.Vertices or LineString.Point(n).
However when setting new X and Y values to the point instance or even assign a new point instance (with the new coordinates) won't trigger a redraw of that line. Calling Mapsui.Map.ViewChanged(true) doesn't help either.

Is it possible? Do I have to call any other Refresh/Update method?

Thank you in advance!

**Comment by pauldendulk** [comment]
Take a look at the MutatingTriangleSample. I expect that logic to work for lines as well.

**Comment by PChristoph** [comment]
I finaly could test this and it works! Thank you very much.
