### ISSUE TITLE
Very long LineStrings vanish on high zoomlevels

### ISSUE THREAD

**Issue by PChristoph** [pauldendulk/Mapsui#256]
Hello there,

I observe the following effect:
when creating a Feature with a LineString Geometry with this style:
`new VectorStyle { Fill = new Brush(Color.Black),
                        Outline = null,
                        Line = { Color = Color.Black, Width = 3 } }`
and some StartPoint and EndPoint, while the EndPoint is StartPoint.Y + customLength, with customLength = 40000000,
the LineString disappears when zooming into the map. When zooming out, it appears again. This effect won't occur when customLength is set to 440000, but will appear with 450000 again. So the magic number might lay inbetween these.

I'm very unsure what information I could provide to support the investigation. Please feel free to ask for more. The Version of Mapsui is from 21st Nov, including the 3 commits from that day.

Thank you for your time!

Best regards
Christoph

**Comment by pauldendulk** [comment]
Is this with the WPF renderer in WPF? Could you try the Skia renderer?  

```
 public MapControl()
 {
       InitializeComponent();
       MainMapControl.Map.CRS = "EPSG:28992";
       MainMapControl.RenderMode = Mapsui.UI.Wpf.RenderMode.Skia;
 }
```

**Comment by PChristoph** [comment]
yes exactly - wpf renderer. I tried the Skia renderer - the line won't disappear with that!

**Comment by pauldendulk** [comment]
This is actually not something I can fix. It is a limitation of the WPF renderer. I have not seen this problem before on WPF but I have seen it with the UWP renderer. It was the same renderer as WPF but compiled for UWP. I don't use that anymore. 

Could you work with Skia or is there some specific functionality that you need from WPF?

**Comment by PChristoph** [comment]
Thank you very much for your quick response!
At the moment I don't see reasons against Skia.

Best regards
Christoph
