### ISSUE TITLE
Rendering done twice in WPF

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#258]
Reported by @Skymirrh 

>  I noticed a strange behavior: rendering was systematically done twice. This is easy to reproduce:
> - Launch WPF sample in Debug mode.
> - to "Test samples" combo box.
> - Put a breakpoint at line 528 (RenderWpf) in MapControl.cs.
> - Click on sample "2".
> - RenderWpf is called twice.

**Comment by pauldendulk** [comment]
I checked this. There are indeed two call, but the first is triggered by setting the Map object and the second by the data being added. This is correct. While panning and zooming this does not occur.

**Comment by pauldendulk** [comment]
Thanks for pointing this out. This could have revealed a serious bug.

**Comment by Skymirrh** [comment]
Thanks for reporting back, good to know!
