### ISSUE TITLE
[1.2.0] AssemblyVersion set to 1.1.3

### ISSUE THREAD

**Issue by Skymirrh** [pauldendulk/Mapsui#259]
In latest 1.2.0, AssemblyVersion is still set to 1.1.3, whereas AssemblyFileVersion is properly set to 1.2.0. This is due to a change in your update script from [here](https://github.com/pauldendulk/Mapsui/commit/b8852e3565a0b23fbbe49b9bad89fbb6f17c7353#diff-854303b96deaa8627a03a914429dc7e9R26).

Was this intended? Are 1.1.3 and 1.2.0 assemblies interchangeable?

**Comment by pauldendulk** [comment]
Ah, you are very quick to notice! The assemblies in the 1.2.0 package are actually 1.2.0 assemblies, their version number is just wrong. The assemblies are not interchangeable. If you just use the 1.2.0 nuget package there will be no problem on your side. I messed up the script, I need to make some improvements to it.

**Comment by Skymirrh** [comment]
No problem. Should I wait a bit, if you intend to release a 1.2.1 to fix this? If not, I'll just make a note of it for the next release of our app (our build process checks for AssemblyVersion in order to do some stuff, I'll just make a temporary exception rule for Mapsui).

**Comment by pauldendulk** [comment]
ah, that is how you found it. I just release 1.2.1 which should have correct assembly versions. Could you check?

**Comment by pauldendulk** [comment]
oh I never read you post properly. It is still not fixed. Will fix it soon.

**Comment by Skymirrh** [comment]
Thanks, I'll wait for the update then ;)
