### ISSUE TITLE
Hyperlink Widget does not open the URL (iOS only)

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#260]
On iOS I got the following message when clicking on the Hyperlink Widget: 
`The file /Users/sebastian/Library/Developer/CoreSimulator/Devices/5F7D1EA7-CE4F-42D9-BB65-6546C9B4E097/data/Containers/Bundle/Application/884E8FB4-04A9-4741-B0E3-F4905BCC413B/XamFormsMvxTemplateiOS.app/http:/www.openstreetmap.org/copyright does not exist.`

On Android it seems to work with clicking on the hyperlink.

**Comment by pauldendulk** [comment]
Will be fixed soon.
