### ISSUE TITLE
How to use Viewport Limiter

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#265]
Hi. I want to Limit my Map in order to don't allow user to show blank spaces around the layers loaded.

I have tried first with the Pan.

`ViewportLimiter.LimitExtent(Map.Viewport, PanMode.KeepViewportWithinExtents, Map.Envelope, Map.Envelope);`

But this only works in the X direction (width) not on the Y direction (The user can drag and show blank spaces )

Also when I resized the control the user can pan on all the directions.

Then with the Zoom 

I've tried with 

 `ViewportLimiter.LimitResolution(Map.Viewport, ZoomMode.KeepWithinResolutionsAndAlwaysFillViewport, null, Map.Resolutions, Map.Envelope);`

But also the results are bad...

I think I don't understand quite good the Modes and also The Map.Envelope and Map.ViewPort properties.

**Comment by pauldendulk** [comment]
Do you use WPF, iOS, Android or UWP?

**Comment by 88madri** [comment]
WPF

**Comment by pauldendulk** [comment]
ViewportLimiter is not used in WPF at all, did you build your own MapControl?

I am working on an implementation now.

**Comment by pauldendulk** [comment]
I released a beta with WPF ViewportLimiter. There is a new 'Keep Within Limits' sample in Mapsui.Samples.Wpf.

https://www.nuget.org/packages/Mapsui/1.3.0-beta

**Comment by pauldendulk** [comment]
So, I admit the status of the feature was pretty unclear. 

- Currently it does not take into account rotation.
- The fact that it did not limit in the y-direction was a bug caused by an attempt to take into account rotation.
- It was initially implemented for Android.
- With this beta it is now implemented for WPF.
- It is not implemented for iOS and UWP.

**Comment by 88madri** [comment]
Let me try it at the beginning of the new year. Currently on holidays. :)

**Comment by 88madri** [comment]
Why do you remove ZoomHelper.ClipResolutionToExtremes method???

**Comment by pauldendulk** [comment]
It is replace by ViewportLimiter.LimitExtent. How did you use it? 

Do you use your own MapControl implementation?

**Comment by pauldendulk** [comment]
I re-added ZoomHelper.ClipResolutionToExtremes with obsolete warning. Thanks for your remark.

**Comment by 88madri** [comment]
I have tried before and I can say its fully working
I mean all the pretended behaviour I want in my first post.

**Comment by pauldendulk** [comment]
Lovely!
