### ISSUE TITLE
CustomTheme Example

### ISSUE THREAD

**Issue by GeoDirk** [pauldendulk/Mapsui#266]
All your examples for shapefiles use the GradientTheme.  I'm looking for a specific way to highlight something from a shapefile.  For example, I want to use the countries.shp and overall have the fill for each country as tan.  However, for a few countries, I want to be able to filter based upon the .dbf field "name" and change the fill for those countries to be something else.

Example: highlight "Canada" and "Ukraine" as green but leave the rest of the countries alone.

In Sharpmap, this was pretty easy as the FeatureDataRow was available to the CustomTheme class and you could iterate through each row as it was rendered doing the test (see https://sharpmap.codeplex.com/wikipage?title=CustomTheme).  However, in Mapsui, I'm not seeing the equivalent.

Is this possible and if so and code snippet to show how?

Thanks

**Comment by pauldendulk** [comment]
Ah indeed, no samples of CustomTheme at all even though it is the most powerful Theme. I think the [CustomTheme](https://github.com/pauldendulk/Mapsui/blob/master/Mapsui/Styles/Thematics/CustomTheme.cs) in Mapsui is mostly just a copy of the original SharpMap version so I think you can apply the SharpMap samples.

There is also the similar but simpler ThemeStyle which has a sample in the vectortiles fork:
https://github.com/pauldendulk/Mapsui/blob/vectortiles/Samples/Mapsui.Samples.Common.Desktop/VectorTileSample.cs

**Comment by GeoDirk** [comment]
Hi Paul,

Thanks for the ThemeStyle tip, I'll look into after the holidays and I get back.

With regards to CustomTheme, what would be the Mapsui equivalent to the:

private SharpMap.Styles.VectorStyle GetCountryStyle(SharpMap.Data.FeatureDataRow row)

function?  I'm not spotting a SharpMap.Data.FeatureDataRow equivalent in your library.

**Comment by pauldendulk** [comment]
oh yes, that is a difference. Mapsui does not depend on DataRow since that was not supported in some of our platforms. So instead it implemented the bracket operator (```[]```) directly on ```Feature```. The vector tile sample makes use of it in this line:
https://github.com/pauldendulk/Mapsui/blob/vectortiles/Samples/Mapsui.Samples.Common.Desktop/VectorTileSample.cs#L41

**Comment by GeoDirk** [comment]
Thanks for the tips Paul.  I ended up accomplishing what I wanted using the ThemeStyle and your example feature parsing from VectorTileSample.  

My changes to your ShapefileSample.cs to demonstrate this:

```C#
        private static ILayer CreateCountryLayer(IProvider countrySource)
        {
            return new Layer
            {
                Name = "Countries",
                DataSource = countrySource,
                Style = new ThemeStyle(f =>
                {
                    if (f.Geometry is Point)
                        return null;

                    VectorStyle style = new VectorStyle();

                    switch (f["NAME"].ToString().ToLower())
                    {
                        case "denmark":
                            style.Fill = new Brush(Color.Green);
                            style.Outline = new Pen(Color.Green);
                            break;
                        case "united states":
                            style.Fill = new Brush(Color.Violet);
                            style.Outline = new Pen(Color.Violet);
                            break;
                        case "china":
                            style.Fill = new Brush(Color.Orange);
                            style.Outline = new Pen(Color.Orange);
                            break;
                        case "japan": 
                            style.Fill = new Brush(Color.Cyan);
                            style.Outline = new Pen(Color.Cyan);
                            break;
                        default:
                            style.Fill = new Brush(Color.Gray);
                            style.Outline = new Pen(Color.Gray, 1);
                            break;
                    }
                    return style;
                })
            };
        }
```


![image](https://user-images.githubusercontent.com/1356726/34510384-85f2d302-f064-11e7-9ac3-fb236bb87a9a.png)

**Comment by pauldendulk** [comment]
Thanks for the example I will add it the Mapsui.Samples.Wpf.

**Comment by pauldendulk** [comment]
todo: Add to samples.

**Comment by GeoDirk** [comment]
@pauldendulk added in a PR for this #331.  Adds in my above example plus also puts in info and hover layer examples.

**Comment by GeoDirk** [comment]
@pauldendulk new PR (on Master branch this time) with all the new examples #347

**Comment by pauldendulk** [comment]
The PR has now been merged. Thanks GeoDirk.
