### ISSUE TITLE
iOS pinch zoom crash

### ISSUE THREAD

**Issue by tizumiZoo** [pauldendulk/Mapsui#267]
Occasionally, pinch zooming is iOS crashing.

Fine with 1.1.3 but crash from 1.2.0. 

It seems that pinch zooming is calling TouchesBegan with two touches, which returns null from GetScreenPositon() and assign null to _touchDown. Calling WidgetTouch.GetWidget() with null _touchDown causes Null exception.

It won't happen if I place my fingers one by one before pinching but more likely occurring when pinching 'simultaneously' with two fingers.

Also, maybe better to have a null check for Widget.Envelop. We use a TileLayer, and When not assigning any Text to Attribution, WidgetTouch.GetWidget() crashes. 
It's just a matter of assigning something to Attribution.Text but it was a bit of trouble debugging for the ause of crash.

**Comment by pauldendulk** [comment]
Thanks for you accurate analysis. This is a serious bug. I will fix it by simply returning on _touchDown == null, since the purpose of the _touchDown argument is to check if the user intentionally touched the attribution and not accidentally while dragging.

**Comment by pauldendulk** [comment]
I published a beta with the fix: https://www.nuget.org/packages/Mapsui/1.3.0-beta2

**Comment by tizumiZoo** [comment]
Thank you very much for your dedicated work. Wasn't expecting to get back and fixed this quick, especially around this time of the year.
