### ISSUE TITLE
Skia/WPF Differences in PenStrokeCap rendering 

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#268]
WPF:

![image](https://user-images.githubusercontent.com/963462/34452865-29eaf120-ed49-11e7-952f-6010c0421c03.png)

Skia:

![image](https://user-images.githubusercontent.com/963462/34452870-3a29667a-ed49-11e7-852e-31338a40b2c2.png)

**Comment by radderz** [comment]
Looks like wpf might have a start cap too which I didn't notice as I am not using wpf. Can have a look when back from holiday.

**Comment by radderz** [comment]
The skia one with triangle is due to that being a wpf only feature.Skia doesn't implement triangle.

**Comment by pauldendulk** [comment]
Thanks from your quick reply!

I added the StrokeStartLineCap in WPF. 

Since skia is the main renderer I will removed the triangle option. 

The samples still look different but this is because of the StrokeLineJoin. I could set this to Round in WPF to make them similar but perhaps this will break things for current users. 

I will leave StrokeLineJoin as a separate feature, so this is now done.

**Comment by pauldendulk** [comment]
This will be part of the 1.3.0
