### ISSUE TITLE
iOS is referencing System.ServiceModel

### ISSUE THREAD

**Issue by Bonnoj** [pauldendulk/Mapsui#27]
I have an issue which seems to be mostly related to Xamarin, but I wonder what's causing it. Mapsui is referencing System.ServiceModel assembly, but only on iOS. The System.ServiceModel is part of Windows Communication Foundation (WCF) which requires higher licenses on Xamarin. I've tried to backtrack the origin of the reference but couldn't find anything. It suprises me that iOS requires this while Android builds fine without the reference.

Other projects came across the same issue (mvvmcross, xlabs) and resolved it by removing the reference or changing PCL profile.

https://github.com/XLabs/Xamarin-Forms-Labs/issues/336
https://github.com/MvvmCross/MvvmCross/issues/394

When looking through the System.ServiceModel namespace (http://msdn.microsoft.com/en-us/library/system.servicemodel.aspx) I don't see anything that seems required in Mapsui. Any idea what's causing this reference?

**Comment by pauldendulk** [comment]
I am closing this issue. We have since release two Mapsui iOS apps and did not come across this problem. This could easily have been one of the (many) bugs that Xamarin fixes quickly.

**Comment by pauldendulk** [comment]
Reopened because this was reported again https://github.com/pauldendulk/Mapsui/issues/43

**Comment by pauldendulk** [comment]
I just did some further tests. If I remove RequestHelper.cs from BruTile the assemblies folder is not generated (so no assemblies folder at all). Perhaps this solves the issue for Xamarin.Indy developers. Please test this.

RequestHelper is not used from BruTile itself but it offered as a kind of utilities class. It does add some value but perhaps it could be removed and be presented as a sample.

**Comment by pauldendulk** [comment]
To Xamarin.Indy developers. You could test this, by:
- Clone BruTile
- Add a new Android app
- Add BruTile core as reference
- Confirm the remported problem exists
- Remove RequestHelper.cs from BruTile
- Confirm the reported problem does not exist

If this solves the problem we will consider removing RequestHelper.cs. If it is removed we will have to release a new BruTile package and Mapsui package.

**Comment by kochizufan** [comment]
Can I get a RequestHelper.cs-removed-BruTile.dll?
I try to make it, but if I remove RequestHelper.cs, HttpTileProvider.cs throws compile error, so I can't remove RequestHelper.cs.
I can't compile RequestHelper.cs-removed-BruTile, without error.

**Comment by pauldendulk** [comment]
Forgot about that one. You can just remove RequestHelper there and only assign the argument.

Your app will probably not run though. It is just to test Indy.

**Comment by pauldendulk** [comment]
It would also be interesting to see what happens if you compile RequestHelper.cs as part of the Android app itself.

**Comment by kochizufan** [comment]
Itried:

* I made solution named "BruTileErrorTest".
* I made projects named "BruTileErrorTest.iOS" and "BruTileErrorTest.Droid" under the solution.
* I add BruTile project to the solution, and refer it from iOS and Android project.
* I add dummy code
```
var web = new BruTile.Web.HttpTileSource (new BruTile.TileSchema (), new BruTile.Web.OsmRequest ());
``` 
to iOS project's AppDelegate#FinishedLaunching and Android project's MainActivity#OnCreate.
* Compiled them. iOS project shows "Need Business edition" error, Android not.

* In BruTile project, I change RequestHelper.cs's compile option to "None", and HttpTileProvider.cs's code to
```
    _fetchTile = fetchTile;// ?? (RequestHelper.FetchImage);
``` 
* Compiled iOS and Android projects again. Result is same before. iOS project shows same error, Android not.

If I tested bad way or what you don't wanted, please tell me.

Regards,

**Comment by pauldendulk** [comment]
Thanks for your clear report. We should conclude this does not solve the problem. The fact that iOS needs business and Android not is weird, and indicates it is a bug. We could try to randomly cut parts out of BruTile (maybe anything using system.net) and see if it fixes the problem. But maybe we should first try to ask Xamarin.

**Comment by kochizufan** [comment]
Reported.

https://bugzilla.xamarin.com/show_bug.cgi?id=30621

Thank you for helping us!

**Comment by pauldendulk** [comment]
Thanks a lot!

**Comment by kochizufan** [comment]
Xamarin reported it will fix in Xam.iOS 8.10.3
(If I didn't misunderstand written in English...)
https://bugzilla.xamarin.com/show_bug.cgi?id=30621#c9

**Comment by pauldendulk** [comment]
Ah great! Thanks for taking care of this.

**Comment by pauldendulk** [comment]
Closing. I assume this is fixed although not tested. Reopen when seen again.
