### ISSUE TITLE
TileLayer fetch timing issue

### ISSUE THREAD

**Issue by tizumiZoo** [pauldendulk/Mapsui#271]
Basically having a Nullreference exception after MapsuiControl is disposed (and crashing our app). Mapsui ver.1.1.3 on iOS.

We use Xamarin Form for our app, so implemented Custom Renderer as suggested in one of these posts with an overriden Dispose() which is like;

protected override Dispose(bool disposing)
{
    mapControl.Map?.AbortFetch();
    base.Dispose(disposing); // the base Dispose() disposes MapControl object set as NativeControl
    mapControl = null;
}

Map has a tile layer (OpenStreetMap).

After a Xamarin Form page that uses Mapsui is popped out (and calling the Dispose()) above, soon later app crashes with Nullexception.

Debugged and found out that even if AbortFetch() is called, FetchWorker has done or is doing fetching, and calls DataChanged event (which calls RefreshGraphics()) after MapControl's Dispose() is called.

Given my finding, as a work-around, I can either
 - put some delay after AbortFetch()
 - or set mapControl.Map = null

to solve the issue, but could you possibly do something in mapsui code?, maybe stop from calling DataChanged event after AbortFetch is called? Override Dispose() in MapControl and removes events? Not sure if they are feasible and safe.

Thanks

**Comment by pauldendulk** [comment]
Thanks for the detailed report.  

Do you use other platforms, like Android, and don't have this problem there?

The Map and fetcher should be able to persist after the MapControl is disposed. I would think the main problem is that the callback to MapControl.DataChanged is not cleaned up when the MapControl is disposed. That could be done in the dispose code you posted above. Perhaps that is also the proper place to do that (I have not looked into the code yet).

**Comment by pauldendulk** [comment]
This stackoverflow post is relevant here: https://stackoverflow.com/a/452294/85325

**Comment by tizumiZoo** [comment]
We didn't really notice on other platforms, but we use/test iOS more so that might be why. Also, this issue occurs when tile is still being fetched, so say for OpenStreet map as base tile map, if I open map and wait for all the tiles to be fetched, probably this issue won't or hardly occur (?), and that might be also why it was not noticed.

For now, we are doing,

protected override Dispose(bool disposing)
{
mapControl.Map?.AbortFetch();
**mapControl.Map = null; / /<- this will prevent DataChanged event to be fired**
base.Dispose(disposing); // the base Dispose() disposes MapControl object set as NativeControl
mapControl = null;
}

As judging from the source code, this is only the way to unsubscribe the event handler in MapControl class (iOS)

**Comment by pauldendulk** [comment]
Yes, Map = null is the best solution for now. I think I will add a public Unsubscribe methode as suggested in the post by Jared Parsons and also add a dispose overload in which I will call Unsubscribe.

**Comment by pauldendulk** [comment]
I will release a beta with Unsubscribe in a moment, wait.

**Comment by pauldendulk** [comment]
I published a new beta. Could you check if this fixes your issue: https://www.nuget.org/packages/Mapsui/1.3.1-beta1

**Comment by tizumiZoo** [comment]
Tested with iOS and my issue seems solved. Not getting crash any longer. I will probably do a bit more tests but I think your change fixed it. 

Thanks for your dedicated work.

**Comment by pauldendulk** [comment]
Thanks for the testing.
