### ISSUE TITLE
InfoEvents are wrong in Xamarin / Android Native

### ISSUE THREAD

**Issue by coenvdam** [pauldendulk/Mapsui#274]
InfoEvents don't give me the right information when I click on points/features in the Android Native version of Mapsui. They require me to click just above the point to get the InfoEvent for clicking on it. This is reproducable in the samples by changing the Main.axml of the Android project to this:
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:id="@+id/mainLayout"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:minWidth="25px"
    android:minHeight="25px">
  <TextView
      android:text="Map"
      android:textAppearance="?android:attr/textAppearanceLarge"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:gravity="center"
      android:id="@+id/textView1" />
  <Mapsui.UI.Android.MapControl
      android:id="@+id/mapcontrol"
      android:layout_width="fill_parent"
      android:layout_height="fill_parent" />
</LinearLayout>`

 You'll also need to change a `RelativeLayout` to `LinearLayout` in line 44 of Activity1.cs, otherwise the project won't build.
With this code, a TextView is placed above the map. This makes it so you have to click just above the points on the map. How far you have to click above the points depends on how much space above the map is taken.

**Comment by pauldendulk** [comment]
Thank you very much @coenvdam! Your description made it very easy to reproduce. This bug has been here for quite a while. Great to have it fixed.

**Comment by pauldendulk** [comment]
This prerelease should fix this issue: https://www.nuget.org/packages/Mapsui/1.3.1-beta2

**Comment by coenvdam** [comment]
Thanks for fixing this so quickly! It works like a charm.
