### ISSUE TITLE
iOS crashes shortly after panning map

### ISSUE THREAD

**Issue by spaddlewit** [pauldendulk/Mapsui#276]
v1.1.3 works fine, but as soon as I upgrade to v1.2.0, I experience this issue.

I have an MBTiles layer, a polygon layer, and a point layer with labels. I wish I could supply stack trace information, etc., but the debugger doesn't catch it -- the app just closes.

**Comment by pauldendulk** [comment]
Could your check if removing one of these layers fixes the problem?

**Comment by spaddlewit** [comment]
Just did some testing -- it's the MBTiles layer.
I have not updated any other NuGets from 1.1.3 to 1.2.0 -- they have the same dependencies, so it's got to be something in Mapsui.

**Comment by pauldendulk** [comment]
Thanks that helps. Do you use the same  mbtiles layer on other platforms?

**Comment by spaddlewit** [comment]
Yes. I use the same layer on other platforms.
Also -- I just tried using an HttpTileSource instead of an MBTilesSource and it works fine. (But obviously I need the MBTilesSource and it shouldn't be crashing...)

**Comment by pauldendulk** [comment]
If it is possible to share the mbtiles please send it to pauldendulk@gmail.com. Or use wetransfer if it is big.

**Comment by pauldendulk** [comment]
Note to self. I received the mbtiles a long time ago and should look into this.

**Comment by spaddlewit** [comment]
This appears to have fixed itself in Mapsui v1.3.2!

**Comment by pauldendulk** [comment]
Party! Exception handling was improved in 1.3.2. There might still be an exception occurring under the hood. You could try to listen to this with the logger: https://github.com/pauldendulk/Mapsui/wiki/How-to-work-with-Mapsui#logging

**Comment by spaddlewit** [comment]
Might take a week or so to get back to you, but I *will* check on this for you.

**Comment by pauldendulk** [comment]
I assume this is fixed. If anything like this happens again please submit a new issue.
