### ISSUE TITLE
Disparity between InvokeInfo on iOS/Droid/Uwp

### ISSUE THREAD

**Issue by radderz** [pauldendulk/Mapsui#277]
On MapControl.cs, iOS and Droid invoke Map.InvokeInfo on TouchEnd and MotionEventActions.Up which could have been a drag/pinch guesture rather than a tap.

It looks to me that this is a tapped like function to enable the map to show info etc on tap of a feature. However if you tap on a featre and drag the map it also invokes the info. On UWP it doesn't do this as it has a proper tapped event.

This means on a screen with features that you want to be clickable, just doing a screen drag has a chance of clicking the feature causing unintended consequences if it is being used as a selection mechanism that then centres on the clicked feature.

Either we need a Tapped hander for a feature or a InvokeInfo to only trigger if the guesture is a tap.

**Comment by pauldendulk** [comment]
Yes, I agree. There are some options to resolve this. Perhaps we can use platform specific tab gesture. Gesture can be very performance consuming though. So perhaps we should add some checks ourselves. We should perhaps also share the code for this over all MapControls.

What do you mean with?
> a Tapped hander for a feature

**Comment by radderz** [comment]
Sorry that is a typo, I was meaning if the InvokeInfo is working the way it is supposed to then we could have an additional "Event Handler" for Tapped specifically. 

I think the guesture recognizers shouldn't be too bad if we do some initial checks around if the finger has moved much and the time between down and up and if there is ever 2 touches to ignore it.

**Comment by pauldendulk** [comment]
I was thinking about some of the built-in gesture recognizer of the platforms. I know for WPF it used to take a lot of processing for little effect. If we do those checks ourselves it won't be such a problem. 

btw, The MapControls are gradually growing to become more complex. I have to start thinking about refactoring and reusing more code in common components. As a consequence things will become more aligned.

**Comment by radderz** [comment]
Yes there is a lot in them that could be sub classed as an abstract class with common parts shared. I have done this with a lot of functionality on top of the map and if you create a generic interactions conversion that then just references the base class it can help reduce the code a lot.

i.e. having the mouse down/up/drag etc all done in the sub class with all the relavent scalings pre done should reduce the duplication of code.

I can have another look at this bug and try to atleast cut out the major instances like when a drag or zoom have occured within the same touch instance when I get time. I think just making it so that if there are even 2 touches within a touch interaction (i.e. max touches) then to not call the info and reset this value touch up. The second one would be to look for a meaningful drag and perhaps the time spent touching. Tap handling should be the simplest, it gets more complicated when doing double taps.

In saying that though,
For iOS and Android I have implemented double tap zoom ontop of the Map in my code, and from a performance impact perspectivie I didn't even notice it, and that was with older and lower end phones too. I can potentially bring those tap handlers into their MapControls as a test too.

**Comment by radderz** [comment]
@pauldendulk I am about to do a pull request which rewrites the MapControl panning, zoom, rotation to be mostly the same in iOS and Android so that we end up with less bugs, I have also implemented the tap gestures and and I don't see a performance impact even on old phones (I have a bunch of different iOS and android phones I test on).

**Comment by pauldendulk** [comment]
>   think just making it so that if there are even 2 touches within a touch interaction (i.e. max touches) then to not call the info and reset this value touch up. 

Yes, that is how it should work.

**Comment by radderz** [comment]
Hi Paul the pull request ended up using the built in gesture recognisers as it didn't cause any efficiency issues when testing on older slower phones. I think the Tap gestures are relatively cheap.

**Comment by radderz** [comment]
This was fixed by #289
