### ISSUE TITLE
Improvement: Text Outline

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#280]
Would be nice for a better Text-Visibility without breaking the App Style with the available Background Boxes to have Outlines like on this graphic: 
![outlineexample](https://user-images.githubusercontent.com/25636075/34852356-819d53a6-f72e-11e7-9432-5832cbb43939.png)

**Comment by pauldendulk** [comment]
There is a Halo property on LabelStyle. It is not as nice as the sample that you show. But take a look to see what you think of it. 

It is not very easy to implement stuff like this. Perhaps SkiaSharp will get better support for this at some point.

**Comment by pauldendulk** [comment]
This is from Test 9 of the 'test samples'

![image](https://user-images.githubusercontent.com/963462/34868352-cb1b9808-f783-11e7-9e1a-e52a051bc57e.png)

**Comment by Sebastian1989101** [comment]
I guess this will make the text highlight enough which is the primary goal for this. I will give it a try (didn't notice this option before).

**Comment by pauldendulk** [comment]
This is with a font of 30 and pen width of 3:
![image](https://user-images.githubusercontent.com/963462/34868674-dcf0c0e8-f784-11e7-9c35-e1f801ea999b.png)

**Comment by Sebastian1989101** [comment]
Using the WPF Sample, it more looks like a shadow for me. Did I miss something else to change? 
![lhurptr](https://user-images.githubusercontent.com/25636075/34870976-1743f5a6-f78c-11e7-9127-17f296b54c12.png)

`new LabelStyle
{
    Text = "Black Halo",
    ForeColor = Color.White,
	Font = { Size = 30 },
    Halo = new Pen(Color.Black, 3),
    BackColor = null
}`

**Comment by pauldendulk** [comment]
In the WPF sample you can select skia rendering, top left.

WPF and Skia are different. It was not easy to get this equal. If you search the issues/PRs on halo you can find some info on this.  Actually both should be possible, shadow and text outline.

**Comment by Sebastian1989101** [comment]
Ah I see. Which one is used bei iOS / Android? The Skia renderer I guess?

**Comment by pauldendulk** [comment]
Yes, WPF is only available in the WPF MapControl.

**Comment by Sebastian1989101** [comment]
Great. It works and highlights the font perfectly. So I guess this "problem" is now solved too.

**Comment by pauldendulk** [comment]
We have to thank @spaddlewit for that :)
