### ISSUE TITLE
Attribution should be invisible when there is no content

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#281]
It now shows even if Layer.Attribution is null.

**Comment by pauldendulk** [comment]
@Sebastian1989101 Debugging now. 

In skia the attribution is not drawn when the Layer.Attribution is set to null. Not when the text is null. But is when the text is an empty string. This is by design.

In WPF the attribution is not drawn when the Layer.Attribution is set to null. It is drawn when the text is null. This should not be the case. I have changed this with this commit https://github.com/pauldendulk/Mapsui/commit/b3ce7ec21aa1db2de112cef0a723c76ee2c1f1da). It is drawn then the string is empty.

I am not sure why you still see it. Perhaps you were looking in WPF, or maybe some of the other layers have an attribution.

**Comment by pauldendulk** [comment]
I just decided not to draw the hyperlink when the string is empty. I could imagine a use case for this (for instance if users type something in a hyperlink), but rare. Since the default of the TileSource attribution text is empty string this would mean the empty hyperlink would be the default.

**Comment by Sebastian1989101** [comment]
Strange I tested it before with `null` but I guess my VS Mac did not compile properly... again... but it works indeed with `null`.

**Comment by pauldendulk** [comment]
Thanks for the update. I'll have to add a null check there too (was needed for WPF also).

**Comment by pauldendulk** [comment]
Decided not to draw the attribution also in the case of empty string: https://github.com/pauldendulk/Mapsui/commit/62e86e20350cfdb9f4b6d8215409a8a1c59ff5a6
