### ISSUE TITLE
Opacity of MemoryLayer not working on SkiaRenderer

### ISSUE THREAD

**Issue by PChristoph** [pauldendulk/Mapsui#285]
Hello pauldendulk,

sorry for not responding to your suggestions in my last issue report. I was in vacation. Happy new year btw! Your bugfix worked very well, thank you!

However I think I found another problem with the skia renderer as described in the topic. When changing the opacity of a MemoryLayer with a number of Geometries (of type 'Point') from 1 to 0, the geometries stay visible. However doing this with the standard wpf renderer works fine and the points vanish.

Best regards
Christoph

**Comment by pauldendulk** [comment]
This is one of the features that is not implemented yet in skia 
- 'Skia has no transparency on layers.' 
https://github.com/pauldendulk/Mapsui/wiki/Renderers

For WPF layer opacity is easy. You can set it on the layers' canvas. For skia it looks like it should be set on the SKPaint for each individual draw method. This is some more work. Pass the opacity to all draw methods and multiply it with the features' opacity. 

If should investigate if there are other options.

As a workaround, could you perhaps set the transparency on all individual features?

**Comment by PChristoph** [comment]
Thanks for your input! Your suggested workaround works fine!
