### ISSUE TITLE
SymbolStyle with Outline won't appear as dashed on SkiaRenderer

### ISSUE THREAD

**Issue by PChristoph** [pauldendulk/Mapsui#286]
Hello,

1. I have a feature for which I add a SymbolStyle like this:

```cs
feature.Styles.Add(
   new SymbolStyle() 
   {
      SymbolType = SymbolType.Rectangle, 
      Outline = new Pen() { Color = Color.Red, PenStyle = PenStyle.ShortDash },
      Fill = null
   }
);
```

unfortunatly the outerline won't appear as dashed in SkiaRenderer, while in WpfRenderer it does. Any help would be appreciated!

Some additional questions:
2. how can I change the size of the drawn rectangle without using Scale? Because using scale also makes the outline thicker.
3. if you don't mind explaining something which I could find out by myself by digging into the code: what is the purpose of Enabled, MinVisible and MaxVisible on the Style class?

Best regards
Christoph

**Comment by pauldendulk** [comment]
1. This is not implemented yet for skia. It was missing from my differences list. I added it now to that [list](https://github.com/pauldendulk/Mapsui/wiki/Renderers). Looks like it should use PathEffect, and you have to correct for line width. Not very easy. https://github.com/pauldendulk/Mapsui/blob/master/Mapsui.Rendering.Skia-PCL/LineStringRenderer.cs

2. There is no way to do that right now with those default symbols. With images as symbol you have more freedom.

3. MinVisible and MaxVisible form the range within a symbol is visible. They are set in map unit per pixel as the resolution. Mostly the Layers Min/MaxVisible is used in practice.

**Comment by PChristoph** [comment]
Thank you for your explanations! This helped very much. Is my assumption right, that setting `Style.Enabled = false` would just hide this style?

**Comment by pauldendulk** [comment]
Yes. This can be useful during runtime.

Paul

Op 17 jan. 2018 11:47 a.m. schreef "PChristoph" <notifications@github.com>:
