### ISSUE TITLE
Using local Mapnik based tile server

### ISSUE THREAD

**Issue by doronweiss** [pauldendulk/Mapsui#290]
hi, i have to use maps in an off-the-internet application, i am an experienced programmer but understand very little in mapping.
Mapsui looks a nice/good front end. and works great when i am online
following some hints and some (bad or good) common sense i setup a tile server, following the instructions in: 'https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/', i have my tile server running and able to render a basic map in the browser entering (for example) 'http://192.168.1.150/hot/0/0/0.png'  (192... is in my local net)
What i COULD NOT FIGURE OUT is how to tell MapsUI to connect to this server, today my code says:
**mapCtrl.Map.Layers.Add(new TileLayer(KnownTileSources.Create()));**
i am looking for something like:
**mapCtrl.Map.Layers.Add(new Uri (xxxxxxx));**

Is there such an option?
thanks
doron

**Comment by pauldendulk** [comment]
something like new TileLayer(new HttpTileSource (url))

There are some tile source samples.

Paul


Op 20 jan. 2018 8:11 p.m. schreef "doronweiss" <notifications@github.com>:

**Comment by pauldendulk** [comment]
You need to create a TileLayer and pass in a TileSource. Like this:

```
        private static HttpTileSource CreateTileSource()
        {
            return new HttpTileSource(new GlobalSphericalMercator(0, 18),
                "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                new[] { "a", "b", "c" }, name: "OpenStreetMap",
                attribution: OpenStreetMapAttribution);
        }
```
https://github.com/pauldendulk/Mapsui/blob/master/Mapsui/Utilities/OpenStreetMap.cs

**Comment by doronweiss** [comment]
i'll push my luck a little farther, i managed to connect to the local tile server (using the above replay) with the code:
>  mapCtrl.Map.Layers.Add(new TileLayer(new BruTile.Web.HttpTileSource(new 
 GlobalSphericalMercator(0,19), "http://192.168.1.150/hot/0/0/0.png")));
*(tried several scale limits)*

I get the world map, but as i try to zoom in (ctrl-scroll) i get this ridiculous 👍 

![tiledmaps](https://user-images.githubusercontent.com/25414211/35228439-684f715e-ff99-11e7-8092-574e5132c4a5.png)
 
whatever zoom i try to reach i just get this basic tile repeated

**Note 1:** i loaded data into the postGIS/postgres db using the *osm2pgsql* command, more specifically i loaded israel-palestine pbf file and results looked as if the data was loaded correctly
**Note 2:** I undestand this is probably the tile referred by 0/0/0.png but i assumed that this will be an anchor for other tiles to be fetched, i ** do not** understand the "a","c","c" pattern above :-(

thanks
doron

**Comment by charlenni** [comment]
That's easy :)

You should look again on your URL. You must use "/{z}/{x}/{y}.png" instead of "/0/0/0.png". If you don't do this, you get allways only the first tile (0/0/0) and not the correct tile (x/y/z). The URL is a normal string, which is used for a string.Format() operation to replace x, y and z.

**Comment by charlenni** [comment]
You should look into the definition of the function in BruTile (https://github.com/BruTile/BruTile/blob/master/BruTile/Web/HttpTileSource.cs). a, b and c are different names for servers, which deliver all the same information. If you provide entries, than "{s}" is replaced with an entry of this array. Normally, if you have only one server, you don't include a "{s}" and provide a null for this parameter.

So I think, your URL should be
````mapCtrl.Map.Layers.Add(new TileLayer(new BruTile.Web.HttpTileSource(new
GlobalSphericalMercator(0,19), "http://192.168.1.150/hot/{z}/{x}/{y}.png")));

**Comment by doronweiss** [comment]
**thanks all of you, works great***

![tiledmaps](https://user-images.githubusercontent.com/25414211/35230780-b71b3bbe-ff9f-11e7-9c00-8c217f1048d8.png)

it is the mapsui sample but running with a local server (no internet)
thanks again

**Comment by pauldendulk** [comment]
ah great you got this working

And thanks @charlenni :)

**Comment by charlenni** [comment]
Btw. do you need an extra server or wouldn't it be enough to use a MBTiles file with bitmap data for the region? Would be much easier than setup a whole tile server.

**Comment by doronweiss** [comment]
my answer is simple - i do not know
i am a newbie to mapping, and it is possible that the path i took is a complicated overkill.
i set up a full server with postgres/renderd and god remember what else, if there was a way to read/render the tiles directly without using a server i would be happy, i just don't know where to start from
sad, but true
thanks, doron

**Comment by anushabasavaraj92** [comment]
> You should look into the definition of the function in BruTile (https://github.com/BruTile/BruTile/blob/master/BruTile/Web/HttpTileSource.cs). a, b and c are different names for servers, which deliver all the same information. If you provide entries, than "{s}" is replaced with an entry of this array. Normally, if you have only one server, you don't include a "{s}" and provide a null for this parameter.
> 
> So I think, your URL should be
> 
> ```
> GlobalSphericalMercator(0,19), "http://192.168.1.150/hot/{z}/{x}/{y}.png")));
> ```

Is there a way to make a folder containing the map tiles in z/x/y order as a tile source in mapsui?
