### ISSUE TITLE
Rotation occurs based on the center point of the map rather than the center point of the current pinch that initiates the rotation

### ISSUE THREAD

**Issue by radderz** [pauldendulk/Mapsui#292]
This is less obvious but the rotation property rotates about the center of the Map so when pinch zooming and rotation away from the center point of the Map the location of the touches gets further from the actual map points that originally were touched.

This causes weird pinch location error as you move around in one big motion

**Comment by pauldendulk** [comment]
Thanks for reporting. That could be a tricky one.

**Comment by radderz** [comment]
I have done it in the new pull request #293 , I also added UWP rotation.
