### ISSUE TITLE
NullReferenceException (iOS)

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#296]
While I now start the testing with the 1.3.2 Beta 1 for the other bug, a new one come up for about 1-2% of my users. Here is the exception stack trace from AppCenter: 

```
VisibleFeatureIterator.IterateLayer (Mapsui.IViewport viewport, Mapsui.Layers.ILayer layer, System.Action`3[T1,T2,T3] callback)
VisibleFeatureIterator.IterateLayers (Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers, System.Action`3[T1,T2,T3] callback)
MapRenderer.Render (SkiaSharp.SKCanvas canvas, Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers)
MapRenderer.Render (SkiaSharp.SKCanvas canvas, Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers, System.Collections.Generic.IEnumerable`1[T] widgets, Mapsui.Styles.Color background)
MapRenderer.Render (System.Object target, Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers, System.Collections.Generic.IEnumerable`1[T] widgets, Mapsui.Styles.Color background)
MapControl.OnPaintSurface (System.Object sender, SkiaSharp.Views.iOS.SKPaintGLSurfaceEventArgs skPaintSurfaceEventArgs)
SKGLView.DrawInSurface (SkiaSharp.SKSurface surface, SkiaSharp.GRBackendRenderTargetDesc renderTarget)
SKGLView.DrawInRect (GLKit.GLKView view, CoreGraphics.CGRect rect)
(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by pauldendulk** [comment]
Thanks, these tests with large user bases are very valuable. 

The top MapRenderer.Render method in your stack trace has a try catch. So how does this error show up in your analysis? Do you actually listen to the logger? Or our handled exceptions also shown in the analysis? They should be distinguishable from unhandled exceptions.

Now the question is what could be null in IterateLayer and why. Does your tool provide any more information about that? Do you set something explicitly to null?

**Comment by Sebastian1989101** [comment]
This are always exceptions where the whole app crashes. So it must be something unhandled. 

The bad thing is, that the app is obfuscated so that I have no more detailed stack trace. The implementation is exactly like the description here, so there should be no null assignment: https://development-blog.eu/an-own-map-with-mapsui-in-xamarin-forms-entwurf/ 

I'm currently trying to reproduce this error somehow on my devices but so far without any luck.

**Comment by pauldendulk** [comment]
It can not be unhandled with the try-catch around the LayerIterator. 
https://github.com/pauldendulk/Mapsui/blob/master/Mapsui.Rendering.Skia-PCL/MapRenderer.cs#L76

The options I see:
- I made a mistake in releasing the beta. Unfortunately I don't write tags in my beta releases so I can not check. Have to add those.
- The update to the new version of Mapsui was not done for all projects.
- This is a report from a user that has not updated to the latest version.

I will release a new version. Probably tomorrow.

**Comment by Sebastian1989101** [comment]
Thats strange because this exception is from the "Crashes" section of Visual Studio AppCenter which means the OS was forced to terminate this app because of this Exception (which normally only happens on unhandled exceptions). 

I also just double checked which version(s) of Mapsui are referenced in the affected version and it is the latest stable release 1.3.1 in all projects. This exception also happens on 1.3.2-beta1 but most of the reports are from 1.3.1 yet. Sadly I have no logging with older releases to compare. 

So either the AppCenter library has sorted this error to the false category or there must be a way for a unhandled exception.

**Comment by pauldendulk** [comment]
@Sebastian1989101 A new beta: https://www.nuget.org/packages/Mapsui/1.3.2-beta2

**Comment by Sebastian1989101** [comment]
Will test it with the next beta releases of my apps which are planed for tomorrow.

**Comment by pauldendulk** [comment]
What could help if you listen to the logger. Take a look at the mapsui.samples.wpf to see how to do that. You can probably send the output to the Xamarin monitoring framework. This used to be possible in Xamarin insights.

**Comment by pauldendulk** [comment]
The Android sdk might make a difference. 

Deleting bin and obj folders might also be worth a try with such a weird problem.

**Comment by pauldendulk** [comment]
@Sebastian1989101 Has this issue been seen in beta3 or beta4? I expect that this was fixed.

**Comment by Sebastian1989101** [comment]
I can't see any in the log currently. So I'll guess it is fixed but not 100% sure yet. The iOS Version with Mapsui 1.3.2-beta3 is currently only available for about 50 testers of my App while beta2 is currently used by more than 1000.

**Comment by pauldendulk** [comment]
This was a long time ago. I assume this is fixed.
