### ISSUE TITLE
Mapsui standart controls.

### ISSUE THREAD

**Issue by antonad** [pauldendulk/Mapsui#298]
Hello. I have just started working with this component. Now I am confused because I don't see any examples of using standart map controls such as zoomcontols, maprotation, scale line and so on. 
Do you have any standart components over the map as other map components have?

**Comment by pauldendulk** [comment]
hi antonad,

Most of what you mention is not part of Mapsui out of the box. In most cases it is extendable to that.

### Zoom Controls
For mobile direct map navigation with fingers is used most of the time. Plus/minus buttons or a zoomlevel slider are not part of Mapsui. It is possible to use your own controls and change to MapControl.Map.Viewport.Resolution.

### Ma pRotation
What kind of control you expect here? The WPF sample has a rotation slider. You could use a similar approach.

### Scale Bar
There is no scale-bar yet. @charlenni has worked on it in the past. It will have to be an implementation of IWidget.

**Comment by pauldendulk** [comment]
btw, the ui in Mapsui suggests that this is primarily a ui project, but it is not (bad naming), it is a complete gis component. The ui will improve over time but is not the primary purpose. A lot more is going on.

**Comment by antonad** [comment]
Hello. I mean standart components like 
https://www.google.ru/search?newwindow=1&dcr=0&tbm=isch&sa=1&ei=MchxWsGQC8mosgHRtJfwAw&q=map+mobile+compass&oq=map+mobile+compass&gs_l=psy-ab.3...122188.123622.0.123743.8.8.0.0.0.0.117.707.6j2.8.0....0...1c.1.64.psy-ab..0.3.310...0i19k1j0i30i19k1j0i5i30i19k1j0i8i30k1.0.SArntjURLWk#imgrc=_7Gq1d7nEa6bLM:
and
https://www.google.ru/search?q=map+mobile&newwindow=1&dcr=0&tbm=isch&source=iu&ictx=1&fir=H6FwUqrWttdy8M%253A%252CfHzXIA1GonAFaM%252C_&usg=__wlU2da0ZU7sB4vu10ahqnKcOe0Y%3D&sa=X&ved=0ahUKEwiw7OTlqoLZAhULkSwKHakBBA0Q9QEIOjAC#imgrc=P0E5UrxP3VJmDM:.

I like your component, but it takes a lot of time to create this components. It is better to have some solution to have them in a box ans google for example

Thank you for examples, I will view them.

**Comment by charlenni** [comment]
@antonad I think, you understand something wrong. Mapsui doesn't have the ability to use your GPS to determin your position. And because of this, components for orientation or actual place are useless.

I add in the moment a scalebar and some zoom buttons for zooming in and out. So, if you want to have them, you have to wait some time.

**Comment by antonad** [comment]
Thank you. 
Of course scale bar and zoom functions are most important. I will wait for them. 
May be some control to switch layers is needed also.
I am using OpenLayers for web applications. You can see standart controls it includes.

**Comment by pauldendulk** [comment]
Mapsui does not have the ability to work with GPS out of the box but can be extended with such functionality. I have written apps where the GPS position is added to a MemoryLayer and added buttons to center on the GPS position or keep it centered while the GPS changes.
