### ISSUE TITLE
Add Mapsui.Rendering.OpenTK and Mapsui.Rendering.Gdi to NuGet package

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#30]

**Comment by kwesolowski** [comment]
Adding MbTiles.Pcl would be also helpful (we try to use nugets as dependencies instead of creating mutiple repository dependant build) - used from github it seemed to work ;)

**Comment by pauldendulk** [comment]
Perhaps MbTiles.Pcl could be in its own nuget package with a dependency on BruTile core, like BruTile.Desktop https://www.nuget.org/packages/BruTile.Desktop/

Would you use it like that?

**Comment by kwesolowski** [comment]
Sure - any way to use it as nuget package would be great.

**Comment by pauldendulk** [comment]
What do mean with '(and by making it easier to use code from master it encourages contributions)'?

**Comment by kwesolowski** [comment]
I meant that when nugets are available and updated frequently it simpler for me to fix bug and create pull request (and use nuget when it is released) than integrate multiple repositories and make it easy for other devs and build server to use "our fixed fork" :)

**Comment by pauldendulk** [comment]
Closing. This should be improved but not the highest priority right now.
