### ISSUE TITLE
Zoom In and Out ?

### ISSUE THREAD

**Issue by NikolaStamenov** [pauldendulk/Mapsui#300]
Hello.
I need to zoom in and out the map with a buttons [ + ] and [ - ].
Is there a simple way to do that ?

**Comment by pauldendulk** [comment]
You need to create your own buttons and call Mapsui methods.

For WPF you can use the MapControl ZoomIn and ZoomOut methods.

For the other controls you could change the resolution (half it, or double it for each step).

**Comment by NikolaStamenov** [comment]
It is for Android, and .. the point is that I got no idea how to change the resolution..
Is there some kind of example on this thing ? I am pretty new..

**Comment by pauldendulk** [comment]
We just release beta that includes @charlenni's new +/- buttons.

![image](https://user-images.githubusercontent.com/963462/35757507-ab037d22-086f-11e8-8950-eecf5652b383.png)

**Comment by NikolaStamenov** [comment]
Where is the example how to implement the buttons please. I can not find it.
( since I would like to navigate it from aside controls which is not in the map actually )

**Comment by charlenni** [comment]
You could find an example in the OsmSample.cs (https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/OsmSample.cs, line 12).

**Comment by NikolaStamenov** [comment]
But this is some sort of widget, which is not the thing I am looking for. I need to implement ( unfortunately for me ) my own controls in outside the map zone. 
That's why I were looking for sample just for the code of zoom in and out.
( by the way - sorry about not explained properly at the beginning )

**Comment by charlenni** [comment]
See https://github.com/pauldendulk/Mapsui/blob/master/Mapsui/Widgets/Zoom/ZoomInOutWidget.cs, line 186 and 195.

**Comment by NikolaStamenov** [comment]
Thank You so much !
