### ISSUE TITLE
Default center of map

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#304]
If I'm create a new Map and set the center of the map, but add later a layer with a map, the map isn't positioned at the center set while createing Map. Is this correct? Shouldn't the new layer set to the old center?

**Comment by pauldendulk** [comment]
> but add later a layer with a map
You mean you later add a layer to the same Map you created in the first step?

**Comment by pauldendulk** [comment]
A Map contains the Viewport. The Viewport should not change when you add a another layer. But I'm not sure if that is what you are doing.

**Comment by charlenni** [comment]
I create a Map without any Layer. Than I set the center via NavigateTo(). After this, I create a Layer and add this to Layers. When I do it this way, the screen stays empty (tested on Android). If I call NavigateTo() with the same center again, map is loaded and updated.

**Comment by pauldendulk** [comment]
The check here is meant to preserve the initialization of the center:
https://github.com/pauldendulk/Mapsui/blob/master/Mapsui/Viewport.cs#L293

NavigateTo is primarily meant to make sure the Map is refreshed too. This is not important here because there is no map to refresh if there is no layer. What if you set the Map.Viewport.Center directly?

**Comment by pauldendulk** [comment]
And do you also set the Map.Viewport.Resolution?

**Comment by charlenni** [comment]
Yes, I thought I have done this. But no results. I could set Center, but Resolution stays at NaN.

I now catch the ViewportChanged event and check, if Width and Height are both != 0 the first time. Than I call NavigateTo(). That works.

**Comment by pauldendulk** [comment]
Is there something specific that should be fixed?

**Comment by pauldendulk** [comment]
There might be an issue here. But since there is a workaround and I do not want to give this high priority I will close this now.

The logic should be that setting the center and resolution should be preserved also when there is no layer yet.
