### ISSUE TITLE
Automatically publish NuGets

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#310]
It should be possible to release prereleases fast, possibly automatic from the build server.

I am not sure what the best choices are here. 

### Frequency
- On every commit. Would that not be too much for a nuget publish?
- Nightly. This is what many projects used to do. But maybe that is old fashioned.

### Naming
- major.minor.patch-alpha+build?

### Target
Should this to the the nuget.org. I also see projects that use myget for prereleases. How would that work in the use? Just switch the source?

### How should this be scripted?
Mapsui uses appveyor as build server. I don't have any experience with this in other projects. You can specify a 'deployment' which creates an artifact during build that can deployed manually. It is also possible to deploy automatic on everybuild. It easy to use the buildnumber for the automatic release. I would prefer a counter that starts with 1 for a new main version.

**Comment by radderz** [comment]
I support this, there is a pre-release track in nuget that allows you to specifically see pre-release version, I think just a major.minor.patch-pre{build} i.e 1.3.2-pre3 where the 3 resets when the major, minor or patch changes. If someone doesn't want pre-release builds then they can just ignore them. I.e. in visual studio seeing pre-release builds is opt-in.

**Comment by pauldendulk** [comment]
The pre-release status in nuget is solely determine by the string tag after the proper major.minor.patch version. So the current 1.3.2-beta4 is considered a pre-release and it now shown if the pre-release is unchecked. 

No beta:
![image](https://user-images.githubusercontent.com/963462/35937737-78409bbe-0c47-11e8-9216-c43b5252e69f.png)

I would say there should be a distinction between a beta, which will have some features that are not properly tested, and just any commit made to master. 

An option might be to develop in a 'develop' branch and merge to master if you want to release a beta. 

A nightly could also be an option. It will be visible along with the beta releases but if the string tag is sufficiently different this might not be a problem.   

About the version number increments. I would also choose the way you describe. The current way to determine the beta number is by manual change of an appveyor string. I think this could better be managed inside the repository in some version.txt, but we need some scripting for this. I now prefer .NET Core console apps for my scripting, like I used for the Tools\VersionUpdater

**Comment by pauldendulk** [comment]
Made some progress. AppVeyor has it's own nuget feeds. There are project feeds and account feeds.
I just now added an automatic push to the build which appends a 'build' string plus the build number to the version string. You can query the packages with:
```
nuget list -source https://ci.appveyor.com/nuget/mapsui -prerelease
```
The response is:
```
Mapsui 1.3.2-beta4-137
```
Apparently it stores only the most recent package, but that might even be good enough. The account feed is more persistent. I have not looked into that yet. 

So with respect to above questions.
- Frequency: On every checking. Let's call it the CI release.
- Target: AppVeyor project and/or account feed
- Naming: Perhaps something like the above it good enough. It is nice to have the beta part in so it can be related to those releases. Alternatives:
   1. 1.3.2-beta4-137
   2. 1.3.2-beta4-ci137 (for continuous integration). 
   3. 1.3.2-beta4- build137.
   4. 1.3.2-beta4-b48ed0753839f84d2aebb38e6ee533c6decbc095 commit hash.
   5. 1.3.2-beta4-1 (start counting commits after original version from 1).
   6. 1.3.2-pre137 Simple, but it is not clear how it relates to betas.
I think I like 5 best. 
- Scripting: Could be simple as it is now. Perhaps I would like to have a version.txt in the repo.

**Comment by pauldendulk** [comment]
Pull requests are also published as CI nuget.

**Comment by pauldendulk** [comment]
The AppVeyor documentation: https://www.appveyor.com/docs/nuget/

**Comment by radderz** [comment]
5 or 1 are good I think, with 5 preferred

**Comment by pauldendulk** [comment]
I now use a dot separator to get proper numeric compare in the build number: https://semver.org/

Otherwise 
```1.3.2-beta4-137```
would be lower than:
```1.3.2-beta4-2```

**Comment by pauldendulk** [comment]
Better would be:
```1.3.2-beta.4-137```
with a dot between beta and 4. But I have to introduce that after the next patch release because ```1.3.2-beta.4-138``` is lower than ```1.3.2-beta4-137```.

**Comment by pauldendulk** [comment]
This works fine now.
