### ISSUE TITLE
Selecting a country in a shapefile via a click event

### ISSUE THREAD

**Issue by npace** [pauldendulk/Mapsui#314]
I'm trying to make a WPF desktop application that renders a map of the world and lets the user click on a country in order to select it and display some relevant information. 

So far my approach is to use a shapefile and render that with Mapsui, and set an Info EventHandler to get the screen and world space coordinates. 
My idea is to basically solve a point-in-polygon problem by comparing the coordinates of the click event with the shapes of various countries.

Is this a sound idea? Can anyone give me any tips on how to efficiently access the country shape data? After I identify the clicked country, is it feasible to dynamically add a new layer to the map, rendering only the selected country in a different color?

**Comment by radderz** [comment]
Hi npace, yes that is a sound idea, you would use the click location and the "ScreenToWorld" function to find where the click was relative to the shape file spatial items. Just make sure you get the click location relative to the view!

**Comment by pauldendulk** [comment]
Did you find the ShapefileSample? It can help you to get started?

Do you select the country in a map or from a list? 

It is also possible to use a ThemeStyle to make certain countries visible. This way you could load just one layer, and show one country at a time.

**Comment by radderz** [comment]
Actually the info event will contain the clicked polygon. You shouldn't need to do anything like a spatial intersection based on screen position.

**Comment by pauldendulk** [comment]
Here some discussion on ThemeStyle and a pointer to a sample in the VectorTiles fork. https://github.com/pauldendulk/Mapsui/issues/266

**Comment by npace** [comment]
Wow, thanks for the quick response, guys!

@pauldendulk 

> Did you find the ShapefileSample?

Yep, I've based my code on the ShapefileSample class.

> Do you select the country in a map or from a list?

I want to select a country in the map, by clicking within the country's territory.

@radderz 
The InfoEventArgs object passed via the Info EventHandler contains null values for its ILayer and IFeature properties. After snooping around in InfoLayersSample and ShapefileSample, I think this is because my shapefile isn't an info layer. 

If I modify the call in Map.InvokeInfo from `var eventArgs = InfoHelper.GetInfoEventArgs(Viewport, screenPosition, scale, InfoLayers, symbolCache, numTaps);` to `var eventArgs = InfoHelper.GetInfoEventArgs(Viewport, screenPosition, scale, Layers, symbolCache, numTaps);`, I get the clicked feature in my eventArgs.

Using this knowledge, I tried to add an info layer using the same ShapeFile as a DataSource, but the InfoEventArgs in my EventHandler still contains nulls. What am I missing here? This should be fairly straightforward, I just don't think modifying Map.InvokeInfo is a clean approach.

The ThemeStyle discussion looks promising, I'll try to implement this after resolving the click issue.

**Comment by radderz** [comment]
Hi npace, I haven't tried a shapefile with an info layer, but yes it would need to be an info layer for it to contain the feature.

If that isn't working though, it is trivial to use the ScreenToWorld function of the GlobalSphericalMercator class and then you can do an Intersection with the shapes. If you have many shapes, you may want to do a simple feature bounding box check before doing an intersects to keep performance in check.

**Comment by pauldendulk** [comment]
@npace Just looked at this with the sample. There is an issue if you use this in combination with the RasterizingLayer. The RasterizingLayer wraps the shapefile layer to gain performance. The featureInfo however returns the feature from the RasterizingLayer. You need to replace this:
```
map.Layers.Add(new RasterizingLayer(CreateCountryLayer(countrySource)));            
```
with this:
```
map.Layers.Add(CreateCountryLayer(countrySource));
```

**Comment by pauldendulk** [comment]
A solution could be to make a distinction between GetFeatures and GetRenderFeatures. The same issue will exist with rasterized vector tiles.

**Comment by npace** [comment]
Sorry for the late reply...
So far, just unwrapping my country layer from the rasterizing layer didn't improve my situation - all it did was make the UI thread slightly jankier.

I'm going to look through the ShapeFile provider class to make sure that my shapefile's info is getting parsed correctly.

**Comment by pauldendulk** [comment]
If you take the current master code as a starting point and in ShapefileSample modify the CreateMap sample like this:
```
        public static Map CreateMap()
        {
            var map = new Map();

            var countrySource = new ShapeFile(GetAppDir() + "\\GeoData\\World\\countries.shp", true) {CRS = "EPSG:3785"};
            var citySource = new ShapeFile(GetAppDir() + "\\GeoData\\World\\cities.shp", true) {CRS = "EPSG:3785"};

            map.Layers.Add(CreateCountryLayer(countrySource));
            map.Layers.Add(new RasterizingLayer(CreateCityLayer(citySource)));
            map.Layers.Add(new RasterizingLayer(CreateCountryLabelLayer(countrySource)));
            map.Layers.Add(new RasterizingLayer(CreateCityLabelLayer(citySource)));

            map.InfoLayers.Add(map.Layers.FindLayer("Countries").First());

            return map;
        }
```

Starte the WPF sample, select 'Shapefile (Desktop)' and click a country, like Greenland in the screenshot the result shows center right.

![image](https://user-images.githubusercontent.com/963462/36384696-77ecd054-1590-11e8-9486-53024303d5ed.png)

**Comment by npace** [comment]
Yep, that definitely works and is way simpler than my initial idea. Thanks!
