### ISSUE TITLE
BitmapRegistry problem

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#315]
I get an error "Mutating a key collection derived from a dictionary is not allowed" when removing a bitmap from the BitmapRegistry by BitmapRegistry.Unregister(). Did this the whole day and now I get an error. I assume, that it is correct, because the line 

    _register.Keys.Remove(id);

shouldn't work for a Dictionary.

Any ideas, what I'm doing wrong?

**Comment by pauldendulk** [comment]
Looks like an ancient bug where it should be:

```
_register.Remove(id)
```
You say you did this whole day?

**Comment by charlenni** [comment]
I thought, but now I‘m not sure anymore :)

**Comment by pauldendulk** [comment]
So, I just made a commit and now the wonderful AppVeyor is configured to publish a latest build nuget package automatically. You can see it from the command line with this:
```
nuget list -source https://ci.appveyor.com/nuget/mapsui -prerelease
```
The feed itself should be added to you nuget feeds in visual studio, or better in the nuget.config of you sln. Feed: https://ci.appveyor.com/nuget/mapsui 

AppVeyor documentation:
https://www.appveyor.com/docs/nuget/#configuring-private-nuget-feed-in-visual-studio

**Comment by radderz** [comment]
@pauldendulk , with the prerelease, it doesn't show up in visual studio for me, is there a flag to see if its a listed prerelease?

**Comment by pauldendulk** [comment]
I added a wiki page with instructions:
https://github.com/pauldendulk/Mapsui/wiki/NuGet-of-latest-build

**Comment by charlenni** [comment]
Problem is solved.
