### ISSUE TITLE
Feature with dynamic geometry

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#316]
I created a Feature with a dynamic Geometry. It is a line, where from time to time a new point is added.

Now I have the problem, that the screen on Android isn't updated, when changing the Geometry property. On UWP on desktop this isn't a problem. If I turn of the Android device and on again, the screen is redrawn and the line is visible.

Which function in which control should I call to update the screen after changing a Feature?

**Comment by radderz** [comment]
If you are updating a geometry value, make sure you call Map.ViewChanged(true) and this will refresh the screen. I'd suggest you only call this as infrequently as you need to though as its a redraw of all items I think. So try to batch your changes where you are doing many small changes.

**Comment by radderz** [comment]
You could possibly call the Layer's ViewChanged that holds the geometry too, but I tend to call map.viewchanged as the the layer one requires a bounding box etc which is probably more efficient, but I was lazy.

**Comment by charlenni** [comment]
@radderz you talked about animations and that you had them in your Xamarin.Forms control. D you think, it is possible to have this code? Or is it confidential?

**Comment by radderz** [comment]
Hi charlenni, I am a bit busy at the moment but I fully intend to extend mapsui with pan/zoom/rotation/fling animations when I get a chance, I cannot directly show our existing code as its company IP. I have pretty good animations running that follows other mapping tools quite well around when to stop an animation based on interactions etc.

**Comment by charlenni** [comment]
That sounds very good. Do you want to implement it in Mapsui or in MapControl?

And about IP: isn‘t Mapsui under LGPL? 😉

**Comment by radderz** [comment]
The Mapsui library is, but not the code that wraps outside of it...

**Comment by charlenni** [comment]
Perhaps you could talk to company, that it would be nice, if they return something to the community, because they profit from that work too. I think, all would say „Thank you very much“. 👍🏼

**Comment by radderz** [comment]
Hence why I said when I get time, I have been doing quite a few updates and extensions to the project which benifits you the community already.

**Comment by charlenni** [comment]
It was easier than I thought. A invalidate of the surface of the MapControl is enough to render the map. In my case (Skia) a InvalidateSurface() is ok.
