### ISSUE TITLE
Info event gets fired while panning/zooming the map

### ISSUE THREAD

**Issue by mknuepfer** [pauldendulk/Mapsui#323]
Hi, I got my project running with MapsUI and it is working good. The user can tap to select a point on the map. This is handled by the Info event. The problem is that the event also gets fired if the user pans or zooms the map. How can we find out if the map is currently panning/zooming?

**Comment by charlenni** [comment]
Hello,

you forgot to mention, which MapControl do you use (Android, iOS or Uwp?) And also the version of MapsUI would be helpfull.

**Comment by radderz** [comment]
Hi Mknuepfer, this is the current state of the stable version of mapsui, if you try the pre-release beta then the taps are handled properly. The latest code includes a number of taps in the info event.

**Comment by mknuepfer** [comment]
I'm using the current stable version 1.3.1 with a custom made control/renderer for Xamarin Forms on iOS and Android.

**Comment by pauldendulk** [comment]
@mknuepfer Try to install the pre-release.

**Comment by mknuepfer** [comment]
OK, this is working with 1.3.2-beta4. Thank you guys for your great work.

**Comment by radderz** [comment]
Hi @mknuepfer, there is one bug in 1.3.2-beta4 that is fixed for the next release where iOS will treat a double click as two single clicks and a double click.
