### ISSUE TITLE
Multiple symbol styles not supported

### ISSUE THREAD

**Issue by spaddlewit** [pauldendulk/Mapsui#326]
When you add multiple symbol styles to a point, they are not layered.. only the most recently one added is drawn.

I'm using the BitmapId.

**Comment by pauldendulk** [comment]
Is this a new issue? How is this with vector on top? There is some layering in the symbols sample.

**Comment by charlenni** [comment]
It would be nice to see some code and to know, if you use WPF or Skia.

**Comment by spaddlewit** [comment]
I don't know if it's new. I've never tried layering bitmap symbols before.

Take BitmapSymbolSample.cs, and modify it to have multiple SymbolStyles on a feature with BitmapIds. I'm trying to run the UWP sample but it seems to be targeting Windows Phone.

**Comment by spaddlewit** [comment]
Skia. Somebody still uses WPF? (kidding, kidding... see #319 )

**Comment by pauldendulk** [comment]
Okay, I'll try that. 

In the meantime I modified the SymbolsSample, added two bitmaps to the stacked symbols and there are no problems there.

![image](https://user-images.githubusercontent.com/963462/36443382-dc08cf46-1678-11e8-8244-b0c7b772ddc5.png)

**Comment by charlenni** [comment]
You layer two bitmaps and not a VectorStyle and a bitmap? Is the second bitmap so big, that the first isn't anymore visible?

**Comment by spaddlewit** [comment]
Yes, I'm layering two bitmaps. And no, I've tried making the second bitmap multiple sizes (SymbolScale), even making it very tiny, and the bitmap behind it is not displaying.

Maybe the first bitmap is affected by the second's SymbolScale and thus becoming too small as well?

**Comment by spaddlewit** [comment]
![snap1](https://user-images.githubusercontent.com/29378443/36443697-7eeb3834-1647-11e8-90cf-689c84773a41.png)

Results in this. There should be a red circle underneath the green checkmark:

![snap2](https://user-images.githubusercontent.com/29378443/36443731-900abfb8-1647-11e8-83e7-b1ac654468ae.png)

BTW, this is Mapsui 1.2.0, due to #276

**Comment by pauldendulk** [comment]
If I take the BitmapSymbolSample and add the two bitmaps on top of each other I get this below. Seems correct.

![image](https://user-images.githubusercontent.com/963462/36443768-f0e7ca9c-1679-11e8-9315-346f90f94f45.png)

**Comment by spaddlewit** [comment]
Ohhhh my gosh. After I pasted the code screenshot, I see the terrible error I made. I'm so embarassed and sorry, Paul! You may close this issue, and apologies for taking up your time.

**Comment by pauldendulk** [comment]
Symbol scale is set for individual symbols, they do not affect each other.

**Comment by pauldendulk** [comment]
hehe, well we had a nice conversation. It is almost a chatroom like this. 

And thanks @charlenni thinking along.

**Comment by charlenni** [comment]
Would it be possible to get the problem you made?

**Comment by spaddlewit** [comment]
Yes -- you'll see that I do:
var checkStyle = new Mapsui.Styles.SymbolStyle();

But instead of proceeding to use checkStyle, I use an earlier declared variable, 'style', to make the property modifications and then add it (again) to the feature.Styles list.

Bad variable scope, and this section of code could use some cleanup.
