### ISSUE TITLE
RasterizingLayer doesn't work for outlined, non-filled polygons (Skia)

### ISSUE THREAD

**Issue by spaddlewit** [pauldendulk/Mapsui#327]
`Mapsui.Layers.Layer layer = new Mapsui.Layers.Layer("Grid");

List<IFeature> features = new List<IFeature>();
// Add my features
layer.DataSource = new MemoryProvider(features) { CRS = "EPSG:4326" };

return new RasterizingLayer(layer);
`
if I just return 'layer' and add it to the map, it displays, with a label on the centroid and everything. If I use new RasterizingLayer(layer), the layer may as well be invisible.

**Comment by spaddlewit** [comment]
Update -- not working on filled polygons, either. Tested both iOS and UWP.

**Comment by pauldendulk** [comment]
Do you use projection from lonlat to SphericalMercator (the coordinate system of the openstreetmap layer)?

Does it work for lines? or Points? Outlined polygons?

**Comment by pauldendulk** [comment]
Update: Rasterizing in combination with projection does not work properly.

**Comment by spaddlewit** [comment]
Bummer. I guess I can just reproject when generating the feature set? What's the most optimized way to do this using Mapsui? (I see Projection utilities and such, but this would be in a performance-minded area of code).

**Comment by pauldendulk** [comment]
You could transform to SphericalMercator when you first receive the feature so that you have to do it only once. 

I think you could create your own instance of MinimalTransformation for the transformation.
