### ISSUE TITLE
Imagelayer cache issue

### ISSUE THREAD

**Issue by Kortdag** [pauldendulk/Mapsui#330]
I have tried to pinpoint the issue but have´t found the root cause. I presume its at cache  / raster rendering issue. Please find a sample attached.

What I´m trying to accomplish is making a non tiled WMS layer. The layers should support grouped layers e.g. WMS requests on the form:
...Layers=X,Y,Z&Styles=A,B,C
where the user is able to change active layers / styles from a layer control. So every time a change occurs I would like to redraw the layer from a new WMS request. E.g.
...Layers=X,&Styles=A
...Layers=X&Styles=B
...Layers=X,Y&Styles=A,B 

In the sample attached I have made an inherited ImageLayer with a custom WMS provider returning the Raster. But as shown every new "ViewChanged does not translate into an updated map except if you make a pan, which also seems a bit "random". I presume its a caching issue?

[TestSample.zip](https://github.com/pauldendulk/Mapsui/files/1774749/TestSample.zip)

**Comment by pauldendulk** [comment]
Thanks for the sample. 

I what you want is already possible with the current provider. The available layers are present as ChildLayers in the RootLayer of the provider. The sample below adds all the layers starting with "warmte".

**Comment by pauldendulk** [comment]
```
using System.Linq;
using Mapsui.Layers;
using Mapsui.Providers.Wms;

namespace Mapsui.Samples.Common.Desktop
{
    public static class WmsSample
    {
        public static Map CreateMap()
        {
            var map = new Map {CRS = "EPSG:28992"};
            // The WMS request needs a CRS
            map.Layers.Add(CreateLayer());
            return map;
        }

        public static ILayer CreateLayer()
        {
            return new ImageLayer("Windsnelheden (PDOK)") {DataSource = CreateWmsProvider()};
        }

        private static WmsProvider CreateWmsProvider()
        {
            const string wmsUrl = "https://geodata.nationaalgeoregister.nl/omgevingswarmte/wms?request=GetCapabilities";

            var provider = new WmsProvider(wmsUrl)
            {
                ContinueOnError = true,
                TimeOut = 20000,
                CRS = "EPSG:28992"
            };

            var warmteLayers = provider.RootLayer.ChildLayers.Where(l => l.Name.StartsWith("warm")).Select(l => l.Name);
            foreach (var warmteLayer in warmteLayers)
            {
                provider.LayerList.Add(warmteLayer);
            }
            provider.SetImageFormat(provider.OutputFormats[0]);
            return provider;
        }
    }
}
```

**Comment by pauldendulk** [comment]
Styles can be added in a similar fashion.

**Comment by Kortdag** [comment]
I looked at the sample already but for different reasons I cannot communicate directly with the wms server. There are proxy server and custom app configuration involved. So cant use the desktop sample but Thanks for the hint.

Anyway all I have built works as expected. A layer control databound to layer visibility and selected style and the end result of user interactions on a list of layers boiled down to one new wms request. 
The problem is that on property changed the layer redraw from code does not update the map to the last fetxhed raster. Making a small pan updates the map alright.
 
The sample shows the behavior where the periodic task changes the style on every request. The map should "flick" between style A and style B without any pan or zoom. But it doesnt. 

I can see a commit in this thread introducing a fetch delay. Is it a fix for solving the problem or unrelated?

**Comment by pauldendulk** [comment]
The commit adds a delay between manipulation and the data fetch to reduce the number of fetches. It was designed to work like that but it didn't.

In general the refresh is triggered by the DataChanged event. It should be called after new data was fetched. To debug this you could create a copy ImageLayer in your own code and step through it. 

Why really need a GroupedWmsOverlay. Can't you use the Imagelayer itself?

**Comment by Kortdag** [comment]
Hi I was able to figure out whats going on. 
It all had to do with resolutions and the consequence when using a tiled layer and an image layer.

The Raster Renderer takes into account the resolution to figure out the  screen coordinates. When using only an image layer with no resolutions it behaved as expected. Adding a tiled layer with resolutions changes the behaviour when refreshing the ImgLayer.

But it seems I just HAVE to call the refresh of the ImageLayers with a reference to the current viewport bounds and resolution and it works.
ViewChanged(true, map.Viewport.Extent, map.Viewport.Resolution);

Before I had something like 
ViewChanged(true, this.Extent, 1);
like I had for a memorylayer. 

This worked until adding a tiled layer in which case the RasterRenderer after the first request started to take into account the resolution from the tiled layer and thereby misplaced the imagelayer geometry.


**Suggestion:** Are there any applications where a non API call would ever call ViewChanged except without providing the current viewport bounds / resolution?
If not a suggestion would be to make it internal or maybe protected for inheritance and implement af parameterless redraw method?

For ImageLayer like 

public void Redraw()
{
        ViewChanged(true, _newExtet, _newResolution);
}

Best regards

**Comment by pauldendulk** [comment]
You are calling the ViewChanged from inside a Layer where there is no extent and resolution available. This is not a very common scenario. The purpose of the ViewChanged method is to tell the layer what the new viewport is. 

In line with your suggestion; The Map has a ViewChanged method without extent and resolution parameters as you describe. The MapControl has a RefreshData method. RefreshData is actually a better name since it's purpose is not to redraw immediately. It will fetch the data and redraw as a consequence, after the data has changed.
