### ISSUE TITLE
Using images as markers (feature - point)

### ISSUE THREAD

**Issue by antonad** [pauldendulk/Mapsui#332]
Hello. I have found an example how to make Point with image, but image can be linked only by ID (as resouce). 
Can I use an image from memory (bitmap, byte array,...)? 
Can I rotate an image on a map using styles (or some other mapsui setting)?

**Comment by pauldendulk** [comment]
There is a SymbolStyle.SymbolRotation. It is used in BitmapSymbolWithRotationAndOffsetSample.

You can load a bitmap from disk or web, convert to Stream (if necessary) and register it with BitmapRegistry.Register. This returns the id you can use in the SymbolStyle.BitmapId.

**Comment by pauldendulk** [comment]
Did this solve your problem?
