### ISSUE TITLE
When a label style is applied to every feature the point shows under the label (Xamarin Forms)

### ISSUE THREAD

**Issue by josesimas** [pauldendulk/Mapsui#336]
Hello,

I hope this is the right place for a beginner'a question.

I am adding labels for a number of features in a map and I cannot find a way to remove the white circle that appears with them:

![image](https://user-images.githubusercontent.com/18383/37206033-f5100cde-238e-11e8-9713-b2d8cf76c91c.png)

This is the code I am using:

	foreach (var point in locations)
	{
		var feature = new Feature
		{
			Geometry = point,
		};
		feature.Styles.Add(
			new LabelStyle
			{
				Text = labels[counter],
				HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Center,
				Offset = new Offset(0, -50),

			});
		counter++;
		features.Add(feature);
	}

	var layer = new MemoryLayer
	{
		Name = "Locations",
		DataSource = new MemoryProvider(features),
		
	};
	map.Layers.Add(layer);

What am I missing? I could not find anything alike in the samples (both Android and WPF).

Thanks,
Jose

**Comment by charlenni** [comment]
I assume, the problem is Layer.Style. Each Layer has an overall Style, which has a s default a white circle. Try

    var layer = new MemoryLayer
    {
    	Name = "Locations",
    	DataSource = new MemoryProvider(features),
    };
    
    layer.Style.Clear();

This should work.

**Comment by pauldendulk** [comment]
Yes, you can ask any question here. 

This is common issue. I guess we should remove that default style in another major release.

**Comment by josesimas** [comment]
Thanks both!

It was solved by adding layer.Style = null as @charlenni suggested (or close enough 👍 ).
