### ISSUE TITLE
ShowInfo event InfoEventArgs Feature and Layer properties are always null in Mapsui Forms

### ISSUE THREAD

**Issue by josesimas** [pauldendulk/Mapsui#337]
Hi,

I have a map with a number of features such as labels and images. I was expecting that when I tap those features they would appear in the InfoEventArgs object of the Info event. I tried adding the said layers to MapView.Map.InfoLayers.Add(); but without any results. Is this something that is not implemented in Mapsui Forms or is there something else that needs to be done for the features to show up in the event?

Thanks,
Jose

**Comment by pauldendulk** [comment]
I stayed away from forms so far, but this is implemented in all Mapsui platforms and I know is used in some forms implementations. Do you use @charlenni forms? https://github.com/charlenni/Mapsui.Forms

**Comment by josesimas** [comment]
Yes, I am using that implementation. So I must be missing something. Do I have to add the layers with the features to the the InfoLayers collection?

**Comment by charlenni** [comment]
This has nothing to do with Mapsui.Forms. It is a Mapsui problem. Most users forget to add features to Layer **and** InfoLayer. Mapsui only detects info events for features, which are added to InfoLayer.

**Comment by josesimas** [comment]
Thanks, maybe I am doing something wrong there, I will have another look and come back.

**Comment by pauldendulk** [comment]
@charlenni But @josesimas mentions in his first post that he added his layer to the InfoLayers, so I assumed this was not the problem here.

@josesimas Perhaps first get this to work for WPF or Android.

**Comment by josesimas** [comment]
Hi, I am terribly sorry, it was my mistake. It works correctly. I was adding them in the wrong place in the code.

**Comment by pauldendulk** [comment]
no problem :)
