### ISSUE TITLE
Using the Google maps zoom levels with Mapsui

### ISSUE THREAD

**Issue by josesimas** [pauldendulk/Mapsui#338]
Hi,

I am trying to find a correspondence between Google maps zoom levels and resolution or equivalent in Mapsui. I found this list of correspondence to a scale:

https://gis.stackexchange.com/questions/7430/what-ratio-scales-do-google-maps-zoom-levels-correspond-to

But I could not also find a way to determine a radius or a resolution from them. I suppose this question is not specific to Mapsui and I thank any leads you could give me.

Thanks,
Jose

**Comment by charlenni** [comment]
You are on the right way. If your map uses EPGS:3857 (spherical web mercator, which is used by Google), than the values in the table are Viewport.Resolutions. This said, setting 

    Viewport.Resolution = 288895.288400

will the map show with Google zoom factor 20.

With a radius it is a little bit difficult, because it depends on place of the map, where you want to get it. See the answer of gilad mayani on the link.

**Comment by josesimas** [comment]
Hi, thanks. Do you mean 288895.288400 corresponds to 12 (as it is in the table) or to 20 as in your answer? Resolutions are fine for me, I just need to convert to zoom levels because that is what the current system stores from session to session.

**Comment by josesimas** [comment]
I got it @charlenni, the numbers on that link don't really line up with the resolution in terms of the expected zoom (according to Google).

**Comment by charlenni** [comment]
Sorry, that was a typo :(

Perhaps the correct would be [here](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Resolution_and_Scale).

**Comment by josesimas** [comment]
Many thanks @charlenni  this new table matches what I am seeing in my map!

**Comment by pauldendulk** [comment]
Hi @josesimas, I think your question was already answered but some further info. Mapsui uses the [BruTile](https://github.com/BruTile/BruTile). Mapsui used to support Google Maps but their protocol got more complicated in later releases and they did not allow other clients than their own maps api. There is still a sample of a Google layer in BruTile so you could take a look there. I think basically the google levels are the same as those of OpenStreetMap. 

The code for the Google Map is [here](https://github.com/BruTile/BruTile/blob/master/Samples/BruTile.Demo/MainWindow.xaml.cs). If you download the BruTile and run the demo the is a option at the bottom.

Also important. Mapsui itself has no resolutions at all. The resolution are in the background layer. In most cases that is the OpenStreetMap layer but it could be anything else.

**Comment by pauldendulk** [comment]
![image](https://user-images.githubusercontent.com/963462/37370023-4281e54e-270b-11e8-8850-8c5cc567d7d9.png)

**Comment by pauldendulk** [comment]
Here is a sample of Google Maps in Mapsui

```
using System;
using System.Net.Http;
using BruTile;
using BruTile.Predefined;
using BruTile.Web;
using Mapsui.Layers;

namespace Mapsui.Samples.Common.Maps
{
    public static class GoogleMapsSample
    {
        public static Map CreateMap()
        {
            var map = new Map();
            map.Layers.Add(new TileLayer(CreateGoogleTileSource("http://mt{s}.google.com/vt/lyrs=t@125,r@130&hl=en&x={x}&y={y}&z={z}")));
           return map;
        }

        private static ITileSource CreateGoogleTileSource(string urlFormatter)
        {
            return new HttpTileSource(new GlobalSphericalMercator(), urlFormatter, new[] { "0", "1", "2", "3" },
                tileFetcher: FetchGoogleTile);
        }

        private static byte[] FetchGoogleTile(Uri arg)
        {
            var httpClient = new HttpClient();

            httpClient.DefaultRequestHeaders.TryAddWithoutValidation("Referer", "http://maps.google.com/");
            httpClient.DefaultRequestHeaders.TryAddWithoutValidation("User-Agent", @"Mozilla / 5.0(Windows; U; Windows NT 6.0; en - US; rv: 1.9.1.7) Gecko / 20091221 Firefox / 3.5.7");

            return httpClient.GetByteArrayAsync(arg).ConfigureAwait(false).GetAwaiter().GetResult();
        }
    }
}

```

**Comment by pauldendulk** [comment]
There resolutions are defined in the class GlobalSphericalMercator. That can be found here: https://github.com/BruTile/BruTile/blob/master/BruTile/Predefined/GlobalSphericalMercator.cs
There are parameter overload to change the number of levels.

**Comment by josesimas** [comment]
Hi Paul,

That is fantastic thanks! I have to say that you guys are super and have been a great help (Mapsui is great but that goes without saying :-).
I was wondering why Mapsui does not support Google maps out of the box, but now I understand (thanks for the example code, I will use it if we decide to implement Google maps). BruTile seems to be the key to some things I will need such as caching (my users may be offline in places). I will have a look into BruTile next.
As far as the resolutions are concerned, the table approach solves my requirement which is to simply adjust to a certain Google zoom level at startup.

Thanks,
Jose
P.S. Sorry, I keep adding an extra "i" to the end of Mapsui

**Comment by pauldendulk** [comment]
Argh!, that extra "i", I just had to fix it. It is not as bad the the MapUI casing though, that is really upsetting ;)
