### ISSUE TITLE
iOS MapControl does not correctly resize the SK view

### ISSUE THREAD

**Issue by JoeCooper** [pauldendulk/Mapsui#341]
The viewport and the SK view do not match the size of their parent element.

![screen shot 2018-03-14 at 12 30 14 pm](https://user-images.githubusercontent.com/5166338/37399933-84864098-2783-11e8-99ff-a7aaa1272952.png)

In the screenshot, it's inheriting its size from whatever happens to be going on in Interface Builder. If I resize it in Interface Builder, it's resized at runtime. This is not acceptable behavior because there is no relationship between its size in Interface Builder and the ideal size at runtime.

This is something I've fixed before with layout constraints but this seems to have been undone. Is there any particular reason for this? What's the story?

**Comment by JoeCooper** [comment]
I found the commit here but there's no explanation for it:

https://github.com/pauldendulk/Mapsui/commit/5357381a4a84298fb0d28a446d6db14e9c657cfc

**Comment by JoeCooper** [comment]
It looks like it was changed while thrashing on this issue:

https://github.com/pauldendulk/Mapsui/issues/245

You wrote, "I published a beta where the NSLayeroutContrained is removed, this could solve the issue."

However, the complainant wrote, "Just tested 1.3.0-beta2 and 1.3.0-beta3. Both has still the white border."

So I don't know why it was just left broken.

**Comment by JoeCooper** [comment]
I see it's based on a stack view again. I'll see if I can find a solution based on stack view. It appears that it's both based on stack view (which is an automatic layout mechanism) and assigns a frame to the child view, which may be the error.

**Comment by pauldendulk** [comment]
I was kind of desperate while trying fix that issue, so I might have broken some things. In the end it was not fixed. I assume it is a problem with SkiaSharps view. For the user the problem was solved by making it possible to set the background color which can be used as a workaround.

Another change that has occurred in the meantime is that the attribution is not a client side thing anymore. It is fully rendered as part of the map (which simplifies things a lot for me). 

The removal of the NSLayeroutContrained on the entire view was just a failed attempt to fix that issue. So I guess it should just be moved back.

**Comment by JoeCooper** [comment]
> So I guess it should just be moved back.

Not necessarily.

I'm going to see if I can make a stack layout size it correctly, and I'll get back to you, I think, later today.

**Comment by JoeCooper** [comment]
> Another change that has occurred in the meantime is that the attribution is not a client side thing anymore.

I see – that does make the stack view a bit over designed for the task now.

**Comment by pauldendulk** [comment]
Whatever you think is the best option. I have learned that my understanding of iOS widgets is limited.

**Comment by JoeCooper** [comment]
Okay so since it's the only child view I did just go ahead and revert it to make it fill the parent.

I have two questions.

1) Can you tag me in if a bug report comes in after this?

2) Can you make a beta build so I can reference this via NuGet?

**Comment by pauldendulk** [comment]
1. Yes
2. There should be a package of the build. I tested this only once. I don't think many people use this. If it does not work for you then let me know. https://github.com/pauldendulk/Mapsui/wiki/NuGet-of-latest-build

**Comment by pauldendulk** [comment]
note, I have been working with the latest build release and it seems to work smooth. You have to know that it only contains the very latest build, not older ones. So if your project refers to an older nuget you have to update.

**Comment by pauldendulk** [comment]
This is fixed.
