### ISSUE TITLE
Add inertia/momentum/smoothness on drag pan

### ISSUE THREAD

**Issue by AliFlux** [pauldendulk/Mapsui#351]
Hi.

I love the way Mapsui incorporates inertia/momentum when we zoom in or out. There's a visible `easiness` upon zoom. Is there a way to add such a momentum for panning as well?

Google Maps has the support. When we pan the map, it keeps on moving even after the mouse button is up. And it slowly stops down.

Thanks.

**Comment by pauldendulk** [comment]
Some related discussion here: https://github.com/pauldendulk/Mapsui/issues/306

**Comment by pauldendulk** [comment]
This is covered by another issue. So I close this

**Comment by balbarak** [comment]
is inertia available on MAUI ?
