### ISSUE TITLE
ViewChangedEventArgs does not contain information on whether the change is complete

### ISSUE THREAD

**Issue by Shchyekinyanin** [pauldendulk/Mapsui#36]
WPF. I'm trying to create a tool for the history of user movements on the map. The tool is signed up for an event ViewChanged of MapControl. But this event raising too much times while viewing the map and ViewChangedEventArgs does not contain information on whether the change is complete, such as method ViewChanged(bool changeEnd) of Map. It would be very nice if in the event there is a new property, announces the completion of changes or new event that raises at the end of changes.

**Comment by pauldendulk** [comment]
I understand your needs. This is not something I expect to be working on soon. Perhaps you can work with your own version of MapControl.cs. 

also see:

https://github.com/pauldendulk/Mapsui/wiki/How-to-work-with-Mapsui

> A common scenario is that you need more functionality from the MapControl. In that case you can still use the NuGet package but don't add a reference to Mapsui.UI. Instead copy it's files to your own project (MapControl.cs and a few others). You can customize these for your own needs. 

When I pick up work on the MapControl (apart from my own immediate needs) I will probably start on an IMapControl interface to bring all platforms in line.

**Comment by pauldendulk** [comment]
I gave this some more thought. There is now a ViewportChanged on the Map. This contains just the current viewport state. The start/complete information is part of the users manipulation and belongs to the MapControl. Perhaps it could pass that information to the Map. Then the Map could trigger a event with that information. But I have no plans to add this soon. 

A possible workaround for your scenario (without copying the MapControl) could by to register the MapControl's manipulation completed event event and then store the Map.Viewport state in your history.

I am going to close this for now. Please reopen if no workarounds are possible for you.
