### ISSUE TITLE
Map navigates to greenwich at startup

### ISSUE THREAD

**Issue by josesimas** [pauldendulk/Mapsui#366]
Hello,

I am getting this issue in that my map (using the OpenStreetmaps provider) navigates to Greenwich the first time the mapping page is opened (I am using Xamarin Forms and Android).

I debugged the code and I can see it navigating to the proper place just before the page opens but to no avail, it always ends up in Greenwich. I suppose the issue is that I am navigating too soon and my coordinates are lost somehow.

I wonder if there is an event from the map that tells me it is ready to navigate?

Thanks,
Jose

**Comment by pauldendulk** [comment]
NavigateTo does not function when MapControl Width and Height are not known. There are 2 solutions. 
1. Set the Map.Viewport.Resolution and Center.
2. Call NavigateTo on the Loaded event.

**Comment by josesimas** [comment]
Hi Paul,

Many thanks! I will do that.

Jose
