### ISSUE TITLE
IThemeStyle.GetStyle(IFeature) doesn't provide zoom level

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#373]
IThemeStyle.GetStyle(IFeature) doesn't provide zoom level. But this is obligatory for modern theme styling.

**Comment by charlenni** [comment]
And the next is, that the result of above function is IStyle. With this, one feature could not have more than one style, like LabelStyle and SymbolStyle. To handle this, you should use a StyleCollections, which thows an exception. For this the following code should be used for PointRenderer after `else if (style is VectorStyle)`:

    else if (style is StyleCollection)
    {
        foreach (var s in (StyleCollection)style)
            Draw(canvas, viewport, s, feature, geometry, symbolCache, opacity);
     }

Same should be done for LineString and Polygon.

**Comment by pauldendulk** [comment]
About passing the zoom level. My idea was to pass the resolution this method. The resolution should be determined from the level early on, while parsing the style json. 

The zoom level is something that is convenient for the end user but the internal working should not depend on it. I think this could all kinds of complications. For instance when the number of levels changes during run time.

**Comment by pauldendulk** [comment]
About StyleCollection. That might be a good idea. Although I was thinking about removing style collection to replace it with an IEnumerable of style everywhere. So the Layer.Style would also be an IEnumerable. The Feature styles already is. 

But I am not sure if this is what you want in this use case. Because the list of style will be rendered in one step. So all the styles of one feature will be drawn on top of the feature next to it. 

You could also set the StyleCollection on the layer and let each style in that collection be a ThemeStyle.

**Comment by charlenni** [comment]
StyleCollection is usefull for POIs. They have a SymbolStyle and a LabelStyle. So I need a StyleCollection or something else. I'm fine with StyleCollection. It could be implemented without any API changes, because it is only a render thing.

To set style on layer isn't possible, because style depends on tags of each feature and zoom level/resolution. So I should create the style each time the feature is rendered.

Regarding resolution and zoom level: You suggest, that we should use all over the library resolution instead of zoom level. Would be possible, but we have to look into HttpTileSource and MbTilesTileSource, which uses zoom level and theme files should be parsed while loading to replace all occurences of zoom levels.

Yes, I implemented GetStyle this way as you suggested, but only in my test environment. If you like, I could try to make a PR in the next days.

**Comment by pauldendulk** [comment]
Thanks but I will look at the GetStyle changes my self. It is a small change, I just want to have a look at possible consequences.

**Comment by charlenni** [comment]
Thanks for this.

Perhaps other things are useful too, like layer, to which the feature belongs. Or should this be known by IThemeStyle, because it belongs to a layer.

**Comment by charlenni** [comment]
@pauldendulk is there any date, when you could look into this?

**Comment by pauldendulk** [comment]
I did take a look and did not see a solution that I felt good about. Could you perhaps work around it by adding a Map (of Viewport) field to your custom ThemeStyle, set it at construction and get the resolution from that object?

**Comment by charlenni** [comment]
Do you have any link to this?

**Comment by charlenni** [comment]
Ok, than I try this.

Perhaps there is room for further improvements, when I could precalc the styles for a zoom level and than recalc them, if the resolution of the viewport changes.

**Comment by pauldendulk** [comment]
I don't have a link. My idea was that you created your own ThemeStyle (perhaps inherit) that has a Viewport member that you could use this field inside the GetStyle method.

**Comment by charlenni** [comment]
Yes, I will do it this way. 

I thought about a link to the Mapbox gradient example.

**Comment by pauldendulk** [comment]
With the mapbox gradient I meant the step wise opacity that you described in another issue. I use the term 'gradient' because it reminds me about how color gradients are defined.
