### ISSUE TITLE
DetermineResolutions of Map.cs doesn't work correct

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#379]
If I add a TileSource, which has up to 31 resolutions (zomm level 0 to 30), DetermineResolution returns only the first 19 of them.

**Comment by pauldendulk** [comment]
What kind of tilesource?

The level are read from the metadata if possible. You can override the schema explicitly.

**Comment by charlenni** [comment]
The Scheme has 31 levels (0 to 30) and the correct Resolutions array with all possible resolutions. But than comes DetermineResolution and removes resolutions from Resolutions. It is, because normalized is getting smaller than normalizedDistanceThreshold. If I reduce normalizedDistanceThreshold in source code, I get some more resolutions :)

**Comment by pauldendulk** [comment]
some, more there are still some missing?

So the resolutions that you added were not just more detailed but were smaller steps than usual?

**Comment by charlenni** [comment]
No, I added a normal global mercator scheme with 31 levels (0 to 30). If you do this, you get around 20 levels.

**Comment by pauldendulk** [comment]
I somehow committed Math.Pow(resolution, 2) instead of the Math.Low(resolution, 2) that I worked with during development.

**Comment by pauldendulk** [comment]
Should be fixed with the latest commit.
