### ISSUE TITLE
Use Non-Mercator Projection for Base Map

### ISSUE THREAD

**Issue by scottdewald** [pauldendulk/Mapsui#38]
I have some map images that were created using the WGS84 (EPSG:4326) projection. I see that I can set ILayer.CRS so that geometries will be tranformed appropriately if necessary, but I don't think this will be valid for images as the insides of the images need to be projected accordingly in a non-linear fashion instead of just the vertices.

I was wanting to change my main map and all layers to be EPSG:4326, but it appears the calculations within Mapsui.Viewport make it dependent on a Mercator projection. Is this correct? If not, how do I create a WGS84 viewport?

Thanks

**Comment by pauldendulk** [comment]
You are correct, projections are not supported for images. (I think Felix Obermaier did create something for that, but not for Mapsui). 

Mapsui.Viewport is independent on a specific projection. It assumes all data it manipulates is in the same projection. If all your data is in EPSG:4326 it should work properly. 

Your problem might be that the projection module tries to project data that should not be projected. Check all your CRS string are actually EPSG:4326 or null.

**Comment by scottdewald** [comment]
OK, great. Then I'll keep looking into it to see what I'm doing wrong.

Are the units of IViewport.Resolution m/pixel or are they projection_units/pixel?

**Comment by pauldendulk** [comment]
projection_units/pixel

**Comment by scottdewald** [comment]
Sweet, got an example working with WGS84 base maps. I had the IViewport.Resolution incorrect. I was thinking it was m/pixel. Thanks for your help.
