### ISSUE TITLE
Extend MouseWheel event

### ISSUE THREAD

**Issue by gaurav230394** [pauldendulk/Mapsui#384]
I am unable to extend Mapcontrol MouseWheel event. I have done something like:
mapControl.MouseWheel += MapControl_MouseWheel1; (at initialization of map control).
Even I have extended one other event (MouseLeftButtonUp) similar way and it is working fine. Please let me know if I am doing something wrong.

**Comment by pauldendulk** [comment]
It is now published in 1.3.3 beta 2: https://www.nuget.org/packages/Mapsui/1.3.3-beta.2
