### ISSUE TITLE
Mapsui.Sample.iOS needs Xamarin.Business 

### ISSUE THREAD

**Issue by kochizufan** [pauldendulk/Mapsui#43]
Hello.

I'm Xamarin Indie user, and I try to compile Mapsui.Sample.iOS, it shows 

"Your app is using an assembly that requires Xamarin.iOS Business edition or higher."
"Your app is using the assembly 'System.ServiceModel.Web'."

Is System.ServiceModel.Web needed for iOS project?
If not so, please remove dependency for it, to compile with Indie edition.

**Comment by pauldendulk** [comment]
This issues has been reported before and was closed because there was no followup. I will close this one and reopen the other one because it has more information
https://github.com/pauldendulk/Mapsui/issues/27

**Comment by pauldendulk** [comment]
@kochizufan I suggested a solution perhaps you could test it https://github.com/pauldendulk/Mapsui/issues/27
