### ISSUE TITLE
Mapsui.Samples.Android cannot compile with Xamarin Studio

### ISSUE THREAD

**Issue by kochizufan** [pauldendulk/Mapsui#44]
Mapsui.Samples.Android cannot compile with Xamarin Studio, with showing this error:

/Users/kokogiko/Projects/Mapsui/Samples/Mapsui.Samples.Android/Properties/AndroidManifest.xml: Warning XA0101: @(Content) build action is not supported (XA0101) (Mapsui.Samples.Android)

How can I solve this problem?

**Comment by kochizufan** [comment]
Sorry, I found the solution.
http://stackoverflow.com/questions/30324099/xamarin-build-action-warning-xa0101

**Comment by pauldendulk** [comment]
The questions mentions a 'warning' but you got an 'error'? Could have changed with another update?

I will change it. A PR is also welcome.
