### ISSUE TITLE
Remove all NotImplementedExceptions from the geometries

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#5]
Just wanted to check if a Polygon intersects a BoundingBox to find out that all of the intersects methods throw NotImplementedException. 
Any plans to implement the methods for all of the Geometries, or can you recommend another library I could reference to do those more and less complex collision-checks?
comments

pauldendulk wrote Apr 19, 2013 at 3:06 PM [x]

This is long standing issue inherited from from the original SharpMap version it was ported from. They should be either implemented or removed.

You could try to use NTS for this:
http://nettopologysuite.googlecode.com/svn/trunk/
You need to convert the geometries though. And I think NTS supports only desktop and Silverlight. Hopefully it could be ported to PCL someday.
pauldendulk wrote Apr 21 at 10:20 PM [x]

There is now a PCL version of NTS. The plan is to replace the current geometries with NTS.

**Comment by kwesolowski** [comment]
NTS moved to GitHub:
https://github.com/NetTopologySuite/NetTopologySuite


We are evaluating mapsui as visual part of distributed app, and we are also looking for SpatialReleations Library. Is NTS still considered to be future lib for Mapsui?

**Comment by pauldendulk** [comment]
Yes, this is still on the wish list. I am following NTS on github and they are dealing with all issues carefully. 

I have no immediate need for it in my own projects so i do not know when this will be done.

**Comment by pauldendulk** [comment]
Since we would like to move away from LGPL NTS is not a good option. I don't see good alternatives at the moment. Perhaps the current geometries should be simplified and NotImplementedExceptions should be removed.

**Comment by pauldendulk** [comment]
Before 1.0 we will not switch to another geometry library. I cleaned up the current geometries. Removed all NotImplementedExceptions. Implemented Within and Distance for polygon (only exterior ring at the moment). Used this in feature info. Added a sample. See this commit and predecessors:
172c1c3f4a05d4cabaf96b141833580c0cb69bab
