### ISSUE TITLE
MapsUI.Geometries.Geometry Clone() method must be marked as virtual

### ISSUE THREAD

**Issue by Shchyekinyanin** [pauldendulk/Mapsui#51]
I have class with geometry property and need Clone method. But I can not just call Geometry.Clone() (it raises error)

Maybe Geometry.Clone() method must be marked as virtual?

**Comment by Shchyekinyanin** [comment]
Resolved. I changed field type to IGeometry and use Copy() method from GeometryExtensions.
In the future, I will take a closer. 
I'm sorry to distract you.

**Comment by pauldendulk** [comment]
Thanks for the update.
