### ISSUE TITLE
How to add a local raster image(*.tif or *.img) to the Map?

### ISSUE THREAD

**Issue by chenguanzhou** [pauldendulk/Mapsui#57]
For the SharpMap project , this function is included in SharpMap.Extensions Component

**Comment by pauldendulk** [comment]
There are several ways

1) If you raster needs to be rotated you could use a PointSymbol with world units. There is a sample in Samples\Mapsui.Samples.Wpf. Zoom into the netherlands to view it. You can find the code by digging deeper from Window1.xaml.cs\Window1.PointSymbolsClick. 

2) Use the GeoTiffProvider (only for GeoTiffs). It reads the bounding box from the tiff.

3) You could add a Raster with a bounding box just as this is done for all the tiles. This can not be rotated. Create your own memory provider and add a Raster Feature. Create like:
> _feature = new Feature { Geometry = new Raster(data, _extent) };

**Comment by anushabasavaraj92** [comment]
I have to load a raster image of large size(500 mb). I have loaded it successfully. But, the responsiveness of the mapcontrol has decreased considerably. Is there a way to overcome this issue?
