### ISSUE TITLE
Whitish maps

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#60]
I am currently running over a really strange issue while trying the Android demo app.
The maps is all white.
( Android 5.1.1 / Huawei Honor X2 phone )

What could be causing this issue ?
![screenshot_2015-12-20-02-00-30](https://cloud.githubusercontent.com/assets/6534199/11915760/0eefbbae-a6be-11e5-867f-33ddf3e817d5.png)
![screenshot_2015-12-20-02-00-44](https://cloud.githubusercontent.com/assets/6534199/11915761/0f089638-a6be-11e5-9291-6f7bf9ead5e1.png)

**Comment by pauldendulk** [comment]
The sample display is correct. The base layer in the sample is KnownTileSource.EsriWorldReferenceOverlay which looks like this. It is not a great choice for a baselayer though. I wil change it to KnownTileSource.OpenStreetMap. Thanks for noticing this.

**Comment by YordanYanakiev** [comment]
Awesome! You are just awesome Paul :)
Thanks !.
btw - it does not show any hints by some reason. is there some documentation or some sort of examples like :
- Creating custom markers with on click / tap events ?
- Showing label and image on a marker ?
- Creating a polyline based on latlng's ?
- Getting the length in km of a polyline ?
ets geo stuff..
