### ISSUE TITLE
Please refresh the code to match the new iOS9.2 / Xcode 7.2 requirements

### ISSUE THREAD

**Issue by NopeLord** [pauldendulk/Mapsui#61]
Please refresh the code to match the latest Apple requirements and Xamarin forms if possible, since Your map solution is just great, and We would very love to use.

Thanks in advance

**Comment by pauldendulk** [comment]
okay, I'll have a look when I'm on a mac.

**Comment by pauldendulk** [comment]
I bought a mac, so that is step one. The rest will follow.

**Comment by pauldendulk** [comment]
Added a new iOS sample. Should be fixed with the next release.
