### ISSUE TITLE
request for a sample

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#63]
I am somehow unable to create a working application.
My aim currently is to create a marker which having some label on top of it, and be able to move it ( if possible without destruction of the original ).
something as follow :
![marker-43n](https://cloud.githubusercontent.com/assets/6534199/13324329/df13cc92-dbe5-11e5-8d5e-ed451f8a87d7.jpg)

Please - add if possible some simple working example for Android / iOS providing such functionality.

**Comment by pauldendulk** [comment]
In Mapsui.Samples.WPF there is a sample called 'Points with animation'. The animation is in the data and works with Xamarin as well. I use it for vehicle tracking app. Did you look at that sample?

**Comment by YordanYanakiev** [comment]
I am currently unable to build anything for windows phone ( neither i own such to run it ), but overall i were researching the samples, but it is a bit distant from what i am used to with google maps api, it is a whole new ideology, and i am very new into it ( for which i would like to be excused if my requests look too newbiesh :) ).

Currently I'm still stuck on the logic of building the markers, since everything i am trying with them leads to a white square or Unhandled Error.

I am adding the sample code I am trying with for Android (and the whole project as an attachment).
`using System;
using System.IO.Compression;

using Android.App;
using Android.Content;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;

using BruTile.Predefined;
using Mapsui.Layers;
using Mapsui.Styles;
using Mapsui.UI.Android;
using Mapsui.Geometries;
using Mapsui.Providers;
using Mapsui.Projection;

using System.IO;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;
using Android.Graphics;



namespace markerTest.Droid
{
	[Activity (Label = "markerTest.Droid", MainLauncher = true, Icon = "@drawable/icon")]
	public class MainActivity : Activity
	{

        MapControl mapControl;

        protected override void OnCreate (Bundle bundle)
		{
			base.OnCreate (bundle);

			// Set our view from the "main" layout resource
			SetContentView ( Resource.Layout.Main );

            var tileLayer = CreateTileLayer();

            mapControl = FindViewById<MapControl>( Resource.Id.mapcontrol );
            mapControl.Map.Layers.Add( tileLayer );

            mapControl.Map.Layers.Add( marker() );

        }

        public static TileLayer CreateTileLayer()
        {
            var tileLayer = new TileLayer( KnownTileSources.Create( KnownTileSource.OpenStreetMap ) );
                tileLayer.Name = "OSM";

            return tileLayer;
        }

        public ILayer marker()
        {
            var iB = BitmapRegistry.Instance.Register( this.GetType().Assembly.GetManifestResourceStream( "markerTest.Droid.Resources.Drawable.markerRed.png" ) );

            var s                = new SymbolStyle();
                s.SymbolType     = SymbolType.Rectangle;
                s.UnitType       = UnitType.Pixel;
                s.SymbolScale    = 0.5;
                s.SymbolRotation = 0.2;
                s.BitmapId       = iB;

            var l             = new LabelStyle();
                l.LabelColumn = "Label";
                l.Text        = "test";

            Feature masterMarker          = new Feature();
                    masterMarker.Geometry = new Mapsui.Geometries.Point( 0, 0 );
                    masterMarker.Styles.Add( l );
                    masterMarker.Styles.Add( s );

           Features ms = new Features();
                     ms.Add( masterMarker );

            Layer r            = new Layer();
                  r.CRS        = "EPSG:4326";
                  r.Name       = "marker1";
                  r.DataSource = new MemoryProvider( ms );

            return r;
        }

    }
}

`

**Comment by YordanYanakiev** [comment]
masterMarker.Styles.Add( l ); - this row leads to "Unhanded Error"
and styling the marker as a bitmap - goes again to a white square as result.

**Comment by YordanYanakiev** [comment]
Just compiled the android sample and tried just to add this row to the original code 

`mapControl.Map.Layers.Add( PointLayerSample.CreateRandomPointLayerWithLabel( new MemoryProvider( new Point( 10, 10 ) ) ) );`

it result immediately on the run an "System.NotImplementedException: The method or operation is not implemented."

**Comment by pauldendulk** [comment]
As I mentioned in #64 labellen does not work yet in Android.
It should be possible to show bitmaps as markers. I can't see anything wrong with your sample code apart from the labels. The Android sample (samples\Mapsui.Samples.Android) uses bitmaps.

**Comment by pauldendulk** [comment]
This is the method in LabelStyle where the label text is retrieved. The three lines are three different methods. You need to pick just one. Just setting Text is the easiest. If you set LabelColumn you need to be sure there is a column that contains the text.
```
        public string GetLabelText(IFeature feature)
        {
            if (LabelMethod != null) return LabelMethod(feature);
            if (LabelColumn != null) return feature[LabelColumn].ToString();
            return Text;
        }
```
None if these function on Android because  ```PlatformLabelBitmap.Create``` is not implemented.
