### ISSUE TITLE
Marker features does not work under Android

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#64]
Just compiled the android sample and tried just to add this row to the original code

mapControl.Map.Layers.Add( PointLayerSample.CreateRandomPointLayerWithLabel( new MemoryProvider( new Point( 10, 10 ) ) ) );

it result immediately on the run an "System.NotImplementedException: The method or operation is not implemented." in Mapsui.Rendering.OpenTK in PlatformLabelBitmap.cs

Probably it is an issue related to the libraries, please - note which libraries You are using into the samples for android. ( currently I am using the nuget version of MapsUI )

is there some specific source for OpenTK which i shall use for Android ?.

**Comment by pauldendulk** [comment]
Sorry, I did not have this clear. Android really does not have an implementation for OpenTK labels. This is a part that needs to be implemented per platform.

https://github.com/pauldendulk/Mapsui/blob/master/Mapsui.Rendering.OpenTK-A/PlatformLabelBitmap.cs

While iOS and desktop have:
https://github.com/pauldendulk/Mapsui/blob/master/Mapsui.Rendering.OpenTK-iOS/PlatformLabelBitmap.cs

https://github.com/pauldendulk/Mapsui/blob/master/Mapsui.Rendering.OpenTK/PlatformLabelBitmap.cs

Android labels is one of my priorities for the coming weeks. 
This is one of

**Comment by YordanYanakiev** [comment]
Unfortunately no marker is shown with or without label feature. It is always turn white square.
If it is possible for a working sample at least for a simple marker without any label - it will clarify a lot.

**Comment by pauldendulk** [comment]
If you download the code and open the solution there is a Android sample with bitmap symbols under de Samples folder called Mapsui.Samples.Android.

This one:
https://github.com/pauldendulk/Mapsui/tree/master/Samples/Mapsui.Samples.Android

**Comment by YordanYanakiev** [comment]
Works perfectly !!!
Thank You very very much Paul den Dulk !
Waiting passionately for the labels.
