### ISSUE TITLE
a suggestion to the MapControl.cs

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#69]
I found a rare bug ( maybe ) which occur when You transit from the map Activity to another activity trough creating an Intent in Android.
Once You finish the work with the new activity and return to the map activity - the screen is darkened, and the map control is dark.
If You touch on it - it resumes work and everything goes normal.
I found that if i force refresh trough call to exposed **RefreshGraphics()** in **MapControl.cs** on "**protected override void OnPostResume()**" in the map activity - the things goes well.
It is probably a lame approach, but it could help to solve the issue.

before: ( Mapsui.UI.Android.MapControl.cs )
```
        private void RefreshGraphics()
        {
            _refreshGraphics = true;
            Invalidate ();
        }
```

after: ( Mapsui.UI.Android.MapControl.cs )
```
        public void RefreshGraphics()
        {
            _refreshGraphics = true;
            Invalidate ();
        }
```

in  Map Activity :
```
        protected override void OnPostResume()
        {
            base.OnPostResume();
            FindViewById<MapControl>(Resource.Id.mapcontrol).RefreshGraphics();
        }
```

**Comment by pauldendulk** [comment]
Made RefreshGraphics() public as suggested.
