### ISSUE TITLE
How to set MapControl background to Transparent?

### ISSUE THREAD

**Issue by IlSocio** [pauldendulk/Mapsui#71]
I tried to set the MapControl background to Transparent but without success... 

Accordingly to this solution http://stackoverflow.com/questions/30787349/make-androidgameview-transparent
I set the AndroidGameView to transparent: 
```
mapControl.SetZOrderOnTop(true);
mapControl.Holder.SetFormat(Format.Transparent);
```
But that was not enough, because the background is drawn by the MapControl itself...

So I had a look at the source code:
https://github.com/pauldendulk/Mapsui/blob/8b4ede5a555c5b137d6cdbce96a5d8d5191346de/Mapsui.UI.Android/MapControl.cs#L264

And tried to set the Alpha to 0 too...
```
mapControl.Map.BackColor.A = 0;
```
but the Alpha doesn't seems to be taken into account.

Does anyone have a solution to set MapControl to transparent?

**Comment by pauldendulk** [comment]
I never did this myself and has so far not been a feature request.

I wonder if the AndroidGameView itself can be used as a fully transparent overlay. If that is possible it should be possible with Mapsui too.

**Comment by pauldendulk** [comment]
You could experiment with the GL.ClearColor in an otherwise empty AndroidGameView.

**Comment by IlSocio** [comment]
I'm getting crazy around the GL.ClearColor :( I need to experiment with the various OpenTK configuration options.

Basically I'd like to overlay a MapControl layer in front of a GoogleMaps control, but GoogleMaps gets totally hidden by the MapControl...

**Comment by pauldendulk** [comment]
Well, what I was trying to say is that it could be that AndroidGameView does not allow transparancy at all. Did you research that with your own AndroidGameView (not Mapsui's)? Since it is OpenGL based it works different than most other Anroid controls. The change to get this to work with the obsoleted MapView is bigger (or actually the Mapsui.Rendering.Android renderer that it is using)

**Comment by pauldendulk** [comment]
btw, to lay two mapcontrols on top of each other might not be the best solution. It is also possible to add a aerial photo layer in Mapsui or to add an overlay to the google maps control. What kind of data would you like to show on top of the google map control?
