### ISSUE TITLE
How to get Coordinates of an image Point?

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#73]
I'm using Viewport.ScreenToWorld() but I don't understand the return. How I can return Lat/Lon given a mouse image position?

**Comment by pauldendulk** [comment]
There are two kind of transformations. 

1. **Transforming between screen and world coordinates**
 The screen coordinates are in the units of your screen (usally pixels). The world coordinates are in the coordinate system of your map (probably SphericalMercator). 

2. **Transforming between different coordinate systems**
Lat/Lon is such a coordinate system (EPSG:4326). Google Maps and OpenStreetMap are using another coordinate system called SphericalMercator (EPSG:3857). These kind of transformation (or projections) can be complicated. Usually this is done with a projection library.

If you are using OpenStreetMap as your background ScreenToWorld will return coordinates in EPSG:3857. So you need to transform this to EPSG:4326. For this one scenario (an no other) there is a helper utility in Mapsui which is called SphericalMercator. You can use it like this:

```
var lonLat = Mapsui.Projection.SphericalMercator.ToLonLat(worldCoordinate);
```

For other kind of projections you need to attach a projection library to Map.Transformation. You have to find yourself a projection library, like [this](https://github.com/NetTopologySuite/ProjNet4GeoAPI) one, and wrap it in a ITransformation implementation.
