### ISSUE TITLE
Some questions about Map.Lock and Scale 

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#74]
I see that Map has a Lock property but in MapControl isn't using. It is because of something??

I need to represent a Scale for the map. Any hints of how to do this? I know I need to get the relation between pixel and meters. Where can I get it?

**Comment by pauldendulk** [comment]
Which platform do you use?

**Comment by 88madri** [comment]
I'm using Windows Desktop (WPF Xaml)

**Comment by pauldendulk** [comment]
There is a ZoomLocked property on the WPF MapControl. Did you try it?

**Comment by 88madri** [comment]
What I want is to disable mouse events on map 

For the scale Can I use ?

```
public double GetMetersPerPixel()
        {
            double metersPerPixel = 0;
            if (MapControl != null)
            {
                var metersWidth = MapControl.Map.Viewport.Extent.Width;
                var pixelsWidth = MapControl.Map.Viewport.Width;

                metersPerPixel = metersWidth / pixelsWidth;
            }
            return metersPerPixel;
        }
```

This is correct??

**Comment by pauldendulk** [comment]
The Viewport.Resolution is in units per pixel. The length of a unit can be different in every coordinate system so you can not use this. 

To calculate the width in meters convert your map coordinates to LatLon then calculate the distance in meters with something like this:

http://stackoverflow.com/questions/837872/calculate-distance-in-meters-when-you-know-longitude-and-latitude-in-java
