### ISSUE TITLE
MapControl refresh problem. 

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#75]
Hi. I'm using WPF Xaml platform.
Sometimes when I'm navigate the map to a certain location, the map does not refresh correctly.
I think the map is already in that new location because of the correct imageToworld Coordinates, but the Tiles of Open Street Map or Bing do not appear. I have to click (MouseUp) to make them show and then they appear instanly (So I think the Tiles are already downloaded). As far I know MouseUp provokes map.ViewChanged(true) InvalidateVisual().

I try with MapControl.Refresh after the navigation with the same results.

**Comment by 88madri** [comment]
I finally found the problem. I need to add new method to Map.Viewport to navigate to new Center and put _modified variable to true.

**Comment by pauldendulk** [comment]
Thanks for reporting back
