### ISSUE TITLE
How to reproject a shapeFile EPSG:4326  to webMercator EPSG:3857

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#78]
I don't know what I'm doing incorrect. I'm loading my shapeFile (countries.shp the same as the Mapsui example) and change the projection to EPSG:3857.

```
 public void LoadSHPLayer(string pathToFile)
        {
            string extension = Path.GetExtension(pathToFile);
            if (extension == SHP_EXTENSION)
            {
                ShapeFile shpResource = new ShapeFile(pathToFile, true);
                if (shpResource != null)
                {
                    var lay = new RasterizingLayer(new Layer
                    {
                        DataSource = shpResource
                    });
                    MapControl.Map.Layers.Clear();
                    MapControl.Map.Layers.Add(lay);
                    MapControl.Map.Transformation = new MinimalTransformation();
                    MapControl.Map.Transformation.Transform(CRS_LAT_LON, CRS_WEB_MERCATOR, MapControl.Map.Viewport.Extent);
                    MapControl.ZoomToFullEnvelope();
                    MapControl.Map.CRS = CRS_WEB_MERCATOR;
                    MapControl.Refresh();
                }
            }
        }
```

I'm using also Bing Maps and OSM tile layers, What I want is to change between these layers and mantain the same level of zoom and pan position. The position is easy becouse I just save the location. But when I save the zoom resolution I cannot use the same between the Shapefile layer and OSM or Bing layer but between OSM and Bing Maps the zoom resolution is the same.

**Comment by pauldendulk** [comment]
So, the transformation itself is correct initially? Things go wrong if you switch between these layers and then things go wrong? 

I would expect no change in MapView at all when you show a different background layer. Could you check what is causing this?

**Comment by 88madri** [comment]
I don't think the transformation is correct because shapeFile Layer and OSM Layer have different resolution units. I can switch between them property but I cannot mantain the zoom level

**Comment by pauldendulk** [comment]
I am closing this issue. I assume there is something wrong with configuring the projection. 

For an example of projection look at:
Samples\Mapsui.Samples.Wpf\Windows1.xaml.cs.ProjectedPointClick

The MinimalTransformation built into Mapsui only projects between WGS84 and SphericalMercator.

If you have more questions just reopen this issue.
