### ISSUE TITLE
using OSM coordinates in Xamarin project

### ISSUE THREAD

**Issue by eakelb** [pauldendulk/Mapsui#83]
Hi, I've got a completly newbie question, but could not find the answer: how do I create a point with coordinates taken from OSM or Google Maps?
Whenever I create it like
`var point = new Point(20, 50)`
i get a point placed very close to the (0, 0), I have to type numbers like 10000 to see the difference but have no idea how to convert it to coordinates known from other maps. I've tried using methods like WorldToScreen, FromLonLat and others but it wouldn't really give any expected result. Can anyone please tell me how to place points correctly?

Here is code:
`
            var mapControl = FindViewById<MapControl>(Resource.Id.mapcontrol);

            var tileLayer = new TileLayer(KnownTileSources.Create()) { Name = "OSM" };
            mapControl.Map.Layers.Add(tileLayer);

            var point = new Point(20, 50);
            var pointLayer = new MemoryLayer
            {
                DataSource = new MemoryProvider(point),
                Style =
                    new SymbolStyle {BitmapId = Methods.GetBitmapIdForEmbeddedResource("App4.Images.blackPoint.png")}
            };
            mapControl.Map.Layers.Add(pointLayer);`

Thanks in advance!

**Comment by eakelb** [comment]
I've finally found out how to solve the problem just half an hour after posting this question, so I just think I'll post the answer in case anyone needed it

first you have to set
`mapControl.Map.Transformation = new MinimalTransformation();'
 and then you can get new points using this code:
`var point = (Point)mapControl.Map.Transformation.Transform("EPSG:4326", "EPSG:3857", new Point(y, x));`
Hope it'll help someone ;)

**Comment by pauldendulk** [comment]
Thanks for posting your answer @eakelb
