### ISSUE TITLE
Missing example with Android/iOS forms ?

### ISSUE THREAD

**Issue by neilRex** [pauldendulk/Mapsui#85]
Could You please post an example with Android/iOS Xamarin Forms, since the PCL method is not much anymore supported and maintained by the big Xamarin components suppliers :|

Thank You in advance, and Thank You for You great work so far ! :)

**Comment by pauldendulk** [comment]
Sorry, I won't be able to work on the in the near future since I am not using Xamarin.Forms myself at the moment.
