### ISSUE TITLE
What is licensing is Mapsui under?

### ISSUE THREAD

**Issue by abhaymin** [pauldendulk/Mapsui#90]
I want to know what license is Mapsui under (MIT, MPL, APACHE, etc..) it is not getting clear in Git or Nuget. Also, can I use this in an commercial purpose?

Thanks

**Comment by pauldendulk** [comment]
The license is LGPL. It was inherited from SharpMap from which it was ported. I added it to the readme (just now). You are free to use it for commercial purposes. Here is a quick summary https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)
