### ISSUE TITLE
Capability - Editing

### ISSUE THREAD

**Issue by abhaymin** [pauldendulk/Mapsui#91]
I have another question in regards to capability of Mapsui for allowing editing of vector feature or capture a new feature in given feature layer as similar to SharpMap. Is there any sample for the same. Thanks.

**Comment by pauldendulk** [comment]
There is no out of the box support for this and there are no samples. The design is such that it is possible to build such functionality on top of it yourself. This has been done in other projects that use Mapsui. Like this one: https://www.youtube.com/watch?v=STx6vko62TE
