### ISSUE TITLE
Polygons & LabelLayers not displaying in Android

### ISSUE THREAD

**Issue by ruairio** [pauldendulk/Mapsui#93]
Hi,

I have a simple Android Activity with a Map and I'm trying to display a random polygon & a labellayer using the sample code provided. Neither work. Am I calling these correctly?

```
  protected override void OnCreate(Bundle bundle)
  {
    base.OnCreate(bundle);
    SetContentView(Resource.Layout.Main);
    var mapControl = FindViewById<MapView>(Resource.Id.mapcontrol);
    mapControl.Map.Layers.Add(new TileLayer(KnownTileSources.Create()) { Name = "OSM" });
    //add polygon
    mapControl.Map.Layers.Add(PointsSample.CreateRandomPolygonLayer(mapControl.Map.Envelope));
    //add stacked label
    var provider = PointsSample.CreateRandomPointsProvider(mapControl.Map.Envelope);
    mapControl.Map.Layers.Add(PointsWithStackedLabelsSample.CreateLayer(provider));
  }
```
![polygonsmissing](https://cloud.githubusercontent.com/assets/20812739/18352051/aa436188-75d4-11e6-8cd4-0491c9b894d4.png)

Thanks,
Ruairi

**Comment by pauldendulk** [comment]
Unfortunately both are not implemented for Android. Stacked-labels has little priority but polygons do. Unfortunately it is not easy to draw polygons with holes in Open.TK. 

I see you are using MapView. MapControl is the newer one, but also has no filles polygons. It has polygon outlines though.
