### ISSUE TITLE
Map pitch on UWP?

### ISSUE THREAD

**Issue by Gh0s7** [pauldendulk/Mapsui#94]
Can't find this anywhere, but I'd like to know if is there a way to apply a pitch projection to map just like in Bing Maps control.

I'd like to be able to input an angle value and have the map pitched based on that value, instead of showing it from top view.

**Comment by pauldendulk** [comment]
What do you mean with pitch projection? The bird' s eye view? This is not supported and won't be supported soon.

**Comment by Gh0s7** [comment]
I'm talking about [this kind of view](https://i-msdn.sec.s-msft.com/en-us/windows/uwp/launch-resume/images/windowsmapsappdirections.png) (not sure if it's called bird view or not).

It's basically a projection on X axis in 3D space.

**Comment by pauldendulk** [comment]
Yes, this is called bird's eye view in de bing maps interface. 

This is not supported. To create something like that I would tilt the map after it is rendered. That would be fairly easy. What makes it harder is that you would also want higher detail tiles on the foreground and lower detail in the background. This will be harder to do.
