### ISSUE TITLE
Load a offline maps with mbTiles

### ISSUE THREAD

**Issue by tabris84** [pauldendulk/Mapsui#95]
I need to load an offline map in my app.
 
I already have the my mbtiles file and I trying to use the constructor for class BruTile.MbTilesTileSource, but apparently it not working. 

How i could load the mbtiles?

Thanks

**Comment by pauldendulk** [comment]
You could take a look at the samples of the itinero MapControl:
https://github.com/itinero/ui/tree/master/samples

Here is the MbTilesSample
https://github.com/itinero/ui/blob/master/samples/Itinero.Code.Samples/MbTilesSample.cs

**Comment by pauldendulk** [comment]
Please let me know if you succeed.
