### ISSUE TITLE
set resolution 

### ISSUE THREAD

**Issue by tabris84** [pauldendulk/Mapsui#96]
I'm working in an Android/iOS application using Xamarin.

I included a Mapsui v 0.9.0 Reference from nuget.
Before i was able to set the zoom when i opened the map but now no.
My old code it's: 
mapControl.Map.Viewport.Resolution= [value of the initial zoom level].

there is a new different way to set the zoom?

Thanks

**Comment by pauldendulk** [comment]
The Resolution property in Viewport still has a setter. What is the problem? You can set it be there is no effect? What if you pan a little after you set it? If it works after pan it is a refresh issue.

**Comment by tabris84** [comment]
thanks for you reply.
I will check if it works setting the parameter after

**Comment by tabris84** [comment]
it works. I inserted a little delay an now it works.
Thanks a lot
